/**
 * Daily / weekly challenges (defs/challenges.ts): keeps the current sets in sync with the UTC
 * date (refresh), tracks their progress from progress signals and grants rewards.
 *
 * Persistence (ProfileData.challenges): the rotation key, the template ids of the generated set and
 * per slot the progress / claimed flag. The set itself is regenerated from the key (deterministic),
 * so a tampered save cannot change targets or rewards; a stored set whose templates no longer match
 * the regenerated one (defs changed) starts over.
 *
 * Rotation: when refresh() finds a new key, completed but unclaimed rewards of the old set are
 * granted first, then the new set starts at 0 and `onRotate` fires.
 */
import type { ChallengeData, ChallengeSetData, ChallengeView } from '../core/contracts';
import type { ChallengePeriod } from '../core/events';
import { CHALLENGE_RULES } from '../defs/challenges';
import {
  generateChallengeSet,
  periodEnd,
  periodKey,
  templateIds,
  type ChallengeInstance,
} from './challengeSeed';
import {
  applySignal,
  beginRunState,
  createConditionState,
  isComplete,
  type ConditionState,
  type ProgressSignal,
} from './signals';

export interface ChallengeHooks {
  /** A challenge reached its target (counted once). */
  onComplete(c: ChallengeInstance): void;
  /** Grant the reward (XP, currency, cosmetic). */
  onClaim(c: ChallengeInstance): void;
  onRotate?(period: ChallengePeriod, key: string): void;
}

interface ActiveSet {
  readonly period: ChallengePeriod;
  key: string;
  instances: ChallengeInstance[];
  states: ConditionState[];
}

const PERIODS: readonly ChallengePeriod[] = ['daily', 'weekly'];

function emptySet(): ChallengeSetData {
  return { key: '', templates: [], slots: [] };
}

function sameIds(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

export class ChallengeTracker {
  private data!: ChallengeData;
  private readonly sets: Record<ChallengePeriod, ActiveSet> = {
    daily: { period: 'daily', key: '', instances: [], states: [] },
    weekly: { period: 'weekly', key: '', instances: [], states: [] },
  };

  constructor(
    data: ChallengeData,
    private readonly hooks: ChallengeHooks,
    private readonly now: () => number = Date.now,
    /** Cosmetic ids a weekly reward slot may grant (defs/cosmetics unlock kind 'challenge'). */
    private readonly cosmeticPool: readonly string[] = [],
    private readonly autoClaim: boolean = CHALLENGE_RULES.autoClaim,
  ) {
    this.attach(data);
  }

  /** Bind to (another) profile's challenge data; stored sets are regenerated from their keys. */
  attach(data: ChallengeData): void {
    this.data = data;
    for (const period of PERIODS) {
      const stored = data[period];
      const set = this.sets[period];
      set.key = stored.key;
      set.instances = stored.key ? generateChallengeSet(period, stored.key, this.cosmeticPool) : [];
      if (!stored.key || !sameIds(stored.templates, templateIds(set.instances))) {
        // Nothing generated yet, or generated by other defs: refresh() starts a fresh set.
        set.key = '';
        set.instances = [];
        data[period] = emptySet();
      }
      this.bindStates(set);
    }
  }

  /** Rotate sets whose UTC day / week ended. Returns true when anything changed. */
  refresh(): boolean {
    const date = new Date(this.now());
    let changed = false;
    for (const period of PERIODS) {
      const key = periodKey(period, date);
      const set = this.sets[period];
      if (set.key === key) continue;
      if (set.key) this.claimCompleted(set);
      set.key = key;
      set.instances = generateChallengeSet(period, key, this.cosmeticPool);
      this.data[period] = {
        key,
        templates: templateIds(set.instances),
        slots: set.instances.map(() => ({ progress: 0, claimed: false })),
      };
      this.bindStates(set);
      this.hooks.onRotate?.(period, key);
      changed = true;
    }
    return changed;
  }

  /** Returns true when persisted data changed. */
  signal(sig: ProgressSignal): boolean {
    let dirty = false;
    for (const period of PERIODS) {
      const set = this.sets[period];
      const slots = this.data[period].slots;
      for (let i = 0; i < set.instances.length; i++) {
        const inst = set.instances[i]!;
        if (inst.condition.metric !== sig.metric) continue;
        const st = set.states[i]!;
        const slot = slots[i]!;
        if (isComplete(inst.condition, st)) continue;
        if (!applySignal(inst.condition, st, sig)) continue;
        slot.progress = st.progress;
        dirty = true;
        if (isComplete(inst.condition, st)) this.completeSlot(set, i);
      }
    }
    return dirty;
  }

  beginRun(): void {
    for (const period of PERIODS) for (const st of this.sets[period].states) beginRunState(st);
  }

  /** Grant a completed, unclaimed challenge's reward. */
  claim(id: string): boolean {
    for (const period of PERIODS) {
      const set = this.sets[period];
      const i = set.instances.findIndex((c) => c.id === id);
      if (i >= 0) return this.claimSlot(set, i);
    }
    return false;
  }

  /** Dev console: complete (and claim) now. */
  complete(id: string): boolean {
    for (const period of PERIODS) {
      const set = this.sets[period];
      const i = set.instances.findIndex((c) => c.id === id || String(c.index) === id);
      if (i < 0) continue;
      const inst = set.instances[i]!;
      const st = set.states[i]!;
      if (isComplete(inst.condition, st)) return false;
      st.progress = inst.target;
      this.data[period].slots[i]!.progress = st.progress;
      this.completeSlot(set, i);
      return true;
    }
    return false;
  }

  instances(): ChallengeInstance[] {
    return [...this.sets.daily.instances, ...this.sets.weekly.instances];
  }

  views(): ChallengeView[] {
    const out: ChallengeView[] = [];
    const date = new Date(this.now());
    for (const period of PERIODS) {
      const set = this.sets[period];
      const slots = this.data[period].slots;
      const endsAt = periodEnd(period, date);
      for (let i = 0; i < set.instances.length; i++) {
        const c = set.instances[i]!;
        const progress = Math.min(set.states[i]!.progress, c.target);
        out.push({
          id: c.id,
          period,
          template: c.template.id,
          name: c.name,
          description: c.description,
          progress,
          target: c.target,
          completed: progress >= c.target,
          claimed: slots[i]?.claimed === true,
          xp: c.xp,
          currency: c.currency,
          cosmetic: c.cosmetic,
          endsAt,
        });
      }
    }
    return out;
  }

  private bindStates(set: ActiveSet): void {
    const stored = this.data[set.period];
    // Slots beyond the set are dropped; missing ones start at 0.
    stored.slots.length = Math.min(stored.slots.length, set.instances.length);
    set.states = set.instances.map((c, i) => {
      let slot = stored.slots[i];
      if (!slot) {
        slot = { progress: 0, claimed: false };
        stored.slots[i] = slot;
      }
      const st = createConditionState(Math.min(slot.progress, c.target), slot.seen ?? []);
      slot.progress = st.progress;
      return st;
    });
  }

  private completeSlot(set: ActiveSet, i: number): void {
    const inst = set.instances[i]!;
    if (set.period === 'daily') this.data.completedDaily++;
    else this.data.completedWeekly++;
    this.hooks.onComplete(inst);
    if (this.autoClaim) this.claimSlot(set, i);
  }

  private claimSlot(set: ActiveSet, i: number): boolean {
    const inst = set.instances[i];
    const slot = this.data[set.period].slots[i];
    const st = set.states[i];
    if (!inst || !slot || !st || slot.claimed || !isComplete(inst.condition, st)) return false;
    slot.claimed = true;
    this.hooks.onClaim(inst);
    return true;
  }

  private claimCompleted(set: ActiveSet): void {
    for (let i = 0; i < set.instances.length; i++) this.claimSlot(set, i);
  }
}
