/**
 * Berserker – enemy type def (M6). Import runtime values only from '../enemyCommon' and TYPES from
 * '../enemies' (runtime cycle otherwise).
 *
 * Heavy humanoid brute (brute brain, heavy token pool: one heavy melee attacker at a time) with
 * bone cleavers for forearms: a cleave chains into a backhand and an overhead crush (combo – each
 * link only while the player stays in reach), a lunge closes gaps. Below half health it roars and
 * enrages: faster, faster swings, glowing veins, no more staggers. Slower than a leaper, far faster
 * than a tank. Counterplay: step out of reach between links (the crush telegraphs with a glint and
 * can be jumped), stagger it before it enrages, shoot the glowing heart between its ribs (×2) or
 * the head; the bone plates on shoulders and forearms shrug bullets off.
 */
import type { EnemyTypeDef } from '../enemies';

export const BERSERKER_ENEMY: EnemyTypeDef | null = {
  id: 'berserker',
  name: 'Berserker',
  brain: 'brute',
  health: 560,
  surface: 'flesh',
  // The bone plates spark and shrug hits off; flesh, head and heart bleed.
  zoneSurfaces: { shield: 'armor' },
  movement: { walkSpeed: 2.5, runSpeed: 5.4, acceleration: 18, turnRateDeg: 280, stride: 2 },
  nav: { radius: 0.55, height: 2.1, separation: 0.9 },
  collider: { radius: 0.5, height: 2 },
  zoneMultipliers: { head: 1.5, weakpoint: 2, shield: 0.35, limb: 0.8 },
  armor: { flat: 3, minFraction: 0.5, zones: ['shield'] },
  resist: {},
  stagger: { threshold: 120, decayPerSecond: 50, duration: 0.8, immunity: 2.5, weakpointMultiplier: 1.5 },
  knockbackResistance: 0.8,
  attacks: [
    {
      id: 'cleave',
      kind: 'melee',
      minRange: 0,
      range: 2.7,
      windup: 0.55,
      strike: 0.14,
      recover: 0.3,
      cooldown: 3.2,
      damage: 13,
      priority: 3,
      usesSlot: true,
      requiresLos: true,
      trackTurnRateDeg: 200,
      shake: 0.35,
      sound: 'enemy.berserker.cleave',
      combo: 'backhand',
      melee: { reach: 2.4, coneDeg: 150, height: 1.7 },
    },
    {
      id: 'backhand',
      kind: 'melee',
      minRange: 0,
      range: 2.7,
      windup: 0.32,
      strike: 0.14,
      recover: 0.25,
      cooldown: 0.4,
      damage: 13,
      priority: 0,
      usesSlot: false,
      requiresLos: true,
      trackTurnRateDeg: 260,
      shake: 0.35,
      sound: 'enemy.berserker.backhand',
      combo: 'crush',
      scripted: true,
      melee: { reach: 2.4, coneDeg: 150, height: 1.7 },
    },
    {
      id: 'crush',
      kind: 'slam',
      minRange: 0,
      range: 2.8,
      windup: 0.5,
      strike: 0.16,
      recover: 1,
      cooldown: 0.6,
      damage: 22,
      priority: 0,
      usesSlot: false,
      requiresLos: true,
      trackTurnRateDeg: 140,
      shake: 0.6,
      sound: 'enemy.berserker.crush',
      scripted: true,
      telegraph: { effect: 'enemy.telegraph.crush', socket: 'blades', scale: 1 },
      slam: {
        radius: 2.8,
        innerRadius: 1.2,
        minFactor: 0.4,
        height: 1,
        socket: 'blades',
        forward: 1.6,
        effect: 'land.heavy',
        effectScale: 1.4,
        nearShake: 0.3,
        shakeRadius: 8,
      },
    },
    {
      id: 'lunge',
      kind: 'charge',
      minRange: 4.5,
      range: 11,
      windup: 0.6,
      strike: 1,
      recover: 0.7,
      cooldown: 6,
      damage: 18,
      priority: 1,
      usesSlot: false,
      requiresLos: true,
      trackTurnRateDeg: 200,
      shake: 0.55,
      sound: 'enemy.berserker.lunge',
      charge: {
        speed: 10.5,
        maxDistance: 11,
        turnRateDeg: 35,
        leadFactor: 0.3,
        hitRadius: 1.1,
        wallProbe: 0.5,
        startClearance: 1.5,
        probeHeight: 0.8,
        wallStagger: 1.2,
        overshoot: 2.5,
        wallEffect: 'land.heavy',
        wallEffectScale: 1.1,
        wallShake: 0.35,
        shakeRadius: 7,
      },
    },
    // Enrage roar (started by the host): a harmless ground shockwave – the shake and the cloud
    // announce the second phase; its wind-up is a free damage window.
    {
      id: 'roar',
      kind: 'slam',
      minRange: 0,
      range: 3,
      windup: 0.55,
      strike: 0.25,
      recover: 0.6,
      cooldown: 0.6,
      damage: 0,
      priority: 0,
      usesSlot: false,
      requiresLos: false,
      trackTurnRateDeg: 120,
      shake: 0,
      sound: 'enemy.berserker.roar',
      scripted: true,
      telegraph: { effect: 'enemy.telegraph.roar', socket: 'head', scale: 1 },
      slam: {
        radius: 0.1,
        innerRadius: 0.05,
        minFactor: 0,
        height: 0,
        socket: 'head',
        forward: 0,
        effect: 'enemy.berserker.roar',
        effectScale: 1,
        nearShake: 0.45,
        shakeRadius: 16,
      },
    },
  ],
  perception: {
    sightRange: 32,
    fovDeg: 120,
    hearingRadius: 30,
    memory: 8,
    eyeSocket: 'head',
    eyeHeight: 1.85,
  },
  brute: {
    runDistance: 5,
    standoff: 1.7,
    engageDistance: 9.5,
    waitRadius: 6.5,
    waitSlack: 1,
    laneCheckInterval: 0.4,
  },
  enrage: {
    healthFraction: 0.5,
    speedMultiplier: 1.35,
    attackRate: 1.3,
    damageMultiplier: 1.15,
    staggerImmune: true,
    roar: 'roar',
    glow: 1.8,
  },
  emergeTime: 1.3,
  death: { collapse: 1, linger: 0.9, dissolve: 1.3, burst: null },
  breach: { attack: 'cleave', segmentTime: 2, segmentsPerTear: 1 },
  slotPool: 'heavy',
  slotCost: 1,
  points: { hit: 10, kill: 180, headshotBonus: 50, weakpointBonus: 60 },
  audio: {
    spawn: 'enemy.berserker.spawn',
    alert: 'enemy.berserker.alert',
    hurt: 'enemy.berserker.hurt',
    death: 'enemy.berserker.death',
    step: 'enemy.berserker.step',
    idle: 'enemy.berserker.idle',
    idleInterval: [3.5, 8],
  },
};
