/**
 * Energy / experimental weapons and the launcher – all box only (Rift-Kiste). Angles in DEGREES,
 * times in seconds, distances in meters, rates in rpm. No casings; cells/tanks/drums instead of
 * magazines. Kind data (`projectile`, `beam`, `charge`) drives the fire-kinds engine.
 *
 * Feel targets:
 * - PL-2 „Sonnenwind“ (projectile): 480 rpm plasma bolts at 85 m/s with a small splash (38 direct +
 *   22 splash) – forgiving against swarms, readable glowing bolts, a soft rhythmic sway.
 *   Forge: Sonnensturm (burning bolts) → Koronaauswurf (faster bolts, crit rhythm) → Supernova
 *   (bigger fire bursts that arc to neighbours).
 * - EX-1 „Kettenblitz“ (beam): a crackling shock beam, 300 DPS on the primary target and arcs that
 *   jump to three more (×0.7 each hop). 100-cell charge = 10 s of lightning; no aim kick, a jitter.
 *   Forge: Gewitterzelle (stuns) → Donnergott (drains life) → Weltengewitter (strikes explode).
 * - RG-9 „Lanze“ (charge): hold 1.1 s to charge (auto-fires 1.5 s after full), release: a 450
 *   damage rail that pierces every body in the line. Underpowered below 35 % (fizzle, no ammo).
 *   Forge: Speer (shock build-up) → Donnerspeer (faster charge, arcs) → Weltenspeer (the rail
 *   ricochets through the room three times).
 * - FW-4 „Inferno“ (beam cone): 12° cone, 9 m, 132 DPS to everything inside + burn; 150 fuel =
 *   10 s. Reload: tank off, tank on, pilot ignites.
 *   Forge: Feuersturm (heavier burn) → Höllenglut (burning pools on kills) → Schwarzes Feuer
 *   (void flames that still burn – void amplifies the burn).
 * - GL-6 „Donnerkeil“ (launcher, projectile): 6-round revolving drum, bouncing grenades (two
 *   bounces or a 1.6 s fuse, direct hits detonate), 4.5 m blast, 260 damage. Shell-by-shell
 *   reload. The player takes 35 % of their own blast.
 *   Forge: Donnerschlag (incendiary kills) → Sturmfaust (shock arcs) → Sternenregen (three
 *   grenades per shot).
 * - SX-0 „Ereignishorizont“ (projectile): a slow void orb (14 m/s) that bursts on the first body or
 *   wall it touches (or after 1.6 s) into a 7 m singularity: pulls the horde in for 3.5 s, then
 *   collapses (600 void).
 *   Three per cell. Forge: Singularität (void marks) → Schwarzschild (crit rhythm) → Urknall
 *   (kills inside spawn more singularities).
 */
import type { WeaponDef } from '../weapons';
import {
  FIRE_POOL,
  MAG_STEPS,
  MELEE_BASH,
  MELEE_HEAVY,
  SHELL_STEPS,
  VOID_MAW,
  conventionAudio,
  explosion,
  field,
  forgeTier,
} from './common';

/** Projectile / beam ranges are the reach of aim assist and falloff; flight is bounded by lifetime. */
export const ENERGY = {
  plasma: {
    id: 'plasma',
    name: 'PL-2 „Sonnenwind“',
    shortName: 'PL-2',
    description: 'Plasmagewehr. Glühende Bolzen mit kleiner Detonation – der Sonnenwind im Korridor.',
    category: 'energy',
    kind: 'projectile',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 38,
      headMultiplier: 1.6,
      limbMultiplier: 0.85,
      weakpointMultiplier: 2,
      falloffStart: 40,
      falloffEnd: 90,
      minFalloffMultiplier: 0.8,
      element: 'physical',
      impulse: 1.4,
      propImpulse: 50,
    },
    pellets: 1,
    rpm: 480,
    magazine: 40,
    reserve: 320,
    chambered: false,
    reload: {
      // magOut = the spent cell ejects, magIn = fresh cell, boltRelease = the coils vent.
      tactical: 2,
      empty: 2.5,
      tacticalSteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.25 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.38 },
        { step: 'magIn', at: 1.2 },
        { step: 'boltRelease', at: 1.95 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.4,
      ads: 0.25,
      moveAdd: 0.9,
      airAdd: 2.2,
      crouchMultiplier: 0.8,
      perShotBloom: 0.12,
      bloomMax: 1.8,
      recoveryPerSec: 7,
      recoveryDelay: 0.16,
    },
    recoil: {
      // Soft rhythmic sway, little climb: the bolts' travel time is the challenge, not the kick.
      pattern: [
        [0, 0.4],
        [0.06, 0.42],
        [-0.04, 0.44],
        [0.08, 0.4],
        [-0.06, 0.38],
        [0.04, 0.36],
        [-0.04, 0.35],
      ],
      patternRepeatFrom: 3,
      randomYaw: 0.08,
      randomPitch: 0.05,
      recoveryPerSec: 8,
      recoveryDelay: 0.14,
      resetTime: 0.3,
      adsMultiplier: 0.65,
      crouchMultiplier: 0.85,
      kickTime: 0.04,
      viewPunch: { pitch: 0.6, yaw: 0.25, roll: 0.4 },
      visualKick: { back: 0.025, up: 0.006, side: 0.002, pitch: 3, yaw: 0.6, roll: 1 },
      shake: 0.1,
    },
    ads: {
      zoom: 0.8,
      inTime: 0.22,
      outTime: 0.16,
      moveSpeedMultiplier: 0.72,
      sensitivityMultiplier: 0.9,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 150,
    equipTime: 0.55,
    holsterTime: 0.32,
    sprintToFireTime: 0.18,
    inspectTime: 2.8,
    melee: MELEE_BASH,
    tracer: { everyNth: 0, color: 0x7fd8ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.plasma', impact: 'impact.plasma', casing: null, muzzleLightColor: 0x6fc8ff },
    audio: conventionAudio('plasma', 'energy'),
    rumble: { strong: 0.18, weak: 0.4, ms: 50 },
    model: 'plasma',
    cost: 2500,
    boxOnly: true,
    attachmentSlots: ['optic', 'muzzle', 'magazine', 'laser'],
    projectile: {
      speed: 85,
      gravity: 0,
      radius: 0.07,
      lifetime: 1.8,
      bounces: 0,
      restitution: 0,
      fuse: 0,
      pierce: 0,
      homing: 0,
      explosion: explosion('physical', 1.4, 22, { small: true, minFalloff: 0.4, vfx: 'impact.plasma' }),
      field: null,
      visual: 'projectile.plasma',
      trail: 'trail.plasma',
      flightAudio: 'projectile.plasma.flight',
    },
    upgrades: [
      forgeTier(
        1,
        'PL-2 „Sonnensturm“',
        { damage: 1.6, magazine: 1.5, reserve: 1.5 },
        { kind: 'elementProc', element: 'fire', chance: 0.25, amount: 12 },
      ),
      forgeTier(
        2,
        'PL-2 „Koronaauswurf“',
        { damage: 1.35, rpm: 1.15, projectileSpeed: 1.3 },
        { kind: 'critBurst', everyNth: 6, multiplier: 2.5 },
      ),
      forgeTier(
        3,
        'PL-2 „Supernova“',
        { damage: 1.25, blastRadius: 1.6, element: 'fire' },
        { kind: 'chainArc', chance: 0.35, count: 2, range: 6, damage: 50 },
        { tracerColor: 0xffc07a },
      ),
    ],
  },

  chainlightning: {
    id: 'chainlightning',
    name: 'EX-1 „Kettenblitz“',
    shortName: 'EX-1',
    description: 'Experimenteller Blitzwerfer. Ein Strahl, der von Feind zu Feind springt.',
    category: 'energy',
    kind: 'beam',
    fireMode: 'auto',
    burst: null,
    // Per beam tick (`beam.tickRate`); arcs keep ×0.7 per hop.
    damage: {
      base: 30,
      headMultiplier: 1.3,
      limbMultiplier: 0.9,
      weakpointMultiplier: 1.5,
      falloffStart: 8,
      falloffEnd: 16,
      minFalloffMultiplier: 0.7,
      element: 'shock',
      impulse: 0.3,
      propImpulse: 12,
    },
    pellets: 1,
    // Equals the beam tick rate (10/s); beams fire per tick, not per round.
    rpm: 600,
    magazine: 100,
    reserve: 400,
    chambered: false,
    reload: {
      tactical: 2.2,
      empty: 2.7,
      tacticalSteps: [
        { step: 'magOut', at: 0.45 },
        { step: 'magIn', at: 1.35 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.3 },
        { step: 'boltRelease', at: 2.1 },
      ],
      perShell: null,
    },
    spread: {
      hip: 0.8,
      ads: 0.3,
      moveAdd: 0.4,
      airAdd: 1,
      crouchMultiplier: 0.9,
      perShotBloom: 0,
      bloomMax: 0,
      recoveryPerSec: 5,
      recoveryDelay: 0.15,
    },
    recoil: {
      // The beam writhes: a faint jitter, no climb.
      pattern: [
        [0, 0.06],
        [0.05, 0.05],
        [-0.05, 0.05],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.08,
      randomPitch: 0.05,
      recoveryPerSec: 6,
      recoveryDelay: 0.12,
      resetTime: 0.3,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.9,
      kickTime: 0.05,
      viewPunch: { pitch: 0.2, yaw: 0.25, roll: 0.3 },
      visualKick: { back: 0.006, up: 0.002, side: 0.004, pitch: 0.6, yaw: 0.8, roll: 0.8 },
      shake: 0.05,
    },
    ads: {
      zoom: 0.85,
      inTime: 0.24,
      outTime: 0.16,
      moveSpeedMultiplier: 0.7,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 18,
    equipTime: 0.6,
    holsterTime: 0.34,
    sprintToFireTime: 0.2,
    inspectTime: 3,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0x9fc8ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.shock', impact: 'impact.shock', casing: null, muzzleLightColor: 0x8fb8ff },
    audio: conventionAudio('chainlightning', 'energy'),
    rumble: { strong: 0.15, weak: 0.45, ms: 60 },
    model: 'chainlightning',
    cost: 3000,
    boxOnly: true,
    attachmentSlots: ['optic', 'muzzle', 'magazine'],
    beam: {
      range: 18,
      tickRate: 10,
      coneDeg: 0,
      chain: { count: 3, range: 6, damageKeep: 0.7 },
      ammoPerSecond: 10,
      visual: 'beam.lightning',
      loopAudio: 'weapon.chainlightning.loop',
    },
    upgrades: [
      forgeTier(
        1,
        'EX-1 „Gewitterzelle“',
        { damage: 1.6, magazine: 1.5, reserve: 1.5, range: 1.2 },
        { kind: 'elementProc', element: 'shock', chance: 0.5, amount: 15 },
      ),
      forgeTier(
        2,
        'EX-1 „Donnergott“',
        { damage: 1.35, range: 1.15, reloadTime: 0.8 },
        { kind: 'lifesteal', fraction: 0.01 },
      ),
      forgeTier(
        3,
        'EX-1 „Weltengewitter“',
        { damage: 1.3, magazine: 1.34 },
        {
          kind: 'explosiveRounds',
          chance: 0.08,
          explosion: explosion('shock', 2.5, 90, { small: true }),
        },
      ),
    ],
  },

  railgun: {
    id: 'railgun',
    name: 'RG-9 „Lanze“',
    shortName: 'RG-9',
    description: 'Elektromagnetische Schiene. Aufladen, loslassen – ein Geschoss, das alles durchschlägt.',
    category: 'energy',
    kind: 'charge',
    fireMode: 'semi',
    burst: null,
    // At full charge; `charge.damageAtMin` scales it down for early releases.
    damage: {
      base: 450,
      headMultiplier: 2,
      limbMultiplier: 0.85,
      weakpointMultiplier: 2.5,
      falloffStart: 150,
      falloffEnd: 300,
      minFalloffMultiplier: 0.85,
      element: 'physical',
      impulse: 6,
      propImpulse: 300,
    },
    pellets: 1,
    // Recovery after a shot before the next charge can start.
    rpm: 50,
    magazine: 6,
    reserve: 30,
    chambered: false,
    reload: {
      tactical: 2.8,
      empty: 3.3,
      tacticalSteps: [
        { step: 'magOut', at: 0.5 },
        { step: 'magIn', at: 1.6 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.48 },
        { step: 'magIn', at: 1.55 },
        { step: 'boltRelease', at: 2.6 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.2,
      ads: 0.02,
      moveAdd: 1.5,
      airAdd: 3,
      crouchMultiplier: 0.8,
      perShotBloom: 0,
      bloomMax: 0,
      recoveryPerSec: 5,
      recoveryDelay: 0.2,
    },
    recoil: {
      pattern: [[0, 6]],
      patternRepeatFrom: 0,
      randomYaw: 0.8,
      randomPitch: 0.5,
      recoveryPerSec: 12,
      recoveryDelay: 0.15,
      resetTime: 1.2,
      adsMultiplier: 0.6,
      crouchMultiplier: 0.8,
      kickTime: 0.08,
      viewPunch: { pitch: 5, yaw: 1, roll: 3 },
      visualKick: { back: 0.15, up: 0.04, side: 0.01, pitch: 14, yaw: 2, roll: 5 },
      shake: 0.55,
    },
    ads: {
      // ~2× (horizontal FOV × 0.55 at 90°).
      zoom: 0.55,
      inTime: 0.32,
      outTime: 0.2,
      moveSpeedMultiplier: 0.55,
      sensitivityMultiplier: 0.7,
    },
    // Pierces every body in the line (up to COMBAT.maxPenetrations), armor included.
    penetration: { power: 8, damageKeep: 0.9 },
    range: 400,
    equipTime: 0.7,
    holsterTime: 0.4,
    sprintToFireTime: 0.28,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 1, color: 0x7fd0ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.energy', impact: 'impact.plasma', casing: null, muzzleLightColor: 0x8fd8ff },
    audio: conventionAudio('railgun', 'energy'),
    rumble: { strong: 1, weak: 1, ms: 220 },
    model: 'railgun',
    cost: 3500,
    boxOnly: true,
    carrySpeedMultiplier: 0.92,
    attachmentSlots: ['optic', 'muzzle', 'stock'],
    charge: {
      time: 1.1,
      minCharge: 0.35,
      damageAtMin: 0.35,
      autoReleaseAfter: 1.5,
      chargeAudio: 'weapon.railgun.charge',
      visual: 'charge.rail',
    },
    upgrades: [
      forgeTier(
        1,
        'RG-9 „Speer“',
        { damage: 1.6, magazine: 1.34, reserve: 1.5 },
        { kind: 'elementProc', element: 'shock', chance: 1, amount: 20 },
      ),
      forgeTier(
        2,
        'RG-9 „Donnerspeer“',
        { damage: 1.35, chargeTime: 0.75, reloadTime: 0.8 },
        { kind: 'chainArc', chance: 1, count: 2, range: 6, damage: 150 },
      ),
      forgeTier(
        3,
        'RG-9 „Weltenspeer“',
        { damage: 1.3, chargeTime: 0.85, penetration: 1.5 },
        { kind: 'ricochet', bounces: 3, damageKeep: 0.9 },
        { tracerColor: 0xe8f4ff },
      ),
    ],
  },

  flamethrower: {
    id: 'flamethrower',
    name: 'FW-4 „Inferno“',
    shortName: 'FW-4',
    description: 'Flammenwerfer. Ein Kegel aus Feuer, neun Meter weit – alles darin brennt.',
    category: 'energy',
    kind: 'beam',
    fireMode: 'auto',
    burst: null,
    // Per beam tick, to everything inside the cone.
    damage: {
      base: 11,
      headMultiplier: 1.2,
      limbMultiplier: 1,
      weakpointMultiplier: 1.3,
      falloffStart: 4,
      falloffEnd: 8.5,
      minFalloffMultiplier: 0.5,
      element: 'fire',
      impulse: 0.15,
      propImpulse: 8,
    },
    pellets: 1,
    // Equals the beam tick rate (12/s).
    rpm: 720,
    magazine: 150,
    reserve: 450,
    chambered: false,
    reload: {
      // magOut = tank off, magIn = tank on, boltRelease = the pilot light ignites.
      tactical: 2.4,
      empty: 2.7,
      tacticalSteps: [
        { step: 'magOut', at: 0.45 },
        { step: 'magIn', at: 1.45 },
        { step: 'boltRelease', at: 1.95 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.45 },
        { step: 'magIn', at: 1.5 },
        { step: 'boltRelease', at: 2.2 },
      ],
      perShell: null,
    },
    spread: {
      hip: 0.6,
      ads: 0.4,
      moveAdd: 0.3,
      airAdd: 0.6,
      crouchMultiplier: 1,
      perShotBloom: 0,
      bloomMax: 0,
      recoveryPerSec: 5,
      recoveryDelay: 0.15,
    },
    recoil: {
      pattern: [
        [0, 0.03],
        [0.02, 0.03],
        [-0.02, 0.03],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.05,
      randomPitch: 0.03,
      recoveryPerSec: 6,
      recoveryDelay: 0.12,
      resetTime: 0.3,
      adsMultiplier: 0.8,
      crouchMultiplier: 0.9,
      kickTime: 0.05,
      viewPunch: { pitch: 0.1, yaw: 0.15, roll: 0.2 },
      visualKick: { back: 0.004, up: 0.001, side: 0.003, pitch: 0.4, yaw: 0.6, roll: 0.6 },
      shake: 0.03,
    },
    ads: {
      zoom: 0.9,
      inTime: 0.26,
      outTime: 0.18,
      moveSpeedMultiplier: 0.75,
      sensitivityMultiplier: 1,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 9,
    equipTime: 0.65,
    holsterTime: 0.36,
    sprintToFireTime: 0.2,
    inspectTime: 3,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0xff8a30, pellets: 1 },
    vfx: { muzzle: 'muzzle.flame', impact: 'impact.fire', casing: null, muzzleLightColor: 0xff8a30 },
    audio: conventionAudio('flamethrower', 'energy'),
    rumble: { strong: 0.2, weak: 0.35, ms: 50 },
    model: 'flamethrower',
    cost: 2500,
    boxOnly: true,
    carrySpeedMultiplier: 0.92,
    attachmentSlots: ['muzzle', 'magazine'],
    beam: {
      range: 9,
      tickRate: 12,
      coneDeg: 12,
      chain: null,
      ammoPerSecond: 15,
      visual: 'beam.flame',
      loopAudio: 'weapon.flamethrower.loop',
    },
    upgrades: [
      forgeTier(
        1,
        'FW-4 „Feuersturm“',
        { damage: 1.6, magazine: 1.4, reserve: 1.5, range: 1.15 },
        { kind: 'elementProc', element: 'fire', chance: 0.5, amount: 15 },
      ),
      forgeTier(
        2,
        'FW-4 „Höllenglut“',
        { damage: 1.35, reloadTime: 0.8 },
        { kind: 'fieldOnKill', chance: 0.3, field: FIRE_POOL },
      ),
      forgeTier(
        3,
        'FW-4 „Schwarzes Feuer“',
        { damage: 1.3, element: 'void', range: 1.1 },
        { kind: 'elementProc', element: 'fire', chance: 1, amount: 20 },
        { palette: 'forgeVoid' },
      ),
    ],
  },

  grenadelauncher: {
    id: 'grenadelauncher',
    name: 'GL-6 „Donnerkeil“',
    shortName: 'GL-6',
    description: 'Trommel-Granatwerfer. Sechs springende Granaten – halte Abstand zur eigenen Explosion.',
    category: 'launcher',
    kind: 'projectile',
    fireMode: 'semi',
    burst: null,
    // Direct hit; the blast is `projectile.explosion`.
    damage: {
      base: 60,
      headMultiplier: 1.2,
      limbMultiplier: 1,
      weakpointMultiplier: 1.5,
      falloffStart: 40,
      falloffEnd: 80,
      minFalloffMultiplier: 0.9,
      element: 'physical',
      impulse: 3,
      propImpulse: 200,
    },
    pellets: 1,
    rpm: 90,
    magazine: 6,
    reserve: 24,
    chambered: false,
    reload: {
      tactical: 0,
      empty: 0,
      tacticalSteps: [],
      emptySteps: [],
      // Drum loaded grenade by grenade (shellIn); from empty the drum is wound (pump) at the end.
      perShell: {
        start: 0.45,
        shell: 0.55,
        insertAt: 0.35,
        end: 0.4,
        emptyEnd: 0.7,
        pumpAt: 0.35,
      },
    },
    spread: {
      hip: 1.2,
      ads: 0.3,
      moveAdd: 1,
      airAdd: 2,
      crouchMultiplier: 0.9,
      perShotBloom: 0.4,
      bloomMax: 1.2,
      recoveryPerSec: 4,
      recoveryDelay: 0.3,
    },
    recoil: {
      pattern: [
        [0, 3.5],
        [0.4, 3.2],
        [-0.4, 3.2],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.6,
      randomPitch: 0.4,
      recoveryPerSec: 14,
      recoveryDelay: 0.12,
      resetTime: 0.8,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.85,
      kickTime: 0.07,
      viewPunch: { pitch: 3, yaw: 0.8, roll: 1.8 },
      visualKick: { back: 0.08, up: 0.03, side: 0.006, pitch: 11, yaw: 1.5, roll: 3 },
      shake: 0.3,
    },
    ads: {
      zoom: 0.82,
      inTime: 0.26,
      outTime: 0.18,
      moveSpeedMultiplier: 0.72,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 200,
    equipTime: 0.65,
    holsterTime: 0.36,
    sprintToFireTime: 0.22,
    inspectTime: 3,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0xffb060, pellets: 1 },
    vfx: { muzzle: 'muzzle.launcher', impact: 'impact.bullet', casing: null, muzzleLightColor: 0xffa850 },
    audio: conventionAudio('grenadelauncher', 'explosive', SHELL_STEPS),
    rumble: { strong: 0.6, weak: 0.7, ms: 120 },
    model: 'grenadelauncher',
    cost: 2000,
    boxOnly: true,
    attachmentSlots: ['optic', 'magazine', 'stock'],
    projectile: {
      speed: 38,
      gravity: 9.8,
      radius: 0.07,
      lifetime: 6,
      bounces: 2,
      restitution: 0.45,
      fuse: 1.6,
      pierce: 0,
      homing: 0,
      explosion: explosion('physical', 4.5, 260, {
        minFalloff: 0.25,
        impulse: 9,
        propImpulse: 420,
        selfDamage: 0.35,
        shake: 0.6,
      }),
      field: null,
      visual: 'projectile.grenade',
      trail: 'trail.smoke',
      flightAudio: 'projectile.grenade.flight',
    },
    upgrades: [
      forgeTier(
        1,
        'GL-6 „Donnerschlag“',
        { damage: 1.6, magazine: 1.34, reserve: 1.5, blastRadius: 1.15 },
        { kind: 'fieldOnKill', chance: 0.3, field: FIRE_POOL },
      ),
      forgeTier(
        2,
        'GL-6 „Sturmfaust“',
        { damage: 1.35, projectileSpeed: 1.25, reloadTime: 0.8 },
        { kind: 'chainArc', chance: 0.5, count: 3, range: 6, damage: 80 },
      ),
      forgeTier(
        3,
        'GL-6 „Sternenregen“',
        // Three grenades per pull share the one grenade's self damage.
        { damage: 1.25, blastRadius: 1.15, selfDamage: 0.33 },
        { kind: 'splitShot', count: 2, angleDeg: 7 },
      ),
    ],
  },

  blackhole: {
    id: 'blackhole',
    name: 'SX-0 „Ereignishorizont“',
    shortName: 'SX-0',
    description: 'Singularitätswerfer. Eine langsame Kugel aus Leere, die alles in sich hineinzieht.',
    category: 'energy',
    kind: 'projectile',
    fireMode: 'semi',
    burst: null,
    // Direct orb hit; the burst, the pull field and its collapse come from `projectile`.
    damage: {
      base: 150,
      headMultiplier: 1,
      limbMultiplier: 1,
      weakpointMultiplier: 1.5,
      falloffStart: 40,
      falloffEnd: 80,
      minFalloffMultiplier: 0.9,
      element: 'void',
      impulse: 2,
      propImpulse: 100,
    },
    pellets: 1,
    rpm: 40,
    magazine: 3,
    reserve: 12,
    chambered: false,
    reload: {
      tactical: 2.6,
      empty: 3.1,
      tacticalSteps: [
        { step: 'magOut', at: 0.5 },
        { step: 'magIn', at: 1.5 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.48 },
        { step: 'magIn', at: 1.45 },
        { step: 'boltRelease', at: 2.4 },
      ],
      perShell: null,
    },
    spread: {
      hip: 0.8,
      ads: 0.2,
      moveAdd: 0.6,
      airAdd: 1.5,
      crouchMultiplier: 0.9,
      perShotBloom: 0.3,
      bloomMax: 0.9,
      recoveryPerSec: 4,
      recoveryDelay: 0.3,
    },
    recoil: {
      pattern: [[0, 2.5]],
      patternRepeatFrom: 0,
      randomYaw: 0.4,
      randomPitch: 0.3,
      recoveryPerSec: 10,
      recoveryDelay: 0.15,
      resetTime: 1.2,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.85,
      kickTime: 0.08,
      viewPunch: { pitch: 2.4, yaw: 0.6, roll: 2.2 },
      visualKick: { back: 0.06, up: 0.02, side: 0.006, pitch: 8, yaw: 1.2, roll: 4 },
      shake: 0.35,
    },
    ads: {
      zoom: 0.85,
      inTime: 0.26,
      outTime: 0.18,
      moveSpeedMultiplier: 0.72,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 100,
    equipTime: 0.7,
    holsterTime: 0.38,
    sprintToFireTime: 0.24,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0xb060ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.void', impact: 'impact.void', casing: null, muzzleLightColor: 0xb060ff },
    audio: conventionAudio('blackhole', 'energy', MAG_STEPS),
    rumble: { strong: 0.7, weak: 0.9, ms: 200 },
    model: 'blackhole',
    cost: 4000,
    boxOnly: true,
    attachmentSlots: ['optic', 'magazine'],
    projectile: {
      speed: 14,
      gravity: 0,
      radius: 0.25,
      lifetime: 3.5,
      bounces: 0,
      restitution: 0,
      // Bursts on the first body or wall it touches, else at the fuse (22 m): an orb drifting
      // through bodies formed its singularity far behind the horde, out of the pull's reach.
      fuse: 1.6,
      pierce: 0,
      homing: 0,
      explosion: explosion('void', 2.2, 90, { small: true, minFalloff: 0.5, shake: 0.25 }),
      field: field(
        'pull',
        'void',
        7,
        3.5,
        35,
        22,
        explosion('void', 5, 600, { minFalloff: 0.4, impulse: 10, propImpulse: 500, shake: 0.6 }),
      ),
      visual: 'projectile.voidorb',
      trail: 'trail.void',
      flightAudio: 'projectile.voidorb.flight',
    },
    upgrades: [
      forgeTier(
        1,
        'SX-0 „Singularität“',
        { damage: 1.5, magazine: 1.34, reserve: 1.5, blastRadius: 1.15 },
        { kind: 'elementProc', element: 'void', chance: 1, amount: 40 },
      ),
      forgeTier(
        2,
        'SX-0 „Schwarzschild“',
        { damage: 1.35, projectileSpeed: 1.3, reloadTime: 0.8 },
        { kind: 'critBurst', everyNth: 3, multiplier: 2.5 },
      ),
      forgeTier(
        3,
        'SX-0 „Urknall“',
        { damage: 1.3, blastRadius: 1.4 },
        { kind: 'fieldOnKill', chance: 0.3, field: VOID_MAW },
        { palette: 'forgeVoid' },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
