/**
 * Light machine guns and the minigun. Angles in DEGREES, times in seconds, distances in meters,
 * rates in rpm. Heavy: slow to raise, slow to aim, slower to carry (`carrySpeedMultiplier`) – and
 * the most sustained damage of the bullet weapons.
 *
 * Feel targets:
 * - LM-60 „Bollwerk“: 100-round belt at 700 rpm, 26 dmg. A heavy climb that settles into a wide,
 *   slow sway: crouched (braced) it hoses a corridor for 8 seconds. The reload is an event –
 *   cover up, box out, new box, lay the belt, slam the cover, charge.
 *   Forge: Festung (crit tracer rounds) → Zitadelle (frost build-up) → Eiswall (rounds burst into
 *   frost, the horde freezes in the corridor).
 * - RX-6 „Kreissäge“ (box only): six barrels spin up (0.75 s) to 2400 rpm; 200 rounds of 14 dmg
 *   (~560 DPS) – a Rift-Kiste jackpot that eats ammo and slows the carrier to a walk.
 *   Forge: Häcksler (crit bursts) → Fleischwolf (drains life, lighter to carry) → Weltenfräse
 *   (electrified rounds that arc between enemies).
 */
import type { WeaponDef } from '../weapons';
import { MELEE_HEAVY, conventionAudio, explosion, forgeTier } from './common';

export const LMGS = {
  lmg: {
    id: 'lmg',
    name: 'LM-60 „Bollwerk“',
    shortName: 'LM-60',
    description: 'Leichtes Maschinengewehr mit 100-Schuss-Gurt. Halte den Korridor – und halte dagegen.',
    category: 'lmg',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 26,
      headMultiplier: 1.7,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2.1,
      falloffStart: 30,
      falloffEnd: 70,
      minFalloffMultiplier: 0.65,
      element: 'physical',
      impulse: 1.2,
      propImpulse: 40,
    },
    pellets: 1,
    rpm: 700,
    magazine: 100,
    reserve: 400,
    // Open bolt: nothing stays chambered.
    chambered: false,
    reload: {
      // magOut = cover open + box out, magIn = box in + belt laid, boltRelease = cover shut + charge.
      tactical: 4.2,
      empty: 4.8,
      tacticalSteps: [
        { step: 'magOut', at: 0.75 },
        { step: 'magIn', at: 2.2 },
        { step: 'boltRelease', at: 3.3 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.72 },
        { step: 'magIn', at: 2.2 },
        { step: 'boltRelease', at: 3.8 },
      ],
      perShell: null,
    },
    spread: {
      hip: 2.6,
      ads: 0.35,
      moveAdd: 1.6,
      airAdd: 3.5,
      crouchMultiplier: 0.65,
      perShotBloom: 0.1,
      bloomMax: 2.6,
      recoveryPerSec: 6,
      recoveryDelay: 0.14,
    },
    recoil: {
      // 1–4 heavy climb, 5–9 drift right, 10–14 swing left, then a wide slow sway.
      pattern: [
        [0, 0.55],
        [0.05, 0.6],
        [-0.05, 0.62],
        [0.08, 0.6],
        [0.1, 0.55],
        [0.14, 0.5],
        [0.16, 0.45],
        [0.12, 0.42],
        [0.06, 0.4],
        [0, 0.38],
        [-0.08, 0.36],
        [-0.14, 0.34],
        [-0.16, 0.32],
        [-0.1, 0.3],
        [0, 0.3],
        [0.1, 0.3],
        [0.16, 0.3],
        [0.1, 0.3],
        [0, 0.3],
        [-0.1, 0.3],
        [-0.16, 0.3],
        [-0.1, 0.3],
      ],
      patternRepeatFrom: 14,
      randomYaw: 0.12,
      randomPitch: 0.07,
      recoveryPerSec: 7,
      recoveryDelay: 0.12,
      resetTime: 0.3,
      adsMultiplier: 0.55,
      // Braced (crouched) it barely moves.
      crouchMultiplier: 0.7,
      kickTime: 0.045,
      viewPunch: { pitch: 0.7, yaw: 0.35, roll: 0.7 },
      visualKick: { back: 0.03, up: 0.006, side: 0.004, pitch: 3, yaw: 1, roll: 1.8 },
      shake: 0.13,
    },
    ads: {
      zoom: 0.76,
      inTime: 0.32,
      outTime: 0.22,
      moveSpeedMultiplier: 0.55,
      sensitivityMultiplier: 0.88,
    },
    penetration: { power: 2, damageKeep: 0.7 },
    range: 240,
    equipTime: 0.8,
    holsterTime: 0.45,
    sprintToFireTime: 0.3,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 3, color: 0xff9a40, pellets: 1 },
    vfx: { muzzle: 'muzzle.lmg', impact: 'impact.bullet', casing: 'casing.rifle', muzzleLightColor: 0xffa048 },
    audio: conventionAudio('lmg', 'large'),
    rumble: { strong: 0.3, weak: 0.55, ms: 60 },
    model: 'lmg',
    cost: 1500,
    carrySpeedMultiplier: 0.9,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'LM-60 „Festung“',
        { damage: 1.7, magazine: 1.5, reserve: 1.5 },
        { kind: 'critBurst', everyNth: 5, multiplier: 2 },
      ),
      forgeTier(
        2,
        'LM-60 „Zitadelle“',
        { damage: 1.35, rpm: 1.1, reloadTime: 0.7 },
        { kind: 'elementProc', element: 'ice', chance: 0.15, amount: 12 },
      ),
      forgeTier(
        3,
        'LM-60 „Eiswall“',
        { damage: 1.3, magazine: 1.34, recoil: 0.8, element: 'ice' },
        {
          kind: 'explosiveRounds',
          chance: 0.12,
          explosion: explosion('ice', 2, 60, { small: true }),
        },
        { tracerColor: 0x9ae8ff, palette: 'forgeFrost' },
      ),
    ],
  },

  minigun: {
    id: 'minigun',
    name: 'RX-6 „Kreissäge“',
    shortName: 'RX-6',
    description: 'Sechsläufige Rotationskanone. Kurz anlaufen lassen – dann zersägt sie alles.',
    category: 'lmg',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 14,
      headMultiplier: 1.6,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2,
      falloffStart: 25,
      falloffEnd: 60,
      minFalloffMultiplier: 0.6,
      element: 'physical',
      impulse: 0.8,
      propImpulse: 26,
    },
    pellets: 1,
    // Full rate after the spin-up (`spinUp`).
    rpm: 2400,
    magazine: 200,
    reserve: 600,
    chambered: false,
    reload: {
      tactical: 3.6,
      empty: 4.1,
      tacticalSteps: [
        { step: 'magOut', at: 0.6 },
        { step: 'magIn', at: 1.9 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.58 },
        { step: 'magIn', at: 1.85 },
        { step: 'boltRelease', at: 2.9 },
      ],
      perShell: null,
    },
    spread: {
      hip: 3,
      ads: 1.6,
      moveAdd: 1.2,
      airAdd: 3,
      crouchMultiplier: 0.8,
      perShotBloom: 0.05,
      bloomMax: 2,
      recoveryPerSec: 6,
      recoveryDelay: 0.1,
    },
    recoil: {
      // A constant shudder rather than a climb: small kicks weaving around the aim point.
      pattern: [
        [0, 0.16],
        [0.06, 0.16],
        [-0.06, 0.16],
        [0.08, 0.14],
        [-0.08, 0.14],
        [0.05, 0.13],
        [-0.05, 0.13],
      ],
      patternRepeatFrom: 3,
      randomYaw: 0.12,
      randomPitch: 0.06,
      recoveryPerSec: 10,
      recoveryDelay: 0.08,
      resetTime: 0.2,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.8,
      kickTime: 0.03,
      viewPunch: { pitch: 0.25, yaw: 0.2, roll: 0.3 },
      visualKick: { back: 0.01, up: 0.002, side: 0.004, pitch: 1, yaw: 0.8, roll: 0.6 },
      shake: 0.05,
    },
    ads: {
      // A braced hip stance rather than sights.
      zoom: 0.9,
      inTime: 0.4,
      outTime: 0.25,
      moveSpeedMultiplier: 0.5,
      sensitivityMultiplier: 0.9,
    },
    penetration: { power: 1.5, damageKeep: 0.65 },
    range: 150,
    equipTime: 1,
    holsterTime: 0.5,
    sprintToFireTime: 0.35,
    inspectTime: 3,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 4, color: 0xffa040, pellets: 1 },
    vfx: { muzzle: 'muzzle.lmg', impact: 'impact.bullet', casing: 'casing.rifle', muzzleLightColor: 0xffa048 },
    audio: conventionAudio('minigun', 'large'),
    rumble: { strong: 0.3, weak: 0.6, ms: 40 },
    model: 'minigun',
    cost: 3500,
    boxOnly: true,
    carrySpeedMultiplier: 0.78,
    spinUp: { time: 0.75, startFraction: 0.35, spinDown: 1.2, loopAudio: 'weapon.minigun.spin' },
    attachmentSlots: ['magazine', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'RX-6 „Häcksler“',
        { damage: 1.6, magazine: 1.5, reserve: 1.5 },
        { kind: 'critBurst', everyNth: 12, multiplier: 3 },
      ),
      forgeTier(
        2,
        'RX-6 „Fleischwolf“',
        { damage: 1.35, moveSpeed: 1.12, reloadTime: 0.8 },
        { kind: 'lifesteal', fraction: 0.005 },
      ),
      forgeTier(
        3,
        'RX-6 „Weltenfräse“',
        { damage: 1.3, element: 'shock', reserve: 1.25 },
        { kind: 'chainArc', chance: 0.15, count: 2, range: 5, damage: 30 },
        { tracerColor: 0x9fd8ff },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
