/**
 * Pistols (sidearms). Angles in DEGREES, times in seconds, distances in meters, rates in rpm.
 *
 * Feel targets:
 * - VX-9 „Sentinel“ (M2, tuning unchanged): precise, fast semi-auto sidearm, 45 dmg, a sharp single
 *   kick per shot. The start weapon: two body shots or one headshot drop an early Schwärmer.
 *   Forge: Nachtwache (every 4th round a crit) → Seraph (ricochets) → Erzengel (every round
 *   detonates in a burst of fire – the akimbo-launcher fantasy in one hand).
 * - RM-44 „Richter“: a hand cannon. 105 dmg, 6 rounds, a big muzzle flip that settles before the
 *   next pull (~150 rpm): every shot is a decision, headshots one-tap through wave 10. Reload
 *   swings the crane out, a speedloader drops six fresh rounds, the crane snaps shut.
 *   Forge: Urteil (the sixth chamber pronounces the verdict: ×2.5) → Jüngstes Gericht (hits call
 *   down arcs) → Hammer der Leere (every round implodes into a void blast).
 * - MP-3 „Hornisse“: a buzzing machine pistol, 1100 rpm, 20 rounds gone in a second. Close-range
 *   panic button with a jittery zigzag the player tames with short bursts.
 *   Forge: Wespennest (poison stings) → Stachelkönigin (every 10th round ×3) → Schwarmtod (each
 *   round splits into three).
 */
import type { WeaponDef } from '../weapons';
import { MELEE_BASH, MELEE_QUICK, conventionAudio, explosion, forgeTier } from './common';

export const PISTOLS = {
  pistol: {
    id: 'pistol',
    name: 'VX-9 „Sentinel“',
    shortName: 'VX-9',
    description: 'Präzise Halbautomatik. Schnell gezogen, tödlich auf den Kopf.',
    category: 'pistol',
    kind: 'hitscan',
    fireMode: 'semi',
    burst: null,
    damage: {
      base: 45,
      headMultiplier: 2,
      limbMultiplier: 0.75,
      weakpointMultiplier: 2.5,
      falloffStart: 18,
      falloffEnd: 45,
      minFalloffMultiplier: 0.6,
      element: 'physical',
      impulse: 1.6,
      propImpulse: 45,
    },
    pellets: 1,
    // Semi-auto rate cap: a fast trigger finger, not a spam button.
    rpm: 420,
    magazine: 12,
    reserve: 84,
    chambered: true,
    reload: {
      tactical: 1.3,
      empty: 1.6,
      tacticalSteps: [
        { step: 'magOut', at: 0.28 },
        { step: 'magIn', at: 0.82 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.26 },
        { step: 'magIn', at: 0.8 },
        { step: 'boltRelease', at: 1.22 },
      ],
      perShell: null,
    },
    spread: {
      hip: 0.9,
      ads: 0.12,
      moveAdd: 0.9,
      airAdd: 2.4,
      crouchMultiplier: 0.8,
      // Paced shots stay pin-point; spamming at the rate cap blooms to the max in ~6 shots.
      perShotBloom: 0.5,
      bloomMax: 2,
      recoveryPerSec: 8,
      recoveryDelay: 0.12,
    },
    recoil: {
      pattern: [
        [0, 1.55],
        [0.12, 1.5],
        [-0.12, 1.5],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.35,
      randomPitch: 0.25,
      recoveryPerSec: 10,
      recoveryDelay: 0.07,
      resetTime: 0.35,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.85,
      kickTime: 0.05,
      viewPunch: { pitch: 1.8, yaw: 0.5, roll: 1.2 },
      visualKick: { back: 0.045, up: 0.012, side: 0.004, pitch: 9, yaw: 1.5, roll: 3 },
      shake: 0.2,
    },
    ads: {
      zoom: 0.86,
      inTime: 0.15,
      outTime: 0.12,
      moveSpeedMultiplier: 0.82,
      sensitivityMultiplier: 0.95,
    },
    // Through glass and grates, not through bodies.
    penetration: { power: 0.5, damageKeep: 0.6 },
    range: 140,
    equipTime: 0.32,
    holsterTime: 0.22,
    sprintToFireTime: 0.1,
    inspectTime: 2.2,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0x9fe8ff, pellets: 1 },
    vfx: {
      muzzle: 'muzzle.pistol',
      impact: 'impact.bullet',
      casing: 'casing.pistol',
      muzzleLightColor: 0xffc27a,
    },
    audio: {
      fire: ['weapon.pistol.fire', 'weapon.pistol.mech', 'weapon.tail.small'],
      dry: 'weapon.dry',
      equip: 'weapon.pistol.equip',
      holster: 'weapon.holster',
      reloadStart: 'weapon.reload.start',
      steps: {
        magOut: 'weapon.pistol.magOut',
        magIn: 'weapon.pistol.magIn',
        boltRelease: 'weapon.pistol.slide',
      },
      melee: 'weapon.melee',
      inspect: 'weapon.inspect',
    },
    rumble: { strong: 0.25, weak: 0.55, ms: 70 },
    model: 'pistol',
    cost: 500,
    attachmentSlots: ['optic', 'muzzle', 'magazine', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'VX-9 „Nachtwache“',
        { damage: 1.8, magazine: 1.5, reserve: 1.6, reloadTime: 0.9 },
        { kind: 'critBurst', everyNth: 4, multiplier: 2 },
      ),
      forgeTier(
        2,
        'VX-9 „Seraph“',
        { damage: 1.35, rpm: 1.15, penetration: 2, adsTime: 0.9 },
        { kind: 'ricochet', bounces: 1, damageKeep: 0.7 },
      ),
      forgeTier(
        3,
        'VX-9 „Erzengel“',
        { damage: 1.3, magazine: 1.34, reserve: 1.25 },
        {
          kind: 'explosiveRounds',
          chance: 1,
          explosion: explosion('fire', 2, 85, { small: true, impulse: 4 }),
        },
        { tracerColor: 0xffb070 },
      ),
    ],
  },

  revolver: {
    id: 'revolver',
    name: 'RM-44 „Richter“',
    shortName: 'RM-44',
    description: 'Schwerer Revolver. Sechs Kammern, sechs Urteile – jeder Schuss reißt die Mündung hoch.',
    category: 'pistol',
    kind: 'hitscan',
    fireMode: 'semi',
    burst: null,
    damage: {
      base: 105,
      headMultiplier: 2.2,
      limbMultiplier: 0.75,
      weakpointMultiplier: 2.5,
      falloffStart: 22,
      falloffEnd: 55,
      minFalloffMultiplier: 0.6,
      element: 'physical',
      impulse: 3.2,
      propImpulse: 95,
    },
    pellets: 1,
    // Double-action pull: the flip must settle before the next shot is accurate.
    rpm: 150,
    magazine: 6,
    reserve: 42,
    // A cylinder: nothing is chambered beyond its six chambers.
    chambered: false,
    reload: {
      // magOut = crane out + ejector, magIn = speedloader, boltRelease = crane snaps shut.
      tactical: 2.1,
      empty: 2.25,
      tacticalSteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.25 },
        { step: 'boltRelease', at: 1.7 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.38 },
        { step: 'magIn', at: 1.3 },
        { step: 'boltRelease', at: 1.8 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.1,
      ads: 0.1,
      moveAdd: 1,
      airAdd: 2.8,
      crouchMultiplier: 0.8,
      perShotBloom: 0.8,
      bloomMax: 2.4,
      recoveryPerSec: 7,
      recoveryDelay: 0.15,
    },
    recoil: {
      // A big, mostly vertical flip per shot with an alternating lean – the cylinder's rhythm.
      pattern: [
        [0, 3.2],
        [0.35, 3],
        [-0.3, 3.1],
        [0.25, 3],
        [-0.35, 3.05],
        [0.3, 2.95],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.45,
      randomPitch: 0.35,
      recoveryPerSec: 14,
      recoveryDelay: 0.1,
      resetTime: 0.6,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.85,
      kickTime: 0.06,
      viewPunch: { pitch: 3.4, yaw: 0.8, roll: 2.2 },
      visualKick: { back: 0.07, up: 0.03, side: 0.006, pitch: 18, yaw: 2, roll: 4 },
      shake: 0.32,
    },
    ads: {
      zoom: 0.84,
      inTime: 0.18,
      outTime: 0.13,
      moveSpeedMultiplier: 0.8,
      sensitivityMultiplier: 0.95,
    },
    // Through one body (flesh) or a grate.
    penetration: { power: 1.2, damageKeep: 0.7 },
    range: 160,
    equipTime: 0.4,
    holsterTime: 0.26,
    sprintToFireTime: 0.12,
    inspectTime: 2.6,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0xffc890, pellets: 1 },
    // Casings leave on the reload (the ejector), not per shot.
    vfx: { muzzle: 'muzzle.pistol', impact: 'impact.bullet', casing: null, muzzleLightColor: 0xffb468 },
    audio: conventionAudio('revolver', 'medium'),
    rumble: { strong: 0.55, weak: 0.7, ms: 110 },
    model: 'revolver',
    cost: 900,
    attachmentSlots: ['optic', 'muzzle', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'RM-44 „Urteil“',
        { damage: 1.7, reserve: 1.6, reloadTime: 0.85 },
        { kind: 'critBurst', everyNth: 6, multiplier: 2.5 },
      ),
      forgeTier(
        2,
        'RM-44 „Jüngstes Gericht“',
        { damage: 1.35, magazine: 1.34, penetration: 1.8 },
        { kind: 'chainArc', chance: 0.35, count: 2, range: 6, damage: 90 },
      ),
      forgeTier(
        3,
        'RM-44 „Hammer der Leere“',
        { damage: 1.3, rpm: 1.25, recoil: 0.85 },
        {
          kind: 'explosiveRounds',
          chance: 1,
          explosion: explosion('void', 2.4, 140, { small: true, impulse: 1.5, shake: 0.18 }),
        },
        { tracerColor: 0xe060ff, palette: 'forgeVoid' },
      ),
    ],
  },

  machinepistol: {
    id: 'machinepistol',
    name: 'MP-3 „Hornisse“',
    shortName: 'MP-3',
    description: 'Vollautomatische Maschinenpistole. 1100 Schuss pro Minute – ein Schwarm in der Hand.',
    category: 'pistol',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 17,
      headMultiplier: 1.7,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2,
      falloffStart: 10,
      falloffEnd: 28,
      minFalloffMultiplier: 0.5,
      element: 'physical',
      impulse: 0.7,
      propImpulse: 22,
    },
    pellets: 1,
    rpm: 1100,
    magazine: 20,
    reserve: 180,
    chambered: true,
    reload: {
      tactical: 1.45,
      empty: 1.8,
      tacticalSteps: [
        { step: 'magOut', at: 0.3 },
        { step: 'magIn', at: 0.9 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.28 },
        { step: 'magIn', at: 0.86 },
        { step: 'boltRelease', at: 1.4 },
      ],
      perShell: null,
    },
    spread: {
      hip: 2.2,
      ads: 0.55,
      moveAdd: 0.7,
      airAdd: 1.8,
      crouchMultiplier: 0.8,
      perShotBloom: 0.12,
      bloomMax: 2.4,
      recoveryPerSec: 9,
      recoveryDelay: 0.1,
    },
    recoil: {
      // Buzzing zigzag around a shallow climb; the tail keeps weaving left-right.
      pattern: [
        [0, 0.42],
        [0.12, 0.4],
        [-0.1, 0.42],
        [0.14, 0.4],
        [-0.12, 0.4],
        [0.16, 0.38],
        [-0.1, 0.38],
        [0.18, 0.36],
        [0.2, 0.34],
        [0.1, 0.32],
        [-0.14, 0.32],
        [-0.2, 0.3],
        [-0.1, 0.3],
        [0.12, 0.3],
      ],
      patternRepeatFrom: 8,
      randomYaw: 0.16,
      randomPitch: 0.08,
      recoveryPerSec: 9,
      recoveryDelay: 0.1,
      resetTime: 0.24,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.85,
      kickTime: 0.035,
      viewPunch: { pitch: 0.45, yaw: 0.3, roll: 0.5 },
      visualKick: { back: 0.018, up: 0.004, side: 0.004, pitch: 2.5, yaw: 1.2, roll: 1.4 },
      shake: 0.09,
    },
    ads: {
      zoom: 0.88,
      inTime: 0.13,
      outTime: 0.1,
      moveSpeedMultiplier: 0.86,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0.5, damageKeep: 0.55 },
    range: 90,
    equipTime: 0.3,
    holsterTime: 0.2,
    sprintToFireTime: 0.08,
    inspectTime: 2.2,
    melee: MELEE_QUICK,
    tracer: { everyNth: 3, color: 0xffcf70, pellets: 1 },
    vfx: { muzzle: 'muzzle.smg', impact: 'impact.bullet', casing: 'casing.pistol', muzzleLightColor: 0xffc070 },
    audio: conventionAudio('machinepistol', 'small'),
    rumble: { strong: 0.12, weak: 0.35, ms: 40 },
    model: 'machinepistol',
    cost: 750,
    attachmentSlots: ['optic', 'muzzle', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'MP-3 „Wespennest“',
        { damage: 1.7, magazine: 1.5, reserve: 1.6 },
        { kind: 'elementProc', element: 'poison', chance: 0.25, amount: 12 },
      ),
      forgeTier(
        2,
        'MP-3 „Stachelkönigin“',
        { damage: 1.35, rpm: 1.1, reloadTime: 0.85 },
        { kind: 'critBurst', everyNth: 10, multiplier: 3 },
      ),
      forgeTier(
        3,
        'MP-3 „Schwarmtod“',
        { damage: 1.25, magazine: 1.34, reserve: 1.25 },
        { kind: 'splitShot', count: 2, angleDeg: 2.5 },
        { tracerColor: 0xd8ff60 },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
