/**
 * Assault / battle rifles. Angles in DEGREES, times in seconds, distances in meters, rates in rpm.
 *
 * Feel targets:
 * - KR-7 „Wächter“ (M2, tuning unchanged): 650 rpm full auto, 28 dmg, learnable pattern (straight
 *   up, then drift right, then back left) that a player can pull down against.
 *   Forge: Hüter (rounds ricochet once) → Bastion (crit rhythm) → Ewige Wacht (explosive rounds).
 * - BR-3 „Triade“: three-round bursts (900 rpm inside the burst, a beat between bursts): every
 *   burst climbs up, nudges right, settles – precise at range, 34 dmg ×3 per trigger pull.
 *   Forge: Dreifaltigkeit (the third round of a burst crits) → Dreigestirn (void build-up) →
 *   Dreizack des Abgrunds (every round fans into a trident of void rays).
 * - SR-17 „Hammerschlag“: semi-auto battle rifle, 62 dmg, 20 rounds, full-power cartridge that
 *   punches through two Schwärmer and a grate. A heavy kick per shot with an alternating lean;
 *   paced fire is laser-accurate, spamming blooms.
 *   Forge: Schmiedehammer (occasional blast) → Donnerhall (chain arcs) → Götterhammer (every hit
 *   detonates in a thunderclap).
 */
import type { WeaponDef } from '../weapons';
import { MELEE_BASH, conventionAudio, explosion, forgeTier } from './common';

export const RIFLES = {
  rifle: {
    id: 'rifle',
    name: 'KR-7 „Wächter“',
    shortName: 'KR-7',
    description: 'Vollautomatisches Sturmgewehr. Zieht erst hoch, dann nach rechts – halte dagegen.',
    category: 'rifle',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 28,
      headMultiplier: 1.8,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2.2,
      falloffStart: 26,
      falloffEnd: 60,
      minFalloffMultiplier: 0.65,
      element: 'physical',
      impulse: 1.1,
      propImpulse: 35,
    },
    pellets: 1,
    rpm: 650,
    magazine: 32,
    reserve: 224,
    chambered: true,
    reload: {
      tactical: 1.85,
      empty: 2.35,
      tacticalSteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.22 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.18 },
        { step: 'boltRelease', at: 1.86 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.7,
      ads: 0.2,
      moveAdd: 1.4,
      airAdd: 3,
      crouchMultiplier: 0.75,
      // Bursts of 3–5 stay tight; a full spray blooms to the cap after ~11 shots.
      perShotBloom: 0.18,
      bloomMax: 2,
      recoveryPerSec: 7,
      recoveryDelay: 0.14,
    },
    recoil: {
      // Shots 1–7 climb, 8–14 drift right, 15–22 swing back left; the tail loops a gentle weave.
      pattern: [
        [0, 0.62],
        [0.02, 0.66],
        [-0.03, 0.68],
        [0.03, 0.7],
        [0, 0.7],
        [0.05, 0.66],
        [0.08, 0.62],
        [0.16, 0.55],
        [0.22, 0.5],
        [0.26, 0.46],
        [0.28, 0.42],
        [0.26, 0.4],
        [0.2, 0.38],
        [0.12, 0.36],
        [0, 0.35],
        [-0.12, 0.34],
        [-0.22, 0.33],
        [-0.28, 0.32],
        [-0.3, 0.32],
        [-0.26, 0.31],
        [-0.18, 0.3],
        [-0.08, 0.3],
        [0.1, 0.3],
        [0.2, 0.3],
        [0.1, 0.3],
        [-0.1, 0.3],
        [-0.2, 0.3],
        [-0.1, 0.3],
      ],
      patternRepeatFrom: 22,
      randomYaw: 0.1,
      randomPitch: 0.07,
      recoveryPerSec: 8,
      recoveryDelay: 0.12,
      resetTime: 0.28,
      adsMultiplier: 0.62,
      crouchMultiplier: 0.85,
      kickTime: 0.045,
      viewPunch: { pitch: 0.75, yaw: 0.3, roll: 0.6 },
      visualKick: { back: 0.028, up: 0.006, side: 0.003, pitch: 3.5, yaw: 0.8, roll: 1.6 },
      // Above the per-interval trauma decay: a hip spray builds up a rumble, ADS stays steady.
      shake: 0.14,
    },
    ads: {
      zoom: 0.74,
      inTime: 0.22,
      outTime: 0.16,
      moveSpeedMultiplier: 0.7,
      sensitivityMultiplier: 0.9,
    },
    penetration: { power: 2, damageKeep: 0.7 },
    range: 220,
    equipTime: 0.5,
    holsterTime: 0.3,
    sprintToFireTime: 0.18,
    inspectTime: 2.8,
    melee: MELEE_BASH,
    tracer: { everyNth: 3, color: 0xffb35a, pellets: 1 },
    vfx: {
      muzzle: 'muzzle.rifle',
      impact: 'impact.bullet',
      casing: 'casing.rifle',
      muzzleLightColor: 0xffb060,
    },
    audio: {
      fire: ['weapon.rifle.fire', 'weapon.rifle.mech', 'weapon.tail.medium'],
      dry: 'weapon.dry',
      equip: 'weapon.rifle.equip',
      holster: 'weapon.holster',
      reloadStart: 'weapon.reload.start',
      steps: {
        magOut: 'weapon.rifle.magOut',
        magIn: 'weapon.rifle.magIn',
        boltRelease: 'weapon.rifle.bolt',
      },
      melee: 'weapon.melee',
      inspect: 'weapon.inspect',
    },
    rumble: { strong: 0.2, weak: 0.45, ms: 55 },
    model: 'rifle',
    cost: 1200,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'KR-7 „Hüter“',
        { damage: 1.75, magazine: 1.25, reserve: 1.6 },
        { kind: 'ricochet', bounces: 1, damageKeep: 0.65 },
      ),
      forgeTier(
        2,
        'KR-7 „Bastion“',
        { damage: 1.35, rpm: 1.1, reloadTime: 0.85, recoil: 0.9 },
        { kind: 'critBurst', everyNth: 5, multiplier: 2 },
      ),
      forgeTier(
        3,
        'KR-7 „Ewige Wacht“',
        { damage: 1.3, magazine: 1.2, penetration: 1.5 },
        {
          kind: 'explosiveRounds',
          chance: 0.3,
          explosion: explosion('physical', 1.8, 70, { small: true }),
        },
        { tracerColor: 0xffd27a },
      ),
    ],
  },

  burstrifle: {
    id: 'burstrifle',
    name: 'BR-3 „Triade“',
    shortName: 'BR-3',
    description: 'Feuerstoßgewehr. Drei Schuss pro Abzug, präzise auf Distanz – jeder Stoß ein Urteil.',
    category: 'rifle',
    kind: 'hitscan',
    fireMode: 'burst',
    // 900 rpm inside a burst; `rpm` is the beat from a burst's last round to the next burst.
    burst: { count: 3, rpm: 900 },
    damage: {
      base: 34,
      headMultiplier: 2,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2.3,
      falloffStart: 30,
      falloffEnd: 70,
      minFalloffMultiplier: 0.65,
      element: 'physical',
      impulse: 1.2,
      propImpulse: 38,
    },
    pellets: 1,
    rpm: 360,
    magazine: 30,
    reserve: 240,
    chambered: true,
    reload: {
      tactical: 1.9,
      empty: 2.4,
      tacticalSteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.2 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.38 },
        { step: 'magIn', at: 1.16 },
        { step: 'boltRelease', at: 1.9 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.6,
      ads: 0.12,
      moveAdd: 1.3,
      airAdd: 3,
      crouchMultiplier: 0.75,
      perShotBloom: 0.25,
      bloomMax: 1.6,
      recoveryPerSec: 9,
      recoveryDelay: 0.2,
    },
    recoil: {
      // Per burst: up, nudge right, settle left; back-to-back bursts keep climbing a little.
      pattern: [
        [0, 0.55],
        [0.1, 0.6],
        [-0.06, 0.62],
        [0.04, 0.5],
        [0.14, 0.52],
        [-0.04, 0.55],
        [0.06, 0.45],
        [0.16, 0.46],
        [-0.02, 0.48],
      ],
      patternRepeatFrom: 6,
      randomYaw: 0.08,
      randomPitch: 0.05,
      recoveryPerSec: 11,
      recoveryDelay: 0.12,
      resetTime: 0.2,
      adsMultiplier: 0.6,
      crouchMultiplier: 0.85,
      kickTime: 0.04,
      viewPunch: { pitch: 0.8, yaw: 0.3, roll: 0.6 },
      visualKick: { back: 0.03, up: 0.006, side: 0.003, pitch: 3.8, yaw: 0.8, roll: 1.6 },
      shake: 0.12,
    },
    ads: {
      zoom: 0.72,
      inTime: 0.22,
      outTime: 0.16,
      moveSpeedMultiplier: 0.7,
      sensitivityMultiplier: 0.9,
    },
    penetration: { power: 2, damageKeep: 0.7 },
    range: 240,
    equipTime: 0.5,
    holsterTime: 0.3,
    sprintToFireTime: 0.18,
    inspectTime: 2.8,
    melee: MELEE_BASH,
    // Every third round (the first of each burst) traces.
    tracer: { everyNth: 3, color: 0xffb35a, pellets: 1 },
    vfx: { muzzle: 'muzzle.rifle', impact: 'impact.bullet', casing: 'casing.rifle', muzzleLightColor: 0xffb060 },
    audio: conventionAudio('burstrifle', 'medium'),
    rumble: { strong: 0.22, weak: 0.5, ms: 60 },
    model: 'burstrifle',
    cost: 1300,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'BR-3 „Dreifaltigkeit“',
        { damage: 1.75, magazine: 1.2, reserve: 1.6 },
        { kind: 'critBurst', everyNth: 3, multiplier: 1.8 },
      ),
      forgeTier(
        2,
        'BR-3 „Dreigestirn“',
        { damage: 1.35, rpm: 1.15, reloadTime: 0.85 },
        { kind: 'elementProc', element: 'void', chance: 0.25, amount: 15 },
      ),
      forgeTier(
        3,
        'BR-3 „Dreizack des Abgrunds“',
        { damage: 1.3, magazine: 1.25, element: 'void' },
        { kind: 'splitShot', count: 2, angleDeg: 1.5 },
        { tracerColor: 0xc070ff },
      ),
    ],
  },

  battlerifle: {
    id: 'battlerifle',
    name: 'SR-17 „Hammerschlag“',
    shortName: 'SR-17',
    description: 'Halbautomatisches Kampfgewehr. Volles Kaliber, schlägt durch zwei Körper und ein Gitter.',
    category: 'rifle',
    kind: 'hitscan',
    fireMode: 'semi',
    burst: null,
    damage: {
      base: 62,
      headMultiplier: 2,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2.4,
      falloffStart: 40,
      falloffEnd: 90,
      minFalloffMultiplier: 0.7,
      element: 'physical',
      impulse: 2.2,
      propImpulse: 70,
    },
    pellets: 1,
    rpm: 400,
    magazine: 20,
    reserve: 140,
    chambered: true,
    reload: {
      tactical: 2.1,
      empty: 2.6,
      tacticalSteps: [
        { step: 'magOut', at: 0.44 },
        { step: 'magIn', at: 1.3 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.26 },
        { step: 'boltRelease', at: 2.02 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.8,
      ads: 0.08,
      moveAdd: 1.5,
      airAdd: 3.2,
      crouchMultiplier: 0.75,
      // Paced shots stay pin-point, spamming at the cap blooms fast.
      perShotBloom: 0.6,
      bloomMax: 2.2,
      recoveryPerSec: 7,
      recoveryDelay: 0.14,
    },
    recoil: {
      // One hard kick per shot, leaning right, left, right …
      pattern: [
        [0, 1.6],
        [0.25, 1.5],
        [-0.2, 1.55],
        [0.3, 1.45],
        [-0.25, 1.5],
      ],
      patternRepeatFrom: 1,
      randomYaw: 0.2,
      randomPitch: 0.15,
      recoveryPerSec: 12,
      recoveryDelay: 0.08,
      resetTime: 0.4,
      adsMultiplier: 0.65,
      crouchMultiplier: 0.85,
      kickTime: 0.05,
      viewPunch: { pitch: 1.8, yaw: 0.5, roll: 1.1 },
      visualKick: { back: 0.05, up: 0.012, side: 0.004, pitch: 7, yaw: 1.2, roll: 2.4 },
      shake: 0.2,
    },
    ads: {
      zoom: 0.7,
      inTime: 0.24,
      outTime: 0.17,
      moveSpeedMultiplier: 0.68,
      sensitivityMultiplier: 0.88,
    },
    // Two bodies (flesh 1 each) and a grate, or through a crate.
    penetration: { power: 2.6, damageKeep: 0.8 },
    range: 280,
    equipTime: 0.55,
    holsterTime: 0.32,
    sprintToFireTime: 0.2,
    inspectTime: 2.9,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0xffa048, pellets: 1 },
    vfx: { muzzle: 'muzzle.rifle', impact: 'impact.bullet', casing: 'casing.rifle', muzzleLightColor: 0xffa850 },
    audio: conventionAudio('battlerifle', 'large'),
    rumble: { strong: 0.35, weak: 0.6, ms: 80 },
    model: 'battlerifle',
    cost: 1500,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'SR-17 „Schmiedehammer“',
        { damage: 1.7, reserve: 1.6, reloadTime: 0.9 },
        {
          kind: 'explosiveRounds',
          chance: 0.15,
          explosion: explosion('physical', 1.5, 60, { small: true }),
        },
      ),
      forgeTier(
        2,
        'SR-17 „Donnerhall“',
        { damage: 1.35, rpm: 1.2, magazine: 1.25 },
        { kind: 'chainArc', chance: 0.3, count: 2, range: 6, damage: 70 },
      ),
      forgeTier(
        3,
        'SR-17 „Götterhammer“',
        { damage: 1.3, penetration: 1.5, recoil: 0.85 },
        {
          kind: 'explosiveRounds',
          chance: 1,
          explosion: explosion('shock', 2.6, 120, { small: true, shake: 0.2 }),
        },
        { tracerColor: 0x9fd8ff },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
