/**
 * Shotguns. Angles in DEGREES, times in seconds, distances in meters, rates in rpm. Damage is per
 * pellet (aggregated to one damage event per target and zone).
 *
 * Feel targets:
 * - SG-12 „Brecher“ (M2, tuning unchanged): 9 × 14 dmg pump shotgun (~70 rpm) that deletes things
 *   up close.
 *   Forge: Drachenatem (burning pellets) → Höllenschlund (pellets ricochet) → Weltenbrecher
 *   (dragon's-breath fire pellets; kills leave burning pools).
 * - AS-20 „Mahlstrom“: drum-fed automatic, 300 rpm, 8 × 11 dmg (~440 DPS inside 6 m). Every shot
 *   thumps the view up with a left/right shove – short controlled strings, not a hose.
 *   Forge: Strudel (frost build-up) → Brandungswelle (every 4th shot ×2) → Schlund der Welten
 *   (kills tear open whirlpools of void that drag the horde in and collapse).
 * - DB-2 „Zwilling“: break-action double barrel. 12 × 15 dmg per barrel, both barrels in a quarter
 *   second: the most damage the player can put out in one breath, then a long reload (break open,
 *   shells fly, two fresh ones, snap shut).
 *   Forge: Kain und Abel (the second barrel hits harder) → Blutsbrüder (drains life) →
 *   Zwillingssonnen (incendiary pellets that burst).
 */
import type { WeaponDef } from '../weapons';
import { FIRE_POOL, MELEE_BASH, VOID_MAW, conventionAudio, explosion, forgeTier } from './common';

export const SHOTGUNS = {
  shotgun: {
    id: 'shotgun',
    name: 'SG-12 „Brecher“',
    shortName: 'SG-12',
    description: 'Pump-Schrotflinte. Neun Kugeln, ein Urteil – aus nächster Nähe vernichtend.',
    category: 'shotgun',
    kind: 'hitscan',
    fireMode: 'pump',
    burst: null,
    damage: {
      base: 14,
      headMultiplier: 1.5,
      limbMultiplier: 0.8,
      weakpointMultiplier: 1.8,
      falloffStart: 7,
      falloffEnd: 22,
      minFalloffMultiplier: 0.25,
      element: 'physical',
      impulse: 0.9,
      propImpulse: 40,
    },
    pellets: 9,
    rpm: 72,
    magazine: 8,
    reserve: 40,
    chambered: false,
    reload: {
      tactical: 0,
      empty: 0,
      tacticalSteps: [],
      emptySteps: [],
      perShell: {
        start: 0.32,
        shell: 0.44,
        insertAt: 0.3,
        end: 0.26,
        emptyEnd: 0.62,
        pumpAt: 0.28,
      },
    },
    spread: {
      // Pellet cone: the whole ring lands on a torso inside ~4 m, half of it at ~8 m.
      hip: 4.5,
      ads: 3.1,
      moveAdd: 0.6,
      airAdd: 1.4,
      crouchMultiplier: 0.9,
      perShotBloom: 0.8,
      bloomMax: 1.6,
      recoveryPerSec: 5,
      recoveryDelay: 0.2,
    },
    recoil: {
      pattern: [[0, 5.2]],
      patternRepeatFrom: 0,
      randomYaw: 0.9,
      randomPitch: 0.6,
      recoveryPerSec: 16,
      recoveryDelay: 0.12,
      resetTime: 0.9,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.85,
      kickTime: 0.07,
      viewPunch: { pitch: 4.2, yaw: 1.2, roll: 2.6 },
      visualKick: { back: 0.11, up: 0.03, side: 0.008, pitch: 16, yaw: 2.5, roll: 5 },
      shake: 0.48,
    },
    ads: {
      zoom: 0.88,
      inTime: 0.2,
      outTime: 0.15,
      moveSpeedMultiplier: 0.78,
      sensitivityMultiplier: 1,
    },
    // Pellets punch through glass and grates, not through crates or bodies.
    penetration: { power: 0.5, damageKeep: 0.55 },
    range: 70,
    equipTime: 0.55,
    holsterTime: 0.32,
    sprintToFireTime: 0.2,
    inspectTime: 2.6,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0xffd08a, pellets: 3 },
    vfx: {
      muzzle: 'muzzle.shotgun',
      impact: 'impact.pellet',
      casing: 'casing.shell',
      muzzleLightColor: 0xffa850,
    },
    audio: {
      fire: ['weapon.shotgun.fire', 'weapon.shotgun.boom', 'weapon.tail.large'],
      extraFire: ['weapon.shotgun.pumpCycle'],
      dry: 'weapon.dry',
      equip: 'weapon.shotgun.equip',
      holster: 'weapon.holster',
      reloadStart: 'weapon.shotgun.open',
      steps: { shellIn: 'weapon.shotgun.shellIn', pump: 'weapon.shotgun.pump' },
      melee: 'weapon.melee',
      inspect: 'weapon.inspect',
    },
    rumble: { strong: 0.8, weak: 0.9, ms: 140 },
    model: 'shotgun',
    cost: 1500,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'SG-12 „Drachenatem“',
        { damage: 1.7, magazine: 1.25, reserve: 1.6 },
        { kind: 'elementProc', element: 'fire', chance: 0.35, amount: 10 },
      ),
      forgeTier(
        2,
        'SG-12 „Höllenschlund“',
        { damage: 1.35, rpm: 1.2, extraPellets: 2, reloadTime: 0.85 },
        { kind: 'ricochet', bounces: 1, damageKeep: 0.6 },
      ),
      forgeTier(
        3,
        'SG-12 „Weltenbrecher“',
        { damage: 1.3, extraPellets: 3, element: 'fire', spread: 0.9 },
        { kind: 'fieldOnKill', chance: 0.4, field: FIRE_POOL },
        { tracerColor: 0xff7a2a },
      ),
    ],
  },

  autoshotgun: {
    id: 'autoshotgun',
    name: 'AS-20 „Mahlstrom“',
    shortName: 'AS-20',
    description: 'Vollautomatische Trommel-Schrotflinte. Sechzehn Schuss, die alles vor dir zermahlen.',
    category: 'shotgun',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 11,
      headMultiplier: 1.5,
      limbMultiplier: 0.8,
      weakpointMultiplier: 1.8,
      falloffStart: 6,
      falloffEnd: 18,
      minFalloffMultiplier: 0.25,
      element: 'physical',
      impulse: 0.75,
      propImpulse: 32,
    },
    pellets: 8,
    rpm: 300,
    magazine: 16,
    reserve: 96,
    chambered: true,
    reload: {
      tactical: 2.6,
      empty: 3.1,
      tacticalSteps: [
        { step: 'magOut', at: 0.5 },
        { step: 'magIn', at: 1.6 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.48 },
        { step: 'magIn', at: 1.55 },
        { step: 'boltRelease', at: 2.45 },
      ],
      perShell: null,
    },
    spread: {
      hip: 5.2,
      ads: 4,
      moveAdd: 0.6,
      airAdd: 1.4,
      crouchMultiplier: 0.9,
      perShotBloom: 0.5,
      bloomMax: 1.8,
      recoveryPerSec: 4,
      recoveryDelay: 0.3,
    },
    recoil: {
      // A thump up per shot with a left/right shove; strings of 3–4 stay on target.
      pattern: [
        [0, 2.2],
        [0.3, 2],
        [-0.3, 2],
        [0.4, 1.8],
        [-0.4, 1.8],
        [0.2, 1.7],
      ],
      patternRepeatFrom: 2,
      randomYaw: 0.6,
      randomPitch: 0.4,
      recoveryPerSec: 12,
      recoveryDelay: 0.1,
      resetTime: 0.5,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.85,
      kickTime: 0.06,
      viewPunch: { pitch: 2.6, yaw: 0.9, roll: 1.8 },
      visualKick: { back: 0.07, up: 0.02, side: 0.006, pitch: 10, yaw: 2, roll: 3.5 },
      shake: 0.3,
    },
    ads: {
      zoom: 0.88,
      inTime: 0.24,
      outTime: 0.16,
      moveSpeedMultiplier: 0.74,
      sensitivityMultiplier: 1,
    },
    penetration: { power: 0.5, damageKeep: 0.55 },
    range: 60,
    equipTime: 0.6,
    holsterTime: 0.34,
    sprintToFireTime: 0.22,
    inspectTime: 2.8,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0xffc070, pellets: 2 },
    vfx: {
      muzzle: 'muzzle.shotgun',
      impact: 'impact.pellet',
      casing: 'casing.shell',
      muzzleLightColor: 0xffa850,
    },
    audio: conventionAudio('autoshotgun', 'large'),
    rumble: { strong: 0.6, weak: 0.8, ms: 100 },
    model: 'autoshotgun',
    cost: 1500,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'AS-20 „Strudel“',
        { damage: 1.7, magazine: 1.5, reserve: 1.5 },
        { kind: 'elementProc', element: 'ice', chance: 0.3, amount: 10 },
      ),
      forgeTier(
        2,
        'AS-20 „Brandungswelle“',
        { damage: 1.35, rpm: 1.15, extraPellets: 2 },
        { kind: 'critBurst', everyNth: 4, multiplier: 2 },
      ),
      forgeTier(
        3,
        'AS-20 „Schlund der Welten“',
        { damage: 1.3, reloadTime: 0.8, reserve: 1.25 },
        { kind: 'fieldOnKill', chance: 0.25, field: VOID_MAW },
        { tracerColor: 0xb46cff },
      ),
    ],
  },

  doublebarrel: {
    id: 'doublebarrel',
    name: 'DB-2 „Zwilling“',
    shortName: 'DB-2',
    description: 'Doppelläufige Kipplauf-Flinte. Zwei Läufe, zwölf Kugeln je Lauf – danach wird geladen.',
    category: 'shotgun',
    kind: 'hitscan',
    fireMode: 'semi',
    burst: null,
    damage: {
      base: 15,
      headMultiplier: 1.5,
      limbMultiplier: 0.8,
      weakpointMultiplier: 1.8,
      falloffStart: 5,
      falloffEnd: 16,
      minFalloffMultiplier: 0.2,
      element: 'physical',
      impulse: 1.4,
      propImpulse: 55,
    },
    pellets: 12,
    // The second trigger follows as fast as the finger moves.
    rpm: 240,
    magazine: 2,
    reserve: 32,
    // Break action: both shells sit in the barrels, nothing beyond.
    chambered: false,
    reload: {
      // magOut = break open + extractor flings the shells, magIn = two shells in, boltRelease = snap shut.
      tactical: 1.85,
      empty: 2,
      tacticalSteps: [
        { step: 'magOut', at: 0.35 },
        { step: 'magIn', at: 0.95 },
        { step: 'boltRelease', at: 1.42 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.35 },
        { step: 'magIn', at: 1.02 },
        { step: 'boltRelease', at: 1.52 },
      ],
      perShell: null,
    },
    spread: {
      hip: 5.5,
      ads: 4.2,
      moveAdd: 0.5,
      airAdd: 1.2,
      crouchMultiplier: 0.9,
      perShotBloom: 1,
      bloomMax: 1.5,
      recoveryPerSec: 5,
      recoveryDelay: 0.2,
    },
    recoil: {
      pattern: [
        [0, 6.5],
        [0.6, 6],
      ],
      patternRepeatFrom: 0,
      randomYaw: 1.2,
      randomPitch: 0.7,
      recoveryPerSec: 18,
      recoveryDelay: 0.12,
      resetTime: 0.9,
      adsMultiplier: 0.8,
      crouchMultiplier: 0.85,
      kickTime: 0.07,
      viewPunch: { pitch: 5.5, yaw: 1.5, roll: 3.2 },
      visualKick: { back: 0.14, up: 0.04, side: 0.01, pitch: 20, yaw: 3, roll: 6 },
      shake: 0.6,
    },
    ads: {
      zoom: 0.9,
      inTime: 0.2,
      outTime: 0.15,
      moveSpeedMultiplier: 0.8,
      sensitivityMultiplier: 1,
    },
    penetration: { power: 0.5, damageKeep: 0.55 },
    range: 55,
    equipTime: 0.5,
    holsterTime: 0.3,
    sprintToFireTime: 0.18,
    inspectTime: 2.6,
    melee: MELEE_BASH,
    tracer: { everyNth: 1, color: 0xffcc80, pellets: 3 },
    // Shells leave on the break-open (reload), not per shot.
    vfx: { muzzle: 'muzzle.shotgun', impact: 'impact.pellet', casing: null, muzzleLightColor: 0xffa048 },
    audio: conventionAudio('doublebarrel', 'large'),
    rumble: { strong: 0.95, weak: 1, ms: 180 },
    model: 'doublebarrel',
    cost: 1100,
    attachmentSlots: ['muzzle', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'DB-2 „Kain und Abel“',
        { damage: 1.7, reserve: 1.6, reloadTime: 0.85 },
        { kind: 'critBurst', everyNth: 2, multiplier: 1.6 },
      ),
      forgeTier(
        2,
        'DB-2 „Blutsbrüder“',
        { damage: 1.35, extraPellets: 2, spread: 0.85 },
        { kind: 'lifesteal', fraction: 0.015 },
      ),
      forgeTier(
        3,
        'DB-2 „Zwillingssonnen“',
        { damage: 1.3, extraPellets: 2, element: 'fire', reloadTime: 0.85 },
        {
          kind: 'explosiveRounds',
          chance: 0.15,
          explosion: explosion('fire', 2.2, 80, { small: true }),
        },
        { tracerColor: 0xffa040 },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
