/**
 * Submachine guns. Angles in DEGREES, times in seconds, distances in meters, rates in rpm.
 * All three deliver ~310–350 body DPS (the KR-7's league) but trade range for handling: fast ADS,
 * short sprint-to-fire, hip fire that holds together inside ~12 m.
 *
 * Feel targets:
 * - SK-5 „Viper“: the honest all-rounder. 850 rpm, 30 rounds; an S-curve pattern (up, lean left,
 *   swing right, settle) that rewards a steady pull-down.
 *   Forge: Giftzahn (poison) → Basilisk (drains life) → Ouroboros (rounds ricochet twice towards
 *   the next enemy – the snake bites its own tail).
 * - PDW-50 „Sturmwind“: 50-round top-loaded magazine, 900 rpm, a flat gentle drift – the room
 *   clearer that never stops shooting. Longer reload (the magazine slides back along the top).
 *   Forge: Orkan (shock build-up) → Taifun (thunderclap crits) → Auge des Sturms (every hit arcs).
 * - KV-9 „Kolibri“: 1150 rpm with almost no recoil (a recoil-mitigating action): laser-straight
 *   bursts, tiny magazine, low per-bullet damage – precision at a blistering rate.
 *   Forge: Feuerkolibri (burn) → Sonnenvogel (crit rhythm) → Phönixschwinge (fire rounds that
 *   heal the shooter).
 */
import type { WeaponDef } from '../weapons';
import { MELEE_QUICK, conventionAudio, forgeTier } from './common';

export const SMGS = {
  smg: {
    id: 'smg',
    name: 'SK-5 „Viper“',
    shortName: 'SK-5',
    description: 'Kompakte Maschinenpistole. Zieht hoch, lehnt links, schwingt rechts – beherrsche die Kurve.',
    category: 'smg',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 22,
      headMultiplier: 1.8,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2.1,
      falloffStart: 14,
      falloffEnd: 36,
      minFalloffMultiplier: 0.55,
      element: 'physical',
      impulse: 0.9,
      propImpulse: 28,
    },
    pellets: 1,
    rpm: 850,
    magazine: 30,
    reserve: 210,
    chambered: true,
    reload: {
      tactical: 1.6,
      empty: 2.05,
      tacticalSteps: [
        { step: 'magOut', at: 0.34 },
        { step: 'magIn', at: 1 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.32 },
        { step: 'magIn', at: 0.98 },
        { step: 'boltRelease', at: 1.58 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.9,
      ads: 0.35,
      moveAdd: 0.8,
      airAdd: 2.2,
      crouchMultiplier: 0.8,
      perShotBloom: 0.14,
      bloomMax: 2.2,
      recoveryPerSec: 8,
      recoveryDelay: 0.12,
    },
    recoil: {
      // 1–5 climb, 6–8 lean left, 9–13 swing right, then a slow weave.
      pattern: [
        [0, 0.5],
        [0, 0.52],
        [-0.04, 0.54],
        [-0.08, 0.52],
        [-0.12, 0.48],
        [-0.14, 0.44],
        [-0.1, 0.42],
        [0, 0.4],
        [0.1, 0.38],
        [0.16, 0.36],
        [0.18, 0.35],
        [0.12, 0.34],
        [0, 0.34],
        [-0.1, 0.33],
        [-0.14, 0.33],
        [-0.06, 0.32],
        [0.06, 0.32],
        [0.12, 0.32],
      ],
      patternRepeatFrom: 12,
      randomYaw: 0.1,
      randomPitch: 0.06,
      recoveryPerSec: 9,
      recoveryDelay: 0.1,
      resetTime: 0.26,
      adsMultiplier: 0.65,
      crouchMultiplier: 0.85,
      kickTime: 0.04,
      viewPunch: { pitch: 0.55, yaw: 0.3, roll: 0.55 },
      visualKick: { back: 0.022, up: 0.005, side: 0.003, pitch: 3, yaw: 0.9, roll: 1.5 },
      shake: 0.1,
    },
    ads: {
      zoom: 0.82,
      inTime: 0.16,
      outTime: 0.12,
      moveSpeedMultiplier: 0.8,
      sensitivityMultiplier: 0.92,
    },
    penetration: { power: 1, damageKeep: 0.6 },
    range: 120,
    equipTime: 0.38,
    holsterTime: 0.24,
    sprintToFireTime: 0.1,
    inspectTime: 2.5,
    melee: MELEE_QUICK,
    tracer: { everyNth: 3, color: 0xffc060, pellets: 1 },
    vfx: { muzzle: 'muzzle.smg', impact: 'impact.bullet', casing: 'casing.pistol', muzzleLightColor: 0xffb868 },
    audio: conventionAudio('smg', 'small'),
    rumble: { strong: 0.15, weak: 0.4, ms: 45 },
    model: 'smg',
    cost: 1000,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'SK-5 „Giftzahn“',
        { damage: 1.7, magazine: 1.34, reserve: 1.6 },
        { kind: 'elementProc', element: 'poison', chance: 0.3, amount: 14 },
      ),
      forgeTier(
        2,
        'SK-5 „Basilisk“',
        { damage: 1.35, rpm: 1.08, reloadTime: 0.85 },
        { kind: 'lifesteal', fraction: 0.012 },
      ),
      forgeTier(
        3,
        'SK-5 „Ouroboros“',
        { damage: 1.3, magazine: 1.25, recoil: 0.85 },
        { kind: 'ricochet', bounces: 2, damageKeep: 0.8 },
        { tracerColor: 0x9dff6a },
      ),
    ],
  },

  pdw: {
    id: 'pdw',
    name: 'PDW-50 „Sturmwind“',
    shortName: 'PDW-50',
    description: 'Verteidigungswaffe mit 50-Schuss-Magazin obenauf. Flacher Rückstoß, endloser Sturm.',
    category: 'smg',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 19,
      headMultiplier: 1.7,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2,
      falloffStart: 14,
      falloffEnd: 34,
      minFalloffMultiplier: 0.55,
      element: 'physical',
      impulse: 0.8,
      propImpulse: 25,
    },
    pellets: 1,
    rpm: 900,
    magazine: 50,
    reserve: 300,
    chambered: true,
    reload: {
      // The top magazine tilts up and slides back off the rails – slower than a stick magazine.
      tactical: 2,
      empty: 2.45,
      tacticalSteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.28 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.25 },
        { step: 'boltRelease', at: 1.95 },
      ],
      perShell: null,
    },
    spread: {
      hip: 2,
      ads: 0.4,
      moveAdd: 0.75,
      airAdd: 2,
      crouchMultiplier: 0.8,
      perShotBloom: 0.1,
      bloomMax: 2.2,
      recoveryPerSec: 8,
      recoveryDelay: 0.11,
    },
    recoil: {
      // Flat: a gentle climb drifting right, back through center to the left, then a lazy sway.
      pattern: [
        [0, 0.4],
        [0.02, 0.42],
        [0.04, 0.42],
        [0.06, 0.4],
        [0.08, 0.38],
        [0.1, 0.36],
        [0.12, 0.34],
        [0.12, 0.32],
        [0.1, 0.3],
        [0.06, 0.3],
        [0.02, 0.3],
        [-0.02, 0.3],
        [-0.06, 0.3],
        [-0.08, 0.3],
        [-0.04, 0.3],
        [0.04, 0.3],
      ],
      patternRepeatFrom: 8,
      randomYaw: 0.1,
      randomPitch: 0.06,
      recoveryPerSec: 8,
      recoveryDelay: 0.1,
      resetTime: 0.26,
      adsMultiplier: 0.65,
      crouchMultiplier: 0.85,
      kickTime: 0.04,
      viewPunch: { pitch: 0.5, yaw: 0.25, roll: 0.5 },
      visualKick: { back: 0.02, up: 0.004, side: 0.003, pitch: 2.6, yaw: 0.8, roll: 1.3 },
      shake: 0.09,
    },
    ads: {
      zoom: 0.82,
      inTime: 0.18,
      outTime: 0.13,
      moveSpeedMultiplier: 0.8,
      sensitivityMultiplier: 0.92,
    },
    penetration: { power: 1, damageKeep: 0.6 },
    range: 120,
    equipTime: 0.42,
    holsterTime: 0.26,
    sprintToFireTime: 0.11,
    inspectTime: 2.7,
    melee: MELEE_QUICK,
    tracer: { everyNth: 4, color: 0xffc468, pellets: 1 },
    vfx: { muzzle: 'muzzle.smg', impact: 'impact.bullet', casing: 'casing.pistol', muzzleLightColor: 0xffbc70 },
    audio: conventionAudio('pdw', 'small'),
    rumble: { strong: 0.14, weak: 0.38, ms: 45 },
    model: 'pdw',
    cost: 1200,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'PDW-50 „Orkan“',
        { damage: 1.65, magazine: 1.2, reserve: 1.5 },
        { kind: 'elementProc', element: 'shock', chance: 0.2, amount: 14 },
      ),
      forgeTier(
        2,
        'PDW-50 „Taifun“',
        { damage: 1.35, rpm: 1.1, reloadTime: 0.82 },
        { kind: 'critBurst', everyNth: 10, multiplier: 3 },
      ),
      forgeTier(
        3,
        'PDW-50 „Auge des Sturms“',
        { damage: 1.3, magazine: 1.25, range: 1.2 },
        { kind: 'chainArc', chance: 1, count: 3, range: 7, damage: 40 },
        { tracerColor: 0x8fd8ff },
      ),
    ],
  },

  vector: {
    id: 'vector',
    name: 'KV-9 „Kolibri“',
    shortName: 'KV-9',
    description: 'Rückstoßgedämpfte Maschinenpistole. 1150 Schuss pro Minute, kaum ein Zittern.',
    category: 'smg',
    kind: 'hitscan',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 18,
      headMultiplier: 1.8,
      limbMultiplier: 0.8,
      weakpointMultiplier: 2,
      falloffStart: 12,
      falloffEnd: 30,
      minFalloffMultiplier: 0.5,
      element: 'physical',
      impulse: 0.7,
      propImpulse: 22,
    },
    pellets: 1,
    rpm: 1150,
    magazine: 25,
    reserve: 200,
    chambered: true,
    reload: {
      tactical: 1.5,
      empty: 1.9,
      tacticalSteps: [
        { step: 'magOut', at: 0.32 },
        { step: 'magIn', at: 0.92 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.3 },
        { step: 'magIn', at: 0.9 },
        { step: 'boltRelease', at: 1.46 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1.7,
      ads: 0.3,
      moveAdd: 0.7,
      airAdd: 1.8,
      crouchMultiplier: 0.8,
      perShotBloom: 0.1,
      bloomMax: 1.8,
      recoveryPerSec: 9,
      recoveryDelay: 0.1,
    },
    recoil: {
      // Almost straight: a tiny climb with a faint wobble around the center line.
      pattern: [
        [0, 0.26],
        [0.03, 0.27],
        [-0.03, 0.28],
        [0.03, 0.28],
        [-0.03, 0.27],
        [0.04, 0.26],
        [-0.04, 0.26],
        [0.03, 0.25],
      ],
      patternRepeatFrom: 2,
      randomYaw: 0.06,
      randomPitch: 0.04,
      recoveryPerSec: 10,
      recoveryDelay: 0.09,
      resetTime: 0.22,
      adsMultiplier: 0.6,
      crouchMultiplier: 0.85,
      kickTime: 0.03,
      viewPunch: { pitch: 0.35, yaw: 0.2, roll: 0.35 },
      visualKick: { back: 0.014, up: 0.003, side: 0.002, pitch: 1.8, yaw: 0.6, roll: 1 },
      shake: 0.07,
    },
    ads: {
      zoom: 0.84,
      inTime: 0.14,
      outTime: 0.11,
      moveSpeedMultiplier: 0.84,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0.5, damageKeep: 0.55 },
    range: 100,
    equipTime: 0.34,
    holsterTime: 0.22,
    sprintToFireTime: 0.09,
    inspectTime: 2.4,
    melee: MELEE_QUICK,
    tracer: { everyNth: 3, color: 0x9fe8ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.smg', impact: 'impact.bullet', casing: 'casing.pistol', muzzleLightColor: 0xffc480 },
    audio: conventionAudio('vector', 'small'),
    rumble: { strong: 0.1, weak: 0.32, ms: 35 },
    model: 'vector',
    cost: 1400,
    attachmentSlots: ['optic', 'muzzle', 'underbarrel', 'magazine', 'stock', 'laser'],
    upgrades: [
      forgeTier(
        1,
        'KV-9 „Feuerkolibri“',
        { damage: 1.7, magazine: 1.4, reserve: 1.6 },
        { kind: 'elementProc', element: 'fire', chance: 0.3, amount: 12 },
      ),
      forgeTier(
        2,
        'KV-9 „Sonnenvogel“',
        { damage: 1.35, rpm: 1.08, reloadTime: 0.85 },
        { kind: 'critBurst', everyNth: 6, multiplier: 2 },
      ),
      forgeTier(
        3,
        'KV-9 „Phönixschwinge“',
        { damage: 1.3, magazine: 1.3, element: 'fire' },
        { kind: 'lifesteal', fraction: 0.02 },
        { tracerColor: 0xff8a3a },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
