/**
 * Wonder weapons ("Wunderwaffen"): box only (WeaponDef.boxOnly – never on a wall), rare in the
 * Rift-Kiste, each with its own base special. Angles in DEGREES, times in seconds, distances in
 * meters, rates in rpm. No attachments: they are finished artifacts, the Rift Forge is their only
 * upgrade path.
 *
 * Feel targets:
 * - „Riss-Zerreißer“ (hitscan): tears a fan of five void rays (splitShot) through everything in
 *   front of it – 380 void per ray, piercing every body; eight tears per cell. A wave-20 corridor
 *   empties in two pulls.
 *   Forge: Weltenriss (six rays) → Leerenschlund (seven, faster) → Ende aller Dinge (a nine-ray
 *   curtain of void at a higher rate).
 * - „Äther-Harfe“ (projectile): 300 rpm of slow homing shock orbs that pass through three bodies
 *   and arc to two more on every hit – a chord of lightning that finds its own targets.
 *   Forge: Sphärenklang (three arcs) → Himmelschor (four, faster orbs) → Symphonie des Sturms
 *   (six arcs, huge reach).
 * - „Kryo-Nova“ (projectile): a heavy ice orb that bursts into a 5 m freezing nova (320 ice,
 *   freezes everything it touches) and leaves a 6 m frost field that slows the horde for 5 s.
 *   Forge: Permafrost (harder freeze) → Eiszeit (kills bloom into frost fields) → Absoluter
 *   Nullpunkt (three orbs per shot).
 */
import type { WeaponDef } from '../weapons';
import { MELEE_HEAVY, conventionAudio, explosion, field, forgeTier } from './common';

/** Frost bloom left by a kill (Kryo-Nova „Eiszeit“). */
const FROST_BLOOM = field('slow', 'ice', 3.5, 4, 10, 0.4);

export const WONDER = {
  riftripper: {
    id: 'riftripper',
    name: '„Riss-Zerreißer“',
    shortName: 'Zerreißer',
    description: 'Wunderwaffe. Reißt einen Fächer aus Leere durch alles, was vor dir steht.',
    category: 'wonder',
    kind: 'hitscan',
    fireMode: 'semi',
    burst: null,
    damage: {
      base: 380,
      headMultiplier: 1.5,
      limbMultiplier: 1,
      weakpointMultiplier: 2,
      falloffStart: 60,
      falloffEnd: 120,
      minFalloffMultiplier: 0.8,
      element: 'void',
      impulse: 5,
      propImpulse: 250,
    },
    pellets: 1,
    rpm: 150,
    magazine: 8,
    reserve: 64,
    chambered: false,
    reload: {
      tactical: 2.4,
      empty: 2.9,
      tacticalSteps: [
        { step: 'magOut', at: 0.45 },
        { step: 'magIn', at: 1.4 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.35 },
        { step: 'boltRelease', at: 2.2 },
      ],
      perShell: null,
    },
    spread: {
      hip: 0.6,
      ads: 0.15,
      moveAdd: 0.6,
      airAdd: 1.5,
      crouchMultiplier: 0.9,
      perShotBloom: 0.3,
      bloomMax: 1,
      recoveryPerSec: 6,
      recoveryDelay: 0.2,
    },
    recoil: {
      pattern: [
        [0, 3.8],
        [0.4, 3.5],
        [-0.4, 3.5],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.5,
      randomPitch: 0.3,
      recoveryPerSec: 14,
      recoveryDelay: 0.1,
      resetTime: 0.6,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.85,
      kickTime: 0.06,
      viewPunch: { pitch: 3.5, yaw: 1, roll: 2.5 },
      visualKick: { back: 0.09, up: 0.03, side: 0.008, pitch: 12, yaw: 2, roll: 4 },
      shake: 0.38,
    },
    ads: {
      zoom: 0.8,
      inTime: 0.24,
      outTime: 0.16,
      moveSpeedMultiplier: 0.75,
      sensitivityMultiplier: 0.9,
    },
    // Pierces every body (up to COMBAT.maxPenetrations), armor included; walls still stop it.
    penetration: { power: 12, damageKeep: 0.9 },
    range: 160,
    equipTime: 0.6,
    holsterTime: 0.34,
    sprintToFireTime: 0.2,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 1, color: 0xc050ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.void', impact: 'impact.void', casing: null, muzzleLightColor: 0xc060ff },
    audio: conventionAudio('riftripper', 'energy'),
    rumble: { strong: 0.8, weak: 0.9, ms: 160 },
    model: 'riftripper',
    cost: 6000,
    boxOnly: true,
    attachmentSlots: [],
    special: { kind: 'splitShot', count: 4, angleDeg: 6 },
    upgrades: [
      forgeTier(
        1,
        '„Weltenriss“',
        { damage: 1.5, magazine: 1.5, reserve: 1.5 },
        { kind: 'splitShot', count: 5, angleDeg: 7 },
      ),
      forgeTier(
        2,
        '„Leerenschlund“',
        { damage: 1.35, rpm: 1.25, reloadTime: 0.8 },
        { kind: 'splitShot', count: 6, angleDeg: 9 },
      ),
      forgeTier(
        3,
        '„Ende aller Dinge“',
        { damage: 1.3, rpm: 1.2, magazine: 1.34 },
        { kind: 'splitShot', count: 8, angleDeg: 14 },
        { tracerColor: 0xff60ff, palette: 'forgeVoid' },
      ),
    ],
  },

  aetherharp: {
    id: 'aetherharp',
    name: '„Äther-Harfe“',
    shortName: 'Harfe',
    description: 'Wunderwaffe. Suchende Blitzkugeln, die durch Körper gleiten und weiterspringen.',
    category: 'wonder',
    kind: 'projectile',
    fireMode: 'auto',
    burst: null,
    damage: {
      base: 110,
      headMultiplier: 1.3,
      limbMultiplier: 1,
      weakpointMultiplier: 1.8,
      falloffStart: 30,
      falloffEnd: 60,
      minFalloffMultiplier: 0.8,
      element: 'shock',
      impulse: 1.5,
      propImpulse: 60,
    },
    pellets: 1,
    rpm: 300,
    magazine: 30,
    reserve: 240,
    chambered: false,
    reload: {
      tactical: 2.2,
      empty: 2.7,
      tacticalSteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.3 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.4 },
        { step: 'magIn', at: 1.25 },
        { step: 'boltRelease', at: 2.05 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1,
      ads: 0.4,
      moveAdd: 0.6,
      airAdd: 1.5,
      crouchMultiplier: 0.9,
      perShotBloom: 0.15,
      bloomMax: 1.2,
      recoveryPerSec: 5,
      recoveryDelay: 0.3,
    },
    recoil: {
      // Each orb plucks the weapon like a string: a light lift with an alternating sway.
      pattern: [
        [0, 0.7],
        [0.15, 0.65],
        [-0.15, 0.65],
        [0.1, 0.6],
      ],
      patternRepeatFrom: 1,
      randomYaw: 0.1,
      randomPitch: 0.08,
      recoveryPerSec: 8,
      recoveryDelay: 0.22,
      resetTime: 0.4,
      adsMultiplier: 0.7,
      crouchMultiplier: 0.85,
      kickTime: 0.05,
      viewPunch: { pitch: 0.9, yaw: 0.4, roll: 0.8 },
      visualKick: { back: 0.03, up: 0.008, side: 0.004, pitch: 4, yaw: 1, roll: 2 },
      shake: 0.12,
    },
    ads: {
      zoom: 0.82,
      inTime: 0.24,
      outTime: 0.16,
      moveSpeedMultiplier: 0.75,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 80,
    equipTime: 0.6,
    holsterTime: 0.34,
    sprintToFireTime: 0.2,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0x9fd0ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.shock', impact: 'impact.shock', casing: null, muzzleLightColor: 0x9fd0ff },
    audio: conventionAudio('aetherharp', 'energy'),
    rumble: { strong: 0.25, weak: 0.5, ms: 70 },
    model: 'aetherharp',
    cost: 6000,
    boxOnly: true,
    attachmentSlots: [],
    special: { kind: 'chainArc', chance: 1, count: 2, range: 6, damage: 60 },
    projectile: {
      speed: 32,
      gravity: 0,
      radius: 0.12,
      lifetime: 2.5,
      bounces: 0,
      restitution: 0,
      fuse: 0,
      pierce: 3,
      homing: 4,
      explosion: null,
      field: null,
      visual: 'projectile.shockorb',
      trail: 'trail.shock',
      flightAudio: 'projectile.shockorb.flight',
    },
    upgrades: [
      forgeTier(
        1,
        '„Sphärenklang“',
        { damage: 1.5, magazine: 1.34, reserve: 1.5 },
        { kind: 'chainArc', chance: 1, count: 3, range: 7, damage: 80 },
      ),
      forgeTier(
        2,
        '„Himmelschor“',
        { damage: 1.35, rpm: 1.2, projectileSpeed: 1.25 },
        { kind: 'chainArc', chance: 1, count: 4, range: 8, damage: 100 },
      ),
      forgeTier(
        3,
        '„Symphonie des Sturms“',
        { damage: 1.3, magazine: 1.25, reloadTime: 0.8 },
        { kind: 'chainArc', chance: 1, count: 6, range: 10, damage: 140 },
        { tracerColor: 0xd8f0ff },
      ),
    ],
  },

  cryonova: {
    id: 'cryonova',
    name: '„Kryo-Nova“',
    shortName: 'Kryo-Nova',
    description: 'Wunderwaffe. Eine Eiskugel, die zur frostigen Nova zerbirst und alles erstarren lässt.',
    category: 'wonder',
    kind: 'projectile',
    fireMode: 'semi',
    burst: null,
    // Direct hit; the nova (explosion) and the frost field come from `projectile`.
    damage: {
      base: 120,
      headMultiplier: 1.3,
      limbMultiplier: 1,
      weakpointMultiplier: 1.8,
      falloffStart: 30,
      falloffEnd: 60,
      minFalloffMultiplier: 0.9,
      element: 'ice',
      impulse: 2,
      propImpulse: 120,
    },
    pellets: 1,
    rpm: 60,
    magazine: 6,
    reserve: 36,
    chambered: false,
    reload: {
      // magOut = the spent canister, magIn = a fresh canister, boltRelease = the fins lock.
      tactical: 2.4,
      empty: 2.9,
      tacticalSteps: [
        { step: 'magOut', at: 0.45 },
        { step: 'magIn', at: 1.4 },
      ],
      emptySteps: [
        { step: 'magOut', at: 0.42 },
        { step: 'magIn', at: 1.35 },
        { step: 'boltRelease', at: 2.2 },
      ],
      perShell: null,
    },
    spread: {
      hip: 1,
      ads: 0.25,
      moveAdd: 0.8,
      airAdd: 1.8,
      crouchMultiplier: 0.9,
      perShotBloom: 0.3,
      bloomMax: 1,
      recoveryPerSec: 4,
      recoveryDelay: 0.3,
    },
    recoil: {
      pattern: [
        [0, 2.8],
        [0.3, 2.6],
        [-0.3, 2.6],
      ],
      patternRepeatFrom: 0,
      randomYaw: 0.4,
      randomPitch: 0.3,
      recoveryPerSec: 12,
      recoveryDelay: 0.12,
      resetTime: 0.9,
      adsMultiplier: 0.75,
      crouchMultiplier: 0.85,
      kickTime: 0.07,
      viewPunch: { pitch: 2.6, yaw: 0.6, roll: 1.8 },
      visualKick: { back: 0.07, up: 0.025, side: 0.006, pitch: 9, yaw: 1.5, roll: 3 },
      shake: 0.3,
    },
    ads: {
      zoom: 0.84,
      inTime: 0.26,
      outTime: 0.18,
      moveSpeedMultiplier: 0.74,
      sensitivityMultiplier: 0.95,
    },
    penetration: { power: 0, damageKeep: 0.5 },
    range: 100,
    equipTime: 0.65,
    holsterTime: 0.36,
    sprintToFireTime: 0.22,
    inspectTime: 3.2,
    melee: MELEE_HEAVY,
    tracer: { everyNth: 0, color: 0xa8e8ff, pellets: 1 },
    vfx: { muzzle: 'muzzle.ice', impact: 'impact.ice', casing: null, muzzleLightColor: 0x9fe0ff },
    audio: conventionAudio('cryonova', 'energy'),
    rumble: { strong: 0.6, weak: 0.8, ms: 160 },
    model: 'cryonova',
    cost: 6000,
    boxOnly: true,
    attachmentSlots: [],
    special: { kind: 'elementProc', element: 'ice', chance: 1, amount: 100 },
    projectile: {
      speed: 26,
      gravity: 2,
      radius: 0.18,
      lifetime: 4,
      bounces: 0,
      restitution: 0,
      fuse: 0,
      pierce: 0,
      homing: 0,
      explosion: explosion('ice', 5, 320, { minFalloff: 0.4, impulse: 5, propImpulse: 300, shake: 0.4 }),
      field: field('slow', 'ice', 6, 5, 20, 0.35),
      visual: 'projectile.cryoorb',
      trail: 'trail.frost',
      flightAudio: 'projectile.cryoorb.flight',
    },
    upgrades: [
      forgeTier(
        1,
        '„Permafrost“',
        { damage: 1.5, magazine: 1.34, reserve: 1.5, blastRadius: 1.15 },
        { kind: 'elementProc', element: 'ice', chance: 1, amount: 150 },
      ),
      forgeTier(
        2,
        '„Eiszeit“',
        { damage: 1.35, rpm: 1.3, reloadTime: 0.8 },
        { kind: 'fieldOnKill', chance: 0.35, field: FROST_BLOOM },
      ),
      forgeTier(
        3,
        '„Absoluter Nullpunkt“',
        { damage: 1.3, blastRadius: 1.2 },
        { kind: 'splitShot', count: 2, angleDeg: 10 },
        { tracerColor: 0xe0f8ff, palette: 'forgeFrost' },
      ),
    ],
  },
} as const satisfies Record<string, WeaponDef>;
