#!/usr/bin/env node
/**
 * Downloads the CC0 assets listed in src/defs/assets.ts (Poly Haven) into public/assets/ and
 * writes public/assets/available.json – the index the runtime AssetLoader reads first (assets not
 * listed there are never requested). Also regenerates the asset section of CREDITS.md.
 *
 *   node scripts/fetch-assets.mjs [--strict] [--force] [--no-ktx2] [--no-prune] [--dry-run] [--only=id,id]
 *
 * --strict   exit 1 if anything failed (default: warn and exit 0 – assets are optional)
 * --force    re-download / re-convert even if files exist and verify
 * --no-ktx2  skip the optional KTX2 conversion (otherwise done when `toktx` is on PATH)
 * --no-prune keep files the index no longer references (default: delete them, see below)
 * --dry-run  only resolve URLs and print what would be downloaded
 * --only     restrict to the given asset ids (other entries of the previous index are kept)
 *
 * Idempotent: existing files whose size/MD5 match Poly Haven's metadata are kept; a KTX2 file is
 * kept only if it is a complete container, newer than its source and made with the current
 * ASSETS.ktx2 arguments (recorded per entry in the index). Downloads, conversions, the index and
 * CREDITS.md are written to a temp file and renamed, so an interrupted run never leaves a truncated
 * file that a later run trusts. Index entries of ids no longer in src/defs/assets.ts are dropped,
 * and files below the texture/HDRI folders that the index does not reference (removed or renamed
 * assets, old resolutions, leftovers of interrupted runs) are deleted – Vite would otherwise ship
 * them, uncredited. Node 20+, no dependencies (src/defs/assets.ts is loaded via Node's type
 * stripping, or transpiled with the project's TypeScript on older Node versions).
 */
import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, open, readFile, readdir, rename, rm, rmdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC_DIR = join(ROOT, 'public');
const DEFS_FILE = join(ROOT, 'src', 'defs', 'assets.ts');
const CREDITS_FILE = join(ROOT, 'CREDITS.md');
const CREDITS_BEGIN = '<!-- ASSET-CREDITS:BEGIN (generated by scripts/fetch-assets.mjs) -->';
const CREDITS_END = '<!-- ASSET-CREDITS:END -->';

const args = process.argv.slice(2);
const flags = {
  strict: args.includes('--strict'),
  force: args.includes('--force'),
  noKtx2: args.includes('--no-ktx2'),
  noPrune: args.includes('--no-prune'),
  dryRun: args.includes('--dry-run'),
  only: (args.find((a) => a.startsWith('--only=')) ?? '').slice('--only='.length).split(',').filter(Boolean),
};

// ---------------------------------------------------------------------------
// Proxy support: Node's fetch ignores HTTPS_PROXY unless NODE_USE_ENV_PROXY=1 (Node >= 22.21 / 24.5).
// ---------------------------------------------------------------------------

async function reexecWithEnvProxy() {
  const proxy = process.env.HTTPS_PROXY || process.env.https_proxy;
  if (!proxy || process.env.NODE_USE_ENV_PROXY || process.env.RIFTFALL_FETCH_CHILD) return;
  const nodeArgs = [...process.execArgv];
  if (process.allowedNodeEnvironmentFlags.has('--disable-warning'))
    nodeArgs.push('--disable-warning=UNDICI-EHPA');
  const child = spawn(process.execPath, [...nodeArgs, fileURLToPath(import.meta.url), ...args], {
    stdio: 'inherit',
    env: { ...process.env, NODE_USE_ENV_PROXY: '1', RIFTFALL_FETCH_CHILD: '1' },
  });
  const code = await new Promise((res) => {
    child.on('exit', (c) => res(c ?? 0));
    child.on('error', () => res(-1));
  });
  if (code === -1) return; // could not spawn – continue in this process
  process.exit(code);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function fmtBytes(n) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

async function loadDefs() {
  try {
    return await import(pathToFileURL(DEFS_FILE).href);
  } catch (nativeErr) {
    try {
      const ts = (await import('typescript')).default;
      const source = await readFile(DEFS_FILE, 'utf8');
      const js = ts.transpileModule(source, {
        compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
      }).outputText;
      return await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
    } catch (tsErr) {
      throw new Error(
        `cannot load ${DEFS_FILE}: ${nativeErr.message}; TypeScript fallback: ${tsErr.message}`,
        {
          cause: tsErr,
        },
      );
    }
  }
}

class HttpError extends Error {
  constructor(status, url) {
    super(`HTTP ${status} for ${url}`);
    this.status = status;
  }
}

async function fetchRetry(url, { as, timeoutMs, cfg }) {
  let lastErr;
  for (let attempt = 0; attempt <= cfg.retries; attempt++) {
    try {
      const res = await fetch(url, {
        signal: AbortSignal.timeout(timeoutMs),
        headers: { 'User-Agent': cfg.userAgent },
      });
      if (!res.ok) throw new HttpError(res.status, url);
      return as === 'json' ? await res.json() : Buffer.from(await res.arrayBuffer());
    } catch (err) {
      lastErr = err;
      const permanent =
        err instanceof HttpError && err.status >= 400 && err.status < 500 && err.status !== 429;
      if (permanent || attempt === cfg.retries) break;
      const delay = cfg.retryBaseDelayMs * 2 ** attempt;
      console.warn(`  ! ${err.message ?? err} – retry ${attempt + 1}/${cfg.retries} in ${delay} ms`);
      await sleep(delay);
    }
  }
  throw lastErr;
}

function md5(buf) {
  return createHash('md5').update(buf).digest('hex');
}

async function fileMatches(absPath, meta) {
  try {
    const st = await stat(absPath);
    if (!st.isFile() || st.size === 0) return false;
    if (meta?.size !== undefined && st.size !== meta.size) return false;
    if (meta?.md5) return md5(await readFile(absPath)) === meta.md5;
    return true;
  } catch {
    return false;
  }
}

async function exists(absPath) {
  try {
    return (await stat(absPath)).isFile();
  } catch {
    return false;
  }
}

/** Write via a temp file + rename: readers never see a truncated file, even after a crash. */
async function writeFileAtomic(absPath, data) {
  const tmp = `${absPath}.tmp`;
  await writeFile(tmp, data);
  await rename(tmp, absPath);
}

/** Assets of the previous available.json (null if missing, unreadable or another version). */
async function readPreviousIndex(indexPath, version) {
  try {
    const old = JSON.parse(await readFile(indexPath, 'utf8'));
    return old?.version === version && old.assets && typeof old.assets === 'object' ? old.assets : null;
  } catch {
    return null;
  }
}

/** Base-relative, forward-slash path of a file below public/ (the form the index uses). */
function publicRel(absPath) {
  return relative(PUBLIC_DIR, absPath).split(sep).join('/');
}

/**
 * Deletes files below absDir that are not in `keep` (base-relative paths) and directories that end
 * up empty. Returns how many entries remain in absDir.
 */
async function pruneDir(absDir, keep, stats) {
  let entries;
  try {
    entries = await readdir(absDir, { withFileTypes: true });
  } catch {
    return 0;
  }
  let remaining = 0;
  for (const entry of entries) {
    const abs = join(absDir, entry.name);
    if (entry.isDirectory()) {
      if ((await pruneDir(abs, keep, stats)) === 0) await rmdir(abs);
      else remaining++;
      continue;
    }
    const rel = publicRel(abs);
    if (keep.has(rel)) {
      remaining++;
      continue;
    }
    stats.bytes += (await stat(abs)).size;
    await rm(abs, { force: true });
    stats.removed++;
    console.info(`  pruned public/${rel}`);
  }
  return remaining;
}

/** Poly Haven files JSON: map key → resolution → format → { url, md5, size }. */
function pickFile(filesJson, key, resolutions, format) {
  const byRes = filesJson?.[key];
  if (!byRes) return null;
  for (const res of resolutions) {
    const file = byRes[res]?.[format];
    if (file?.url) return { res, url: file.url, md5: file.md5, size: file.size };
  }
  return null;
}

async function runLimited(items, limit, fn) {
  let next = 0;
  const worker = async () => {
    while (next < items.length) {
      const i = next++;
      await fn(items[i], i);
    }
  };
  await Promise.all(Array.from({ length: Math.max(1, Math.min(limit, items.length)) }, worker));
}

// ---------------------------------------------------------------------------
// KTX2 (optional)
// ---------------------------------------------------------------------------

/** KTX2 identifier: «KTX 20»\r\n\x1A\n. */
const KTX2_MAGIC = Buffer.from([0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb, 0x0d, 0x0a, 0x1a, 0x0a]);
/** Identifier + header + index; the level index follows. */
const KTX2_HEADER_BYTES = 80;
const KTX2_LEVEL_COUNT_OFFSET = 40;
/** byteOffset, byteLength, uncompressedByteLength (uint64 each). */
const KTX2_LEVEL_ENTRY_BYTES = 24;
/** More mip levels than a 2^31 texture has: a corrupt header. */
const KTX2_MAX_LEVELS = 32;

/** True if the file is a complete KTX2 container: identifier present and every mip level inside the file. */
async function ktx2Complete(absPath) {
  let fh;
  try {
    fh = await open(absPath, 'r');
    const { size } = await fh.stat();
    if (size < KTX2_HEADER_BYTES) return false;
    const header = Buffer.alloc(KTX2_HEADER_BYTES);
    await fh.read(header, 0, KTX2_HEADER_BYTES, 0);
    if (!header.subarray(0, KTX2_MAGIC.length).equals(KTX2_MAGIC)) return false;
    // levelCount 0 = "generate mips at runtime", still one level entry.
    const levels = Math.max(1, header.readUInt32LE(KTX2_LEVEL_COUNT_OFFSET));
    if (levels > KTX2_MAX_LEVELS) return false;
    const index = Buffer.alloc(levels * KTX2_LEVEL_ENTRY_BYTES);
    const { bytesRead } = await fh.read(index, 0, index.length, KTX2_HEADER_BYTES);
    if (bytesRead < index.length) return false;
    for (let i = 0; i < levels; i++) {
      const offset = index.readBigUInt64LE(i * KTX2_LEVEL_ENTRY_BYTES);
      const length = index.readBigUInt64LE(i * KTX2_LEVEL_ENTRY_BYTES + 8);
      if (length === 0n || offset + length > BigInt(size)) return false;
    }
    return true;
  } catch {
    return false;
  } finally {
    await fh?.close();
  }
}

/** Short hash of a conversion command: stored in the index, a change of ASSETS.ktx2 reconverts. */
function conversionSignature(tool, toolArgs) {
  return createHash('sha1')
    .update(JSON.stringify([tool, ...toolArgs]))
    .digest('hex')
    .slice(0, 16);
}

function hasTool(tool) {
  const r = spawnSync(tool, ['--version'], { stdio: 'ignore' });
  return !r.error;
}

function runTool(tool, toolArgs, timeoutMs) {
  return new Promise((res) => {
    const child = spawn(tool, toolArgs, { stdio: ['ignore', 'ignore', 'pipe'] });
    let stderr = '';
    child.stderr.on('data', (d) => (stderr += d));
    const timer = setTimeout(() => child.kill('SIGKILL'), timeoutMs);
    child.on('error', (err) => {
      clearTimeout(timer);
      res({ ok: false, message: err.message });
    });
    child.on('exit', (code) => {
      clearTimeout(timer);
      res({ ok: code === 0, message: stderr.trim().split('\n').slice(-2).join(' ') });
    });
  });
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  await reexecWithEnvProxy();
  const defs = await loadDefs();
  const {
    ASSET_DEFS,
    ASSETS,
    POLYHAVEN,
    polyHavenHdriPath,
    polyHavenTexturePath,
    withExtension,
    SRGB_TEXTURE_ROLES,
  } = defs;
  const cfg = ASSETS.fetch;
  const selected = ASSET_DEFS.filter((d) => flags.only.length === 0 || flags.only.includes(d.id));
  const ktx2Enabled = !flags.noKtx2 && !flags.dryRun && hasTool(ASSETS.ktx2.tool);
  const indexPath = join(PUBLIC_DIR, ASSETS.indexFile);
  const previousAssets = await readPreviousIndex(indexPath, ASSETS.indexVersion);

  console.info(`RIFTFALL asset fetch – ${selected.length} asset(s) from Poly Haven (CC0) → public/assets/`);
  console.info(
    ktx2Enabled
      ? `  KTX2: "${ASSETS.ktx2.tool}" found – converting textures (ETC1S color, UASTC data/normals)`
      : `  KTX2: ${flags.noKtx2 ? 'disabled (--no-ktx2)' : `"${ASSETS.ktx2.tool}" not on PATH – JPG only`}`,
  );

  const results = [];
  const unsupported = new Set();

  await runLimited(selected, cfg.concurrency, async (def) => {
    const result = {
      id: def.id,
      type: def.type,
      files: {},
      ktx2: {},
      /** role → conversionSignature of the KTX2 file. */
      ktx2Args: {},
      downloaded: 0,
      cached: 0,
      bytes: 0,
      errors: [],
      warnings: [],
    };
    results.push(result);
    const { assetId } = def.source;
    const resolutions = [
      def.source.resolution,
      ...cfg.resolutionFallback.filter((r) => r !== def.source.resolution),
    ];

    if (def.source.provider !== 'polyhaven' || (def.type !== 'hdri' && def.type !== 'textureSet')) {
      unsupported.add(def.id);
      result.errors.push(`unsupported source/type (${def.source.provider}/${def.type})`);
      return;
    }

    let filesJson = null;
    try {
      filesJson = await fetchRetry(`${POLYHAVEN.apiBase}/files/${assetId}`, {
        as: 'json',
        timeoutMs: cfg.requestTimeoutMs,
        cfg,
      });
    } catch (err) {
      result.errors.push(`Poly Haven API unreachable (${err.message ?? err}) – indexing local files only`);
    }

    // Credit check (non-fatal): warn if Poly Haven lists different authors than defs/assets.ts.
    if (filesJson && !flags.dryRun) {
      try {
        const info = await fetchRetry(`${POLYHAVEN.apiBase}/info/${assetId}`, {
          as: 'json',
          timeoutMs: cfg.requestTimeoutMs,
          cfg,
        });
        const authors = Object.keys(info.authors ?? {})
          .sort()
          .join(', ');
        const credited = def.credit.author
          .split(',')
          .map((a) => a.trim())
          .sort()
          .join(', ');
        if (authors && authors !== credited)
          result.warnings.push(`credit authors differ from Poly Haven: "${authors}"`);
      } catch {
        // informational only
      }
    }

    /** role → { key, format, pathFor(res) } */
    const wanted = [];
    if (def.type === 'hdri') {
      wanted.push({
        role: 'hdr',
        key: POLYHAVEN.hdriKey,
        format: POLYHAVEN.hdriFormat,
        pathFor: (r) => polyHavenHdriPath(assetId, r),
        required: true,
      });
    } else {
      for (const role of POLYHAVEN.primaryTextureRoles) {
        const m = POLYHAVEN.textureMaps[role];
        wanted.push({
          role,
          key: m.key,
          format: POLYHAVEN.textureFormat,
          pathFor: (r) => polyHavenTexturePath(assetId, role, r),
          required: role === 'map',
        });
      }
      const hasArm =
        !filesJson ||
        pickFile(filesJson, POLYHAVEN.textureMaps.ormMap.key, resolutions, POLYHAVEN.textureFormat);
      if (!hasArm) {
        for (const role of POLYHAVEN.fallbackTextureRoles) {
          const m = POLYHAVEN.textureMaps[role];
          wanted.push({
            role,
            key: m.key,
            format: POLYHAVEN.textureFormat,
            pathFor: (r) => polyHavenTexturePath(assetId, role, r),
            required: false,
          });
        }
      }
    }

    for (const w of wanted) {
      if (!filesJson) {
        // Offline: keep whatever a previous run downloaded.
        for (const r of resolutions) {
          const rel = w.pathFor(r);
          if (await exists(join(PUBLIC_DIR, rel))) {
            result.files[w.role] = rel;
            result.cached++;
            break;
          }
        }
        continue;
      }
      const pick = pickFile(filesJson, w.key, resolutions, w.format);
      if (!pick) {
        (w.required ? result.errors : result.warnings).push(
          `no ${w.key} (${w.format}) at ${resolutions.join('/')}`,
        );
        continue;
      }
      const rel = w.pathFor(pick.res);
      const abs = join(PUBLIC_DIR, rel);
      if (flags.dryRun) {
        console.info(`  [dry-run] ${def.id}.${w.role} ← ${pick.url} (${fmtBytes(pick.size ?? 0)})`);
        result.files[w.role] = rel;
        continue;
      }
      if (!flags.force && (await fileMatches(abs, pick))) {
        result.files[w.role] = rel;
        result.cached++;
        continue;
      }
      try {
        const buf = await fetchRetry(pick.url, { as: 'buffer', timeoutMs: cfg.downloadTimeoutMs, cfg });
        if (pick.md5 && md5(buf) !== pick.md5) throw new Error(`checksum mismatch for ${pick.url}`);
        await mkdir(dirname(abs), { recursive: true });
        await writeFile(`${abs}.part`, buf);
        await rename(`${abs}.part`, abs);
        result.files[w.role] = rel;
        result.downloaded++;
        result.bytes += buf.length;
      } catch (err) {
        await rm(`${abs}.part`, { force: true });
        (w.required ? result.errors : result.warnings).push(`${w.role}: ${err.message ?? err}`);
      }
    }

    if (def.type === 'textureSet' && !result.files.map)
      result.errors.push('albedo map missing – set unusable');

    if (ktx2Enabled && def.type === 'textureSet') {
      for (const [role, rel] of Object.entries(result.files)) {
        const src = join(PUBLIC_DIR, rel);
        const outRel = withExtension(rel, 'ktx2');
        const out = join(PUBLIC_DIR, outRel);
        // toktx writes its output in place: convert into a temp file (still *.ktx2) and rename.
        const tmp = join(PUBLIC_DIR, withExtension(rel, 'part.ktx2'));
        const toolArgs = SRGB_TEXTURE_ROLES.includes(role) ? ASSETS.ktx2.colorArgs : ASSETS.ktx2.dataArgs;
        const signature = conversionSignature(ASSETS.ktx2.tool, toolArgs);
        try {
          const fresh =
            !flags.force &&
            previousAssets?.[def.id]?.ktx2Args?.[role] === signature &&
            (await ktx2Complete(out)) &&
            (await stat(out)).mtimeMs >= (await stat(src)).mtimeMs;
          if (!fresh) {
            const r = await runTool(ASSETS.ktx2.tool, [...toolArgs, tmp, src], ASSETS.ktx2.timeoutMs);
            if (!r.ok) throw new Error(r.message || 'conversion failed');
            if (!(await ktx2Complete(tmp))) throw new Error('conversion wrote an incomplete KTX2 file');
            await rename(tmp, out);
          }
          result.ktx2[role] = outRel;
          result.ktx2Args[role] = signature;
        } catch (err) {
          await rm(tmp, { force: true });
          await rm(out, { force: true });
          result.warnings.push(`KTX2 ${role}: ${err.message ?? err}`);
        }
      }
    }
  });

  results.sort((a, b) => selected.findIndex((d) => d.id === a.id) - selected.findIndex((d) => d.id === b.id));

  // --- available.json -------------------------------------------------------
  const usable = results.filter((r) => (r.type === 'hdri' ? r.files.hdr : r.files.map));
  const partial = flags.only.length > 0;
  let pruned = null;
  if (!flags.dryRun) {
    const assets = {};
    if (partial) {
      // Partial run: keep entries of defined assets that were not processed.
      if (!previousAssets)
        console.warn(
          '  ! previous index missing or unreadable – it will list only the processed assets (run without --only to rebuild it)',
        );
      const defined = new Set(ASSET_DEFS.map((d) => d.id));
      const processed = new Set(results.map((r) => r.id));
      for (const [id, entry] of Object.entries(previousAssets ?? {})) {
        if (!defined.has(id)) console.info(`  index: dropped "${id}" (not in src/defs/assets.ts any more)`);
        else if (!processed.has(id)) assets[id] = entry;
      }
    }
    for (const r of usable) {
      assets[r.id] = {
        type: r.type,
        files: r.files,
        ...(Object.keys(r.ktx2).length > 0 ? { ktx2: r.ktx2, ktx2Args: r.ktx2Args } : {}),
      };
    }
    const index = { version: ASSETS.indexVersion, generatedAt: new Date().toISOString(), assets };
    await mkdir(dirname(indexPath), { recursive: true });
    await writeFileAtomic(indexPath, `${JSON.stringify(index, null, 2)}\n`);
    await writeCredits(ASSET_DEFS);

    // Without the previous index a partial run cannot know which files the other assets use.
    if (!flags.noPrune && !(partial && !previousAssets)) {
      const keep = new Set();
      const addPaths = (map) => Object.values(map ?? {}).forEach((rel) => keep.add(rel));
      for (const entry of Object.values(assets)) {
        addPaths(entry.files);
        addPaths(entry.ktx2);
      }
      // Files of processed assets that are not usable yet (e.g. only the albedo failed) stay for the next run.
      for (const r of results) {
        addPaths(r.files);
        addPaths(r.ktx2);
      }
      pruned = { removed: 0, bytes: 0 };
      for (const dir of [ASSETS.dirs.textures, ASSETS.dirs.hdri])
        await pruneDir(join(PUBLIC_DIR, dir), keep, pruned);
    }
  }

  // --- summary --------------------------------------------------------------
  console.info('');
  let failures = 0;
  for (const r of results) {
    const ok = usable.includes(r);
    if (!ok) failures++;
    const ktx = Object.keys(r.ktx2).length > 0 ? `, ${Object.keys(r.ktx2).length}× ktx2` : '';
    const what = `${Object.keys(r.files).length} file(s): ${r.downloaded} downloaded (${fmtBytes(r.bytes)}), ${r.cached} cached${ktx}`;
    console.info(`  ${ok ? '✔' : '✘'} ${r.id.padEnd(18)} ${what}`);
    for (const w of r.warnings) console.warn(`      warning: ${w}`);
    for (const e of r.errors) console.warn(`      ${ok ? 'note' : 'error'}: ${e}`);
  }
  console.info('');
  if (!flags.dryRun)
    console.info(
      `  index: public/${ASSETS.indexFile} (${usable.length}/${results.length} available), CREDITS.md updated`,
    );
  if (pruned && pruned.removed > 0)
    console.info(`  pruned ${pruned.removed} unreferenced file(s) (${fmtBytes(pruned.bytes)})`);
  if (failures > 0) {
    console.warn(`  ${failures} asset(s) unavailable – the game uses procedural fallbacks for them.`);
    if (flags.strict) process.exit(1);
  }
}

/** Markdown table with padded columns (the layout Prettier produces, so reruns cause no churn). */
function markdownTable(header, rows) {
  const widths = header.map((h, c) => Math.max(3, h.length, ...rows.map((r) => r[c].length)));
  const line = (cells) => `| ${cells.map((cell, c) => cell.padEnd(widths[c])).join(' | ')} |`;
  return [line(header), line(widths.map((w) => '-'.repeat(w))), ...rows.map(line)];
}

async function writeCredits(assetDefs) {
  const lines = [
    CREDITS_BEGIN,
    '',
    ...markdownTable(
      ['Asset id', 'Asset', 'Author(s)', 'Source', 'License'],
      assetDefs.map((d) => [
        `\`${d.id}\``,
        d.credit.title,
        d.credit.author,
        d.credit.source,
        d.credit.license,
      ]),
    ),
    '',
    CREDITS_END,
  ];
  const section = lines.join('\n');
  let text;
  try {
    text = await readFile(CREDITS_FILE, 'utf8');
  } catch {
    text = `# Credits\n\n## Assets\n\n${CREDITS_BEGIN}\n${CREDITS_END}\n`;
  }
  const start = text.indexOf(CREDITS_BEGIN);
  const end = text.indexOf(CREDITS_END);
  const next =
    start >= 0 && end > start
      ? text.slice(0, start) + section + text.slice(end + CREDITS_END.length)
      : `${text.trimEnd()}\n\n## Assets\n\n${section}\n`;
  if (next !== text) await writeFileAtomic(CREDITS_FILE, next);
}

main().catch((err) => {
  console.warn(`fetch-assets: ${err?.stack ?? err}`);
  console.warn('Assets are optional – the game falls back to procedural textures/environment.');
  process.exit(flags.strict ? 1 : 0);
});
