/**
 * Berserker – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and
 * TYPES from '../enemyVisuals' (runtime cycle otherwise).
 *
 * Hunched humanoid brute, ~2.2 m with horns: dark maroon flesh laced with red veins (they flare when
 * it enrages – pose.glow), weathered bone plates on shoulders, forearms and knees, a glowing heart
 * behind a cage of ribs (the weakpoint, visible from the front), forward-swept horns over red eye
 * slits, and fused bone cleavers instead of hands. The arms are explicit L/R bones (no mirrored
 * bone): the cleave swings the right cleaver, the backhand the left, the crush both overhead.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const EMBER = [1, 0.12, 0.04] as const;

export const BERSERKER_VISUAL: EnemyVisualDef | null = {
  capacity: 16,
  zones: {
    flesh: {
      color: [0.075, 0.03, 0.025],
      color2: [0.13, 0.05, 0.04],
      tip: [0.04, 0.018, 0.016],
      tipAmount: 0.35,
      roughness: 0.5,
      metalness: 0,
      clearcoat: 0.5,
      emissive: EMBER,
      emissiveIntensity: 3.2,
      glow: 0,
      pulse: 0,
      veins: 0.8,
      bump: 0.9,
      cells: 0.2,
      scale: 2.2,
    },
    plates: {
      color: [0.2, 0.17, 0.13],
      color2: [0.3, 0.25, 0.19],
      tip: [0.05, 0.03, 0.03],
      tipAmount: 0.4,
      roughness: 0.45,
      metalness: 0,
      clearcoat: 0.3,
      emissive: EMBER,
      emissiveIntensity: 1.2,
      glow: 0,
      pulse: 0,
      veins: 0.1,
      bump: 1.1,
      cells: 0.5,
      scale: 2.5,
    },
    bone: BONE,
    eyes: {
      color: [0.05, 0.01, 0.005],
      color2: [0.05, 0.01, 0.005],
      tip: [0.05, 0.01, 0.005],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.2, 0.05],
      emissiveIntensity: 8,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
    heart: {
      color: [0.25, 0.03, 0.02],
      color2: [0.4, 0.06, 0.04],
      tip: [0.25, 0.03, 0.02],
      tipAmount: 0,
      roughness: 0.12,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.2, 0.06],
      emissiveIntensity: 7,
      glow: 1,
      pulse: 0.5,
      veins: 0.4,
      bump: 0.5,
      cells: 0.5,
      scale: 4,
    },
    maw: {
      color: [0.2, 0.02, 0.02],
      color2: [0.3, 0.05, 0.03],
      tip: [0.2, 0.02, 0.02],
      tipAmount: 0,
      roughness: 0.2,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.16, 0.05],
      emissiveIntensity: 5,
      glow: 0.6,
      pulse: 0.5,
      veins: 0,
      bump: 0.3,
      cells: 0,
      scale: 6,
    },
  },
  bones: [
    {
      name: 'pelvis',
      parent: null,
      pivot: [0, 1.05, -0.12],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -2.6 },
        { ch: 'rx', drive: 'emerge', amp: -20, window: [0.1, 1] },
        { ch: 'ty', drive: 'gait', amp: 0.035, amp2: 0.07, wave: 'abs', offset: HALF_PI },
        { ch: 'rz', drive: 'gait', amp: 4, amp2: 6 },
        { ch: 'ry', drive: 'gait', amp: 4, amp2: 6, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 8, window: [0.5, 1] },
        { ch: 'ty', drive: 'idle', amp: 0.01, freq: 0.3 },
        { ch: 'ry', drive: 'attack', attack: 'cleave', amp: 10, amp2: -12 },
        { ch: 'ry', drive: 'attack', attack: 'backhand', amp: -10, amp2: 12 },
        { ch: 'ty', drive: 'attack', attack: 'crush', amp: -0.18, amp2: 0.04 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: 12, amp2: 0 },
        { ch: 'ty', drive: 'attack', attack: 'lunge', amp: -0.08, amp2: -0.12 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: 14, amp2: 10 },
        { ch: 'ty', drive: 'attack', attack: 'roar', amp: -0.02, amp2: -0.06 },
        { ch: 'rx', drive: 'stagger', amp: -6 },
        { ch: 'tz', drive: 'stagger', amp: -0.08 },
        { ch: 'rz', drive: 'stagger', amp: 2, freq: 5 },
        { ch: 'ty', drive: 'death', amp: -0.6, window: [0.1, 0.6] },
        { ch: 'rx', drive: 'death', amp: 60, window: [0.3, 0.95] },
        { ch: 'rz', drive: 'death', amp: 12, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'chest',
      parent: 'pelvis',
      pivot: [0, 1.25, -0.1],
      motions: [
        { ch: 'ry', drive: 'gait', amp: -5, amp2: -8, offset: HALF_PI },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 4, freq: 2, offset: 1 },
        { ch: 'rx', drive: 'loco', amp: 10, window: [0.5, 1] },
        { ch: 's', drive: 'idle', amp: 0.02, freq: 0.35 },
        { ch: 'rx', drive: 'idle', amp: 1.5, freq: 0.35 },
        { ch: 'ry', drive: 'attack', attack: 'cleave', amp: 30, amp2: -35 },
        { ch: 'rz', drive: 'attack', attack: 'cleave', amp: -5, amp2: 5 },
        { ch: 'ry', drive: 'attack', attack: 'backhand', amp: -30, amp2: 35 },
        { ch: 'rz', drive: 'attack', attack: 'backhand', amp: 5, amp2: -5 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: 28, amp2: -18 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: 25, amp2: 15 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: 8, amp2: -25 },
        { ch: 's', drive: 'attack', attack: 'roar', amp: 0.05, amp2: 0.03 },
        { ch: 'rx', drive: 'stagger', amp: -14 },
        { ch: 'rz', drive: 'stagger', amp: 4, freq: 5 },
        { ch: 'rx', drive: 'death', amp: 25, window: [0.3, 1] },
      ],
    },
    {
      name: 'heart',
      parent: 'chest',
      pivot: [0, 1.5, 0.24],
      motions: [
        { ch: 's', drive: 'idle', amp: 0.08, freq: 1.2 },
        { ch: 's', drive: 'attack', attack: 'roar', amp: 0.25, amp2: 0.15 },
        { ch: 's', drive: 'death', amp: -0.4, window: [0.2, 0.9] },
      ],
    },
    {
      name: 'head',
      parent: 'chest',
      pivot: [0, 1.8, 0.2],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.7 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.6 },
        { ch: 'ry', drive: 'idle', amp: 4, freq: 0.2 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: -10, amp2: -35 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: 12, amp2: -10 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: 18, amp2: 10 },
        { ch: 'rx', drive: 'stagger', amp: -18 },
        { ch: 'ry', drive: 'stagger', amp: 6, freq: 4 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.2, 0.8] },
        { ch: 'ry', drive: 'death', amp: 25, window: [0.4, 1] },
      ],
    },
    {
      name: 'jaw',
      parent: 'head',
      pivot: [0, 1.76, 0.3],
      motions: [
        { ch: 'rx', drive: 'rest', amp: 4 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.5 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: 45, amp2: 30 },
        { ch: 'rx', drive: 'attack', attack: 'cleave', amp: 18, amp2: 6 },
        { ch: 'rx', drive: 'attack', attack: 'backhand', amp: 18, amp2: 6 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: 25, amp2: 10 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: 20, amp2: 12 },
        { ch: 'rx', drive: 'stagger', amp: 20 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.2, 0.7] },
      ],
    },
    // Left arm (+X): the backhand.
    {
      name: 'arm_L',
      parent: 'chest',
      pivot: [0.46, 1.74, 0],
      motions: [
        { ch: 'rx', drive: 'gait', amp: -18, amp2: -28 },
        { ch: 'rz', drive: 'rest', amp: 10 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.3 },
        { ch: 'rz', drive: 'idle', amp: 2, freq: 0.2 },
        { ch: 'rx', drive: 'attack', attack: 'cleave', amp: -10, amp2: 20 },
        { ch: 'rx', drive: 'attack', attack: 'backhand', amp: -80, amp2: -80 },
        { ch: 'ry', drive: 'attack', attack: 'backhand', amp: -45, amp2: 70 },
        { ch: 'rz', drive: 'attack', attack: 'backhand', amp: 0, amp2: 10 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: -35, amp2: -165 },
        { ch: 'rz', drive: 'attack', attack: 'crush', amp: -4, amp2: 8 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: -70, amp2: 35 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: -40, amp2: -30 },
        { ch: 'rz', drive: 'attack', attack: 'roar', amp: 60, amp2: 45 },
        { ch: 'rz', drive: 'stagger', amp: 12 },
        { ch: 'rx', drive: 'stagger', amp: 12 },
        { ch: 'rz', drive: 'death', amp: 25, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: -35, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'forearm_L',
      parent: 'arm_L',
      pivot: [0.58, 1.28, 0.1],
      motions: [
        { ch: 'rx', drive: 'gait', amp: -12, amp2: -18, wave: 'pos', offset: HALF_PI },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.33 },
        { ch: 'rx', drive: 'attack', attack: 'backhand', amp: -5, amp2: -50 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: -10, amp2: -50 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: -10, amp2: -40 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: -60, amp2: -40 },
        { ch: 'rx', drive: 'death', amp: -40, window: [0.3, 0.9] },
      ],
    },
    // Right arm (−X): the cleave.
    {
      name: 'arm_R',
      parent: 'chest',
      pivot: [-0.46, 1.74, 0],
      motions: [
        { ch: 'rx', drive: 'gait', amp: -18, amp2: -28, offset: PI },
        { ch: 'rz', drive: 'rest', amp: -10 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.3, offset: PI },
        { ch: 'rz', drive: 'idle', amp: -2, freq: 0.2 },
        { ch: 'rx', drive: 'attack', attack: 'backhand', amp: -10, amp2: 20 },
        { ch: 'rx', drive: 'attack', attack: 'cleave', amp: -80, amp2: -80 },
        { ch: 'ry', drive: 'attack', attack: 'cleave', amp: 45, amp2: -70 },
        { ch: 'rz', drive: 'attack', attack: 'cleave', amp: 0, amp2: -10 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: -35, amp2: -165 },
        { ch: 'rz', drive: 'attack', attack: 'crush', amp: 4, amp2: -8 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: -70, amp2: 35 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: -40, amp2: -30 },
        { ch: 'rz', drive: 'attack', attack: 'roar', amp: -60, amp2: -45 },
        { ch: 'rz', drive: 'stagger', amp: -12 },
        { ch: 'rx', drive: 'stagger', amp: 12 },
        { ch: 'rz', drive: 'death', amp: -25, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: -35, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'forearm_R',
      parent: 'arm_R',
      pivot: [-0.58, 1.28, 0.1],
      motions: [
        { ch: 'rx', drive: 'gait', amp: -12, amp2: -18, wave: 'pos', offset: HALF_PI + PI },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.33, offset: PI },
        { ch: 'rx', drive: 'attack', attack: 'cleave', amp: -5, amp2: -50 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: -10, amp2: -50 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: -10, amp2: -40 },
        { ch: 'rx', drive: 'attack', attack: 'roar', amp: -60, amp2: -40 },
        { ch: 'rx', drive: 'death', amp: -40, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'thigh_L',
      parent: 'pelvis',
      pivot: [0.2, 1.02, -0.12],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 20, amp2: 30 },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: -10, amp2: -22 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: -16, amp2: 0 },
        { ch: 'rx', drive: 'stagger', amp: -6 },
        { ch: 'rx', drive: 'death', amp: -60, window: [0.1, 0.6] },
      ],
    },
    {
      name: 'shin_L',
      parent: 'thigh_L',
      pivot: [0.24, 0.56, 0.02],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 24, amp2: 34, wave: 'pos', offset: -HALF_PI },
        { ch: 'rx', drive: 'attack', attack: 'lunge', amp: 10, amp2: 26 },
        { ch: 'rx', drive: 'attack', attack: 'crush', amp: 22, amp2: 0 },
        { ch: 'rx', drive: 'death', amp: 80, window: [0.1, 0.6] },
      ],
    },
  ],
  parts: [
    // Torso masses.
    {
      shape: 'ellipsoid',
      bone: 'pelvis',
      zone: 'flesh',
      center: [0, 1.05, -0.12],
      radii: [0.26, 0.18, 0.2],
      lumpy: 0.015,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'flesh',
      center: [0, 1.3, -0.05],
      radii: [0.3, 0.24, 0.23],
      lumpy: 0.015,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'flesh',
      center: [0, 1.58, 0.01],
      radii: [0.44, 0.28, 0.28],
      lumpy: 0.02,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'flesh',
      center: [0, 1.78, -0.1],
      radii: [0.36, 0.17, 0.24],
      lumpy: 0.018,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'flesh',
      center: [0.19, 1.66, 0.17],
      radii: [0.18, 0.11, 0.1],
      rot: [0, 12, 0],
      lumpy: 0.01,
      mirror: true,
    },
    // Heart behind a cage of ribs (weakpoint).
    {
      shape: 'ellipsoid',
      bone: 'heart',
      zone: 'heart',
      center: [0, 1.5, 0.25],
      radii: [0.1, 0.11, 0.08],
      lumpy: 0.008,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.24, 1.44, 0.16],
        [0.12, 1.41, 0.28],
        [0.02, 1.4, 0.31],
      ],
      radius: 0.02,
      radiusB: 0.013,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.26, 1.53, 0.17],
        [0.13, 1.51, 0.3],
        [0.03, 1.5, 0.33],
      ],
      radius: 0.021,
      radiusB: 0.013,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.25, 1.61, 0.19],
        [0.12, 1.59, 0.29],
        [0.02, 1.58, 0.31],
      ],
      radius: 0.02,
      radiusB: 0.013,
      mirror: true,
    },
    // Spined hump.
    {
      shape: 'spike',
      bone: 'chest',
      zone: 'bone',
      a: [0.16, 1.86, -0.14],
      b: [0.27, 2.12, -0.36],
      radius: 0.05,
      curve: [0.02, 0.04, 0],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'chest',
      zone: 'bone',
      a: [0, 1.9, -0.14],
      b: [0, 2.18, -0.34],
      radius: 0.055,
      curve: [0, 0.05, 0],
    },
    {
      shape: 'spike',
      bone: 'chest',
      zone: 'bone',
      a: [0.1, 1.66, -0.3],
      b: [0.16, 1.82, -0.52],
      radius: 0.04,
      curve: [0.01, 0.03, 0],
      mirror: true,
    },
    // Shoulder pauldrons.
    {
      shape: 'ellipsoid',
      bone: 'arm_L',
      zone: 'plates',
      center: [0.5, 1.86, 0],
      radii: [0.24, 0.05, 0.26],
      rot: [0, 0, -25],
      bend: -0.1,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'arm_L',
      zone: 'bone',
      a: [0.52, 1.9, 0],
      b: [0.62, 2.12, -0.1],
      radius: 0.045,
      curve: [0.01, 0.02, 0],
      mirror: true,
    },
    // Head: sunk between the shoulders, brow plate, eye slits, horns, tusked jaw.
    { shape: 'ellipsoid', bone: 'head', zone: 'flesh', center: [0, 1.84, 0.3], radii: [0.13, 0.13, 0.14] },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'plates',
      center: [0, 1.9, 0.4],
      radii: [0.14, 0.03, 0.08],
      rot: [70, 0, 0],
      bend: -0.04,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.055, 1.86, 0.425],
      radii: [0.03, 0.01, 0.015],
      rot: [0, 0, -12],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.1, 1.92, 0.3],
      b: [0.25, 2.1, 0.42],
      radius: 0.042,
      curve: [0.04, 0.02, -0.06],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.08, 1.95, 0.22],
      b: [0.15, 2.03, 0.02],
      radius: 0.03,
      curve: [0.01, 0.02, 0],
      mirror: true,
    },
    { shape: 'ellipsoid', bone: 'jaw', zone: 'maw', center: [0, 1.77, 0.38], radii: [0.07, 0.03, 0.07] },
    { shape: 'ellipsoid', bone: 'jaw', zone: 'flesh', center: [0, 1.74, 0.38], radii: [0.11, 0.045, 0.1] },
    {
      shape: 'spike',
      bone: 'jaw',
      zone: 'bone',
      a: [0.07, 1.75, 0.44],
      b: [0.1, 1.87, 0.48],
      radius: 0.02,
      curve: [0.01, 0, 0.01],
      mirror: true,
    },
    // Arms: massive, bone plated forearms ending in fused cleavers.
    {
      shape: 'capsule',
      bone: 'arm_L',
      zone: 'flesh',
      a: [0.46, 1.74, 0],
      b: [0.58, 1.28, 0.1],
      radius: 0.14,
      radiusB: 0.115,
      mirror: true,
      lumpy: 0.012,
    },
    {
      shape: 'capsule',
      bone: 'forearm_L',
      zone: 'flesh',
      a: [0.58, 1.28, 0.1],
      b: [0.6, 0.86, 0.28],
      radius: 0.12,
      radiusB: 0.095,
      mirror: true,
      lumpy: 0.01,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'plates',
      center: [0.67, 1.07, 0.2],
      radii: [0.22, 0.04, 0.12],
      rot: [-23, 0, -90],
      bend: -0.06,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'plates',
      center: [0.6, 0.84, 0.3],
      radii: [0.09, 0.08, 0.1],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.6, 0.86, 0.3],
      b: [0.64, 0.2, 0.72],
      radius: 0.07,
      curve: [0.02, 0, 0.12],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'bone',
      center: [0.62, 0.56, 0.5],
      radii: [0.02, 0.3, 0.1],
      rot: [-33, 0, 0],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.58, 0.84, 0.28],
      b: [0.52, 0.46, 0.55],
      radius: 0.04,
      curve: [0, 0, 0.05],
      mirror: true,
    },
    // Legs.
    {
      shape: 'capsule',
      bone: 'thigh_L',
      zone: 'flesh',
      a: [0.2, 1.02, -0.12],
      b: [0.24, 0.56, 0.02],
      radius: 0.15,
      radiusB: 0.12,
      mirror: true,
      lumpy: 0.012,
    },
    {
      shape: 'ellipsoid',
      bone: 'shin_L',
      zone: 'plates',
      center: [0.25, 0.58, 0.12],
      radii: [0.1, 0.03, 0.09],
      rot: [70, 0, 0],
      bend: -0.04,
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'shin_L',
      zone: 'flesh',
      a: [0.24, 0.56, 0.02],
      b: [0.25, 0.1, -0.06],
      radius: 0.11,
      radiusB: 0.09,
      mirror: true,
      lumpy: 0.01,
    },
    {
      shape: 'ellipsoid',
      bone: 'shin_L',
      zone: 'plates',
      center: [0.25, 0.07, 0.06],
      radii: [0.11, 0.07, 0.18],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shin_L',
      zone: 'bone',
      a: [0.29, 0.04, 0.18],
      b: [0.32, 0, 0.3],
      radius: 0.028,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shin_L',
      zone: 'bone',
      a: [0.21, 0.04, 0.18],
      b: [0.2, 0, 0.3],
      radius: 0.028,
      mirror: true,
    },
  ],
  attacks: [
    { id: 'cleave', windup: 0.45, strike: 0.6, glow: 1.2 },
    { id: 'backhand', windup: 0.4, strike: 0.58, glow: 1.2 },
    { id: 'crush', windup: 0.3, strike: 0.42, glow: 2 },
    { id: 'lunge', windup: 0.25, strike: 0.8, glow: 1.4 },
    { id: 'roar', windup: 0.4, strike: 0.6, glow: 2.5 },
  ],
  hitboxes: [
    { bone: 'heart', shape: 'sphere', zone: 'weakpoint', a: [0, 1.5, 0.25], radius: 0.12 },
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 1.85, 0.32], radius: 0.16 },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'shield',
      a: [0.67, 1.22, 0.14],
      b: [0.67, 0.92, 0.27],
      radius: 0.12,
      mirror: true,
    },
    { bone: 'arm_L', shape: 'sphere', zone: 'shield', a: [0.52, 1.86, 0], radius: 0.19, mirror: true },
    { bone: 'chest', shape: 'capsule', zone: 'body', a: [0, 1.26, -0.06], b: [0, 1.72, -0.03], radius: 0.36 },
    {
      bone: 'pelvis',
      shape: 'capsule',
      zone: 'body',
      a: [-0.16, 1.05, -0.12],
      b: [0.16, 1.05, -0.12],
      radius: 0.22,
    },
    {
      bone: 'arm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.46, 1.74, 0],
      b: [0.58, 1.28, 0.1],
      radius: 0.14,
      mirror: true,
    },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.58, 1.28, 0.1],
      b: [0.62, 0.35, 0.62],
      radius: 0.12,
      mirror: true,
    },
    {
      bone: 'thigh_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.2, 1.02, -0.12],
      b: [0.24, 0.56, 0.02],
      radius: 0.15,
      mirror: true,
    },
    {
      bone: 'shin_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.24, 0.56, 0.02],
      b: [0.25, 0.08, 0],
      radius: 0.12,
      mirror: true,
    },
  ],
  sockets: {
    head: [{ bone: 'head', point: [0, 1.86, 0.34] }],
    chest: [{ bone: 'chest', point: [0, 1.6, 0.2] }],
    core: [{ bone: 'chest', point: [0, 1.45, 0] }],
    heart: [{ bone: 'heart', point: [0, 1.5, 0.25] }],
    blades: [
      { bone: 'forearm_L', point: [0.63, 0.3, 0.68] },
      { bone: 'forearm_R', point: [-0.63, 0.3, 0.68] },
    ],
    bladeL: [{ bone: 'forearm_L', point: [0.63, 0.3, 0.68] }],
    bladeR: [{ bone: 'forearm_R', point: [-0.63, 0.3, 0.68] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 45, pitchMaxDeg: 30 },
  // Overhead crush and the cleave sweep reach well past the rest bounds.
  cullMargin: 1.4,
  dissolve: { edgeColor: [1, 0.2, 0.06], edgeIntensity: 12, edgeWidth: 0.07, noiseScale: 6 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 1.1 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 1.15,
    death: 'enemy.death',
    deathScale: 1.35,
    deathSocket: 'core',
  },
};
