/**
 * Explodierer – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and
 * TYPES from '../enemyVisuals' (runtime cycle otherwise).
 *
 * Squat, waddling creature hugging an enormous amber bile sac to its belly: the sac glows through a
 * membrane of cells and dark vessels, blisters and fuse bulbs on its back burn yellow-hot. The sac
 * is the weakpoint and always faces the player it runs at. Warning pulse (pose.glow) blinks the
 * whole emission faster as it closes in; the fuse = arms thrown wide, head back screaming, sac
 * swelling to bursting (telegraph glow + amber light).
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const AMBER = [1, 0.52, 0.1] as const;

export const EXPLODER_VISUAL: EnemyVisualDef | null = {
  capacity: 24,
  zones: {
    sac: {
      color: [0.3, 0.14, 0.02],
      color2: [0.45, 0.24, 0.03],
      tip: [0.3, 0.14, 0.02],
      tipAmount: 0,
      roughness: 0.12,
      metalness: 0,
      clearcoat: 1,
      emissive: AMBER,
      emissiveIntensity: 3.2,
      glow: 0.85,
      pulse: 0.55,
      veins: 0.5,
      bump: 0.5,
      cells: 0.6,
      scale: 3,
    },
    blister: {
      color: [0.5, 0.35, 0.08],
      color2: [0.6, 0.45, 0.1],
      tip: [0.5, 0.35, 0.08],
      tipAmount: 0,
      roughness: 0.1,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.75, 0.25],
      emissiveIntensity: 6,
      glow: 1,
      pulse: 0.4,
      veins: 0,
      bump: 0.2,
      cells: 0.3,
      scale: 8,
    },
    flesh: {
      color: [0.12, 0.1, 0.07],
      color2: [0.2, 0.16, 0.1],
      tip: [0.06, 0.05, 0.04],
      tipAmount: 0.4,
      roughness: 0.45,
      metalness: 0,
      clearcoat: 0.7,
      emissive: AMBER,
      emissiveIntensity: 2.4,
      glow: 0,
      pulse: 0,
      veins: 0.55,
      bump: 0.8,
      cells: 0.2,
      scale: 2.6,
    },
    chitin: {
      color: [0.03, 0.025, 0.02],
      color2: [0.07, 0.05, 0.035],
      tip: [0.18, 0.14, 0.1],
      tipAmount: 0.3,
      roughness: 0.3,
      metalness: 0.1,
      clearcoat: 0.9,
      emissive: AMBER,
      emissiveIntensity: 1.4,
      glow: 0,
      pulse: 0,
      veins: 0.1,
      bump: 1,
      cells: 0.7,
      scale: 3,
    },
    bone: BONE,
    eyes: {
      color: [0.05, 0.03, 0.005],
      color2: [0.05, 0.03, 0.005],
      tip: [0.05, 0.03, 0.005],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.6, 0.15],
      emissiveIntensity: 7,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
  },
  bones: [
    {
      name: 'pelvis',
      parent: null,
      pivot: [0, 0.72, -0.12],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -1.8 },
        { ch: 'rx', drive: 'emerge', amp: -20, window: [0.1, 1] },
        { ch: 'rz', drive: 'gait', amp: 8, amp2: 11 },
        { ch: 'ty', drive: 'gait', amp: 0.03, amp2: 0.05, wave: 'abs', offset: HALF_PI },
        { ch: 'ry', drive: 'gait', amp: 5, amp2: 7, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 6, window: [0.5, 1] },
        { ch: 'ty', drive: 'idle', amp: 0.006, freq: 0.5 },
        { ch: 'ty', drive: 'attack', attack: 'fuse', amp: -0.12, amp2: -0.08 },
        { ch: 'rx', drive: 'attack', attack: 'ram', amp: 10, amp2: -6 },
        { ch: 'rx', drive: 'stagger', amp: -8 },
        { ch: 'tz', drive: 'stagger', amp: -0.06 },
        { ch: 'rz', drive: 'stagger', amp: 4, freq: 6 },
        { ch: 'ty', drive: 'death', amp: -0.35, window: [0, 0.5] },
        { ch: 'rx', drive: 'death', amp: 50, window: [0.2, 0.9] },
        { ch: 'rz', drive: 'death', amp: 20, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'torso',
      parent: 'pelvis',
      pivot: [0, 0.82, -0.12],
      motions: [
        { ch: 'rz', drive: 'gait', amp: -4, amp2: -6 },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 3, freq: 2 },
        { ch: 'rx', drive: 'idle', amp: 2, freq: 0.4 },
        { ch: 's', drive: 'idle', amp: 0.02, freq: 0.5 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: -24, amp2: -20 },
        { ch: 'rx', drive: 'attack', attack: 'ram', amp: 26, amp2: -10 },
        { ch: 'rx', drive: 'stagger', amp: -12 },
        { ch: 'rx', drive: 'death', amp: 20, window: [0.3, 1] },
      ],
    },
    {
      name: 'sac',
      parent: 'torso',
      pivot: [0, 0.9, 0.12],
      motions: [
        { ch: 's', drive: 'idle', amp: 0.05, freq: 0.8 },
        { ch: 'ty', drive: 'gait', amp: -0.02, amp2: -0.035, freq: 2 },
        { ch: 'rx', drive: 'gait', amp: 3, amp2: 5, offset: HALF_PI },
        { ch: 'rz', drive: 'gait', amp: 3, amp2: 4 },
        { ch: 's', drive: 'attack', attack: 'fuse', amp: 0.45, amp2: 0.32 },
        { ch: 'tz', drive: 'attack', attack: 'ram', amp: 0.08, amp2: -0.03 },
        { ch: 's', drive: 'stagger', amp: 0.1, freq: 8 },
        { ch: 's', drive: 'death', amp: -0.6, window: [0.15, 0.8] },
      ],
    },
    {
      name: 'head',
      parent: 'torso',
      pivot: [0, 1.3, 0.12],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.8 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.7 },
        { ch: 'ry', drive: 'idle', amp: 5, freq: 0.3 },
        { ch: 'rz', drive: 'idle', amp: 4, freq: 0.23, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: -35, amp2: -30 },
        { ch: 'rx', drive: 'stagger', amp: -20 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'jaw',
      parent: 'head',
      pivot: [0, 1.28, 0.22],
      motions: [
        { ch: 'rx', drive: 'rest', amp: 6 },
        { ch: 'rx', drive: 'idle', amp: 5, freq: 0.9 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: 50, amp2: 40 },
        { ch: 'rx', drive: 'attack', attack: 'ram', amp: 20, amp2: 6 },
        { ch: 'rx', drive: 'stagger', amp: 25 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.2, 0.7] },
      ],
    },
    {
      name: 'arm_L',
      parent: 'torso',
      pivot: [0.26, 1.18, 0.02],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: -10, amp2: -14 },
        { ch: 'rz', drive: 'rest', amp: 4 },
        { ch: 'rx', drive: 'idle', amp: 4, freq: 0.4 },
        { ch: 'rz', drive: 'idle', amp: 3, freq: 0.3 },
        { ch: 'rz', drive: 'attack', attack: 'fuse', amp: 55, amp2: 40 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: -40, amp2: -30 },
        { ch: 'rx', drive: 'attack', attack: 'ram', amp: -20, amp2: 10 },
        { ch: 'rz', drive: 'stagger', amp: 15 },
        { ch: 'rz', drive: 'death', amp: 25, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: -30, window: [0.3, 1] },
      ],
    },
    {
      name: 'forearm_L',
      parent: 'arm_L',
      pivot: [0.42, 0.94, 0.2],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'idle', amp: 6, freq: 0.45, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: -40, amp2: -30 },
        { ch: 'rx', drive: 'death', amp: -30, window: [0.3, 1] },
      ],
    },
    {
      name: 'thigh_L',
      parent: 'pelvis',
      pivot: [0.16, 0.7, -0.14],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 24, amp2: 32 },
        { ch: 'rz', drive: 'rest', amp: 6 },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: -12, amp2: -12 },
        { ch: 'rx', drive: 'death', amp: -50, window: [0.1, 0.6] },
      ],
    },
    {
      name: 'shin_L',
      parent: 'thigh_L',
      pivot: [0.22, 0.38, -0.04],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 26, amp2: 34, wave: 'pos', offset: -HALF_PI },
        { ch: 'rx', drive: 'attack', attack: 'fuse', amp: 18, amp2: 18 },
        { ch: 'rx', drive: 'death', amp: 70, window: [0.1, 0.6] },
      ],
    },
  ],
  parts: [
    // The bile sac (weakpoint) with blisters and dark vessels.
    {
      shape: 'ellipsoid',
      bone: 'sac',
      zone: 'sac',
      center: [0, 0.92, 0.3],
      radii: [0.4, 0.4, 0.38],
      lumpy: 0.03,
    },
    {
      shape: 'ellipsoid',
      bone: 'sac',
      zone: 'blister',
      center: [0.19, 1.11, 0.57],
      radii: [0.07, 0.065, 0.07],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'sac',
      zone: 'blister',
      center: [0.28, 0.84, 0.57],
      radii: [0.06, 0.055, 0.06],
      mirror: true,
    },
    { shape: 'ellipsoid', bone: 'sac', zone: 'blister', center: [0, 0.96, 0.7], radii: [0.055, 0.05, 0.05] },
    {
      shape: 'ellipsoid',
      bone: 'sac',
      zone: 'blister',
      center: [0.12, 0.68, 0.6],
      radii: [0.05, 0.045, 0.05],
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'sac',
      zone: 'flesh',
      points: [
        [0.08, 1.28, 0.2],
        [0.19, 1.24, 0.47],
        [0.2, 1, 0.66],
        [0.15, 0.72, 0.64],
        [0.06, 0.55, 0.46],
      ],
      radius: 0.018,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'sac',
      zone: 'flesh',
      points: [
        [0, 1.3, 0.28],
        [0, 1.22, 0.58],
        [0, 0.95, 0.71],
        [0, 0.68, 0.64],
      ],
      radius: 0.02,
      radiusB: 0.01,
    },
    // Hunched body behind the sac, back plates, glowing fuse bulbs.
    {
      shape: 'ellipsoid',
      bone: 'torso',
      zone: 'flesh',
      center: [0, 1.08, -0.1],
      radii: [0.27, 0.3, 0.24],
      lumpy: 0.02,
    },
    {
      shape: 'ellipsoid',
      bone: 'pelvis',
      zone: 'flesh',
      center: [0, 0.74, -0.14],
      radii: [0.22, 0.14, 0.18],
      lumpy: 0.012,
    },
    {
      shape: 'ellipsoid',
      bone: 'torso',
      zone: 'chitin',
      center: [0, 1.22, -0.22],
      radii: [0.22, 0.04, 0.15],
      rot: [-50, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'ellipsoid',
      bone: 'torso',
      zone: 'chitin',
      center: [0, 1.02, -0.3],
      radii: [0.2, 0.04, 0.13],
      rot: [-75, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'spike',
      bone: 'torso',
      zone: 'bone',
      a: [0.1, 1.25, -0.2],
      b: [0.16, 1.42, -0.3],
      radius: 0.03,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'torso',
      zone: 'blister',
      center: [0.16, 1.42, -0.3],
      radii: [0.035, 0.035, 0.035],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'torso',
      zone: 'bone',
      a: [0, 1.3, -0.16],
      b: [0, 1.5, -0.24],
      radius: 0.032,
    },
    {
      shape: 'ellipsoid',
      bone: 'torso',
      zone: 'blister',
      center: [0, 1.5, -0.24],
      radii: [0.04, 0.04, 0.04],
    },
    // Small sunken head, eyes, screaming jaw.
    { shape: 'ellipsoid', bone: 'head', zone: 'flesh', center: [0, 1.34, 0.2], radii: [0.11, 0.09, 0.12] },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.4, 0.2],
      radii: [0.1, 0.03, 0.11],
      rot: [-10, 0, 0],
      bend: -0.03,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.045, 1.37, 0.3],
      radii: [0.016, 0.014, 0.016],
      mirror: true,
    },
    { shape: 'ellipsoid', bone: 'jaw', zone: 'flesh', center: [0, 1.28, 0.26], radii: [0.08, 0.035, 0.09] },
    {
      shape: 'spike',
      bone: 'jaw',
      zone: 'bone',
      a: [0.04, 1.29, 0.32],
      b: [0.04, 1.33, 0.33],
      radius: 0.009,
      mirror: true,
    },
    // Thin arms hugging the sac.
    {
      shape: 'capsule',
      bone: 'arm_L',
      zone: 'flesh',
      a: [0.26, 1.18, 0.02],
      b: [0.42, 0.94, 0.2],
      radius: 0.05,
      radiusB: 0.04,
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'forearm_L',
      zone: 'flesh',
      a: [0.42, 0.94, 0.2],
      b: [0.3, 0.78, 0.5],
      radius: 0.04,
      radiusB: 0.03,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.3, 0.78, 0.5],
      b: [0.18, 0.74, 0.63],
      radius: 0.014,
      curve: [0.02, 0, 0],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.3, 0.77, 0.5],
      b: [0.22, 0.65, 0.6],
      radius: 0.013,
      curve: [0.02, 0, 0],
      mirror: true,
    },
    // Stubby legs.
    {
      shape: 'capsule',
      bone: 'thigh_L',
      zone: 'flesh',
      a: [0.16, 0.7, -0.14],
      b: [0.22, 0.38, -0.04],
      radius: 0.1,
      radiusB: 0.08,
      mirror: true,
      lumpy: 0.01,
    },
    {
      shape: 'capsule',
      bone: 'shin_L',
      zone: 'chitin',
      a: [0.22, 0.38, -0.04],
      b: [0.22, 0.06, -0.1],
      radius: 0.07,
      radiusB: 0.06,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'shin_L',
      zone: 'chitin',
      center: [0.22, 0.05, -0.02],
      radii: [0.08, 0.05, 0.13],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shin_L',
      zone: 'bone',
      a: [0.25, 0.04, 0.08],
      b: [0.28, 0, 0.18],
      radius: 0.022,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shin_L',
      zone: 'bone',
      a: [0.19, 0.04, 0.08],
      b: [0.17, 0, 0.18],
      radius: 0.022,
      mirror: true,
    },
  ],
  attacks: [
    { id: 'fuse', windup: 0.82, strike: 0.9, glow: 3.5 },
    { id: 'ram', windup: 0.4, strike: 0.55, glow: 0.6 },
  ],
  hitboxes: [
    { bone: 'sac', shape: 'sphere', zone: 'weakpoint', a: [0, 0.92, 0.3], radius: 0.42 },
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 1.34, 0.22], radius: 0.12 },
    { bone: 'torso', shape: 'capsule', zone: 'body', a: [0, 0.86, -0.13], b: [0, 1.22, -0.1], radius: 0.27 },
    {
      bone: 'arm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.26, 1.18, 0.02],
      b: [0.42, 0.94, 0.2],
      radius: 0.06,
      mirror: true,
    },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.42, 0.94, 0.2],
      b: [0.3, 0.78, 0.5],
      radius: 0.05,
      mirror: true,
    },
    {
      bone: 'thigh_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.16, 0.7, -0.14],
      b: [0.22, 0.38, -0.04],
      radius: 0.1,
      mirror: true,
    },
    {
      bone: 'shin_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.22, 0.38, -0.04],
      b: [0.22, 0.06, -0.08],
      radius: 0.08,
      mirror: true,
    },
  ],
  sockets: {
    sac: [{ bone: 'sac', point: [0, 0.92, 0.34] }],
    head: [{ bone: 'head', point: [0, 1.34, 0.22] }],
    chest: [{ bone: 'torso', point: [0, 1.02, 0.18] }],
    core: [{ bone: 'torso', point: [0, 1, -0.05] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 60, pitchMaxDeg: 40 },
  cullMargin: 0.8,
  dissolve: { edgeColor: [1, 0.55, 0.1], edgeIntensity: 12, edgeWidth: 0.08, noiseScale: 7 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 0.95 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 0.9,
    death: 'enemy.death',
    deathScale: 0.7,
    deathSocket: 'sac',
  },
};
