/**
 * Heiler – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and TYPES
 * from '../enemyVisuals' (runtime cycle otherwise).
 *
 * A gaunt bio-priest hovering ~0.2 m above the floor: a pale, green-veined torso hunched under a
 * dark chitin cowl, a bone mask with three glowing eyes, long thin arms with needle fingers, a
 * membrane mantle down the back and a swollen sac with dangling tendrils instead of legs. Its
 * lantern – a glowing green bulb on a stalk that arches over the head like an anglerfish lure – is
 * where the healing tether leaves (socket 'lantern') and its weakpoint. Heal: rises, spreads its
 * arms, the stalk bends forward and the lantern swells (held for the channel); lash: a one-armed
 * whip; death: the hover fails and it crumples onto the floor.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const GREEN: readonly [number, number, number] = [0.32, 1, 0.38];

export const HEALER_VISUAL: EnemyVisualDef | null = {
  // Up to a few per late wave + the dying.
  capacity: 12,
  zones: {
    flesh: {
      color: [0.15, 0.16, 0.13],
      color2: [0.25, 0.26, 0.2],
      tip: [0.05, 0.06, 0.045],
      tipAmount: 0.45,
      roughness: 0.46,
      metalness: 0,
      clearcoat: 0.6,
      emissive: GREEN,
      emissiveIntensity: 2.8,
      glow: 0,
      pulse: 0,
      veins: 0.7,
      bump: 0.6,
      cells: 0.2,
      scale: 2.6,
    },
    chitin: {
      color: [0.025, 0.03, 0.028],
      color2: [0.06, 0.07, 0.055],
      tip: [0.16, 0.17, 0.12],
      tipAmount: 0.3,
      roughness: 0.3,
      metalness: 0.12,
      clearcoat: 1,
      emissive: GREEN,
      emissiveIntensity: 1.6,
      glow: 0,
      pulse: 0,
      veins: 0.14,
      bump: 1,
      cells: 0.7,
      scale: 3,
    },
    membrane: {
      color: [0.04, 0.05, 0.04],
      color2: [0.09, 0.1, 0.07],
      tip: [0.02, 0.025, 0.02],
      tipAmount: 0.6,
      roughness: 0.5,
      metalness: 0,
      clearcoat: 0.45,
      emissive: GREEN,
      emissiveIntensity: 2.4,
      glow: 0,
      pulse: 0,
      veins: 0.55,
      bump: 0.4,
      cells: 0.35,
      scale: 2.2,
    },
    bone: BONE,
    lantern: {
      color: [0.08, 0.28, 0.08],
      color2: [0.16, 0.42, 0.12],
      tip: [0.08, 0.28, 0.08],
      tipAmount: 0,
      roughness: 0.1,
      metalness: 0,
      clearcoat: 1,
      emissive: GREEN,
      emissiveIntensity: 5.5,
      glow: 1,
      pulse: 0.4,
      veins: 0.5,
      bump: 0.45,
      cells: 0.55,
      scale: 3.6,
    },
    eyes: {
      color: [0.02, 0.05, 0.02],
      color2: [0.02, 0.05, 0.02],
      tip: [0.02, 0.05, 0.02],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [0.6, 1, 0.55],
      emissiveIntensity: 8,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
  },
  bones: [
    {
      name: 'body',
      parent: null,
      pivot: [0, 1.15, 0],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -2.6 },
        { ch: 'rx', drive: 'emerge', amp: -22, window: [0.1, 1] },
        // Hover: a slow bob and sway, a glide bob while moving, leaning into a flight.
        { ch: 'ty', drive: 'idle', amp: 0.05, freq: 0.5 },
        { ch: 'rz', drive: 'idle', amp: 2, freq: 0.3, offset: 1 },
        { ch: 'rx', drive: 'idle', amp: 1.5, freq: 0.25, offset: 2 },
        { ch: 'ty', drive: 'gait', amp: 0.03, amp2: 0.05, freq: 2 },
        { ch: 'rz', drive: 'gait', amp: 2, amp2: 3 },
        { ch: 'rx', drive: 'loco', amp: 14, window: [0.35, 1] },
        { ch: 'ty', drive: 'attack', attack: 'heal', amp: 0.14, amp2: 0.14 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: -6, amp2: -6 },
        { ch: 'ry', drive: 'attack', attack: 'lash', amp: 22, amp2: -26 },
        { ch: 'rx', drive: 'stagger', amp: -12 },
        { ch: 'tz', drive: 'stagger', amp: -0.12 },
        { ch: 'rz', drive: 'stagger', amp: 5, freq: 6 },
        // The hover fails: it drops and folds forward onto the floor.
        { ch: 'ty', drive: 'death', amp: -0.8, window: [0, 0.55] },
        { ch: 'rx', drive: 'death', amp: 72, window: [0.3, 0.95] },
        { ch: 'ty', drive: 'death', amp: -0.12, window: [0.55, 0.95] },
        { ch: 'rz', drive: 'death', amp: 12, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'chest',
      parent: 'body',
      pivot: [0, 1.4, -0.02],
      motions: [
        { ch: 'rx', drive: 'rest', amp: 10 },
        { ch: 'rx', drive: 'idle', amp: 2.5, freq: 0.25 },
        { ch: 's', drive: 'idle', amp: 0.02, freq: 0.4 },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 3, freq: 2, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: -16, amp2: -16 },
        { ch: 'ry', drive: 'attack', attack: 'lash', amp: 28, amp2: -30 },
        { ch: 'rx', drive: 'attack', attack: 'lash', amp: 10, amp2: -6 },
        { ch: 'rx', drive: 'stagger', amp: -14 },
        { ch: 'rx', drive: 'death', amp: 24, window: [0.3, 1] },
      ],
    },
    {
      name: 'head',
      parent: 'chest',
      pivot: [0, 1.7, 0.1],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.8 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.7 },
        { ch: 'rx', drive: 'rest', amp: -8 },
        { ch: 'ry', drive: 'idle', amp: 6, freq: 0.2 },
        { ch: 'rz', drive: 'idle', amp: 5, freq: 0.15, offset: 1.5 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: 14, amp2: 14 },
        { ch: 'rz', drive: 'attack', attack: 'heal', amp: 10, amp2: 10 },
        { ch: 'rx', drive: 'stagger', amp: -22 },
        { ch: 'ry', drive: 'stagger', amp: 10, freq: 5 },
        { ch: 'rx', drive: 'death', amp: 35, window: [0.2, 0.8] },
        { ch: 'rz', drive: 'death', amp: -25, window: [0.4, 1] },
      ],
    },
    {
      name: 'stalk',
      parent: 'chest',
      pivot: [0, 1.62, -0.17],
      motions: [
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.35 },
        { ch: 'rz', drive: 'idle', amp: 4, freq: 0.25, offset: 2 },
        { ch: 'rx', drive: 'gait', amp: 3, amp2: 5, freq: 2, offset: 1.5 },
        { ch: 'rx', drive: 'loco', amp: -12, window: [0.35, 1] },
        // Channel: the stalk bends forward so the lantern hangs out in front of the face.
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: 26, amp2: 26 },
        { ch: 'rx', drive: 'attack', attack: 'lash', amp: -10, amp2: 8 },
        { ch: 'rx', drive: 'stagger', amp: -16 },
        { ch: 'rz', drive: 'stagger', amp: 8, freq: 7 },
        { ch: 'rx', drive: 'death', amp: 55, window: [0.2, 0.9] },
        { ch: 'rz', drive: 'death', amp: 20, window: [0.4, 1] },
      ],
    },
    {
      name: 'lantern',
      parent: 'stalk',
      pivot: [0, 2.36, 0.24],
      motions: [
        { ch: 's', drive: 'idle', amp: 0.06, freq: 0.8 },
        { ch: 'rx', drive: 'idle', amp: 7, freq: 0.5, offset: 0.5 },
        { ch: 'rz', drive: 'idle', amp: 5, freq: 0.4, offset: 2.5 },
        { ch: 'rx', drive: 'gait', amp: 8, amp2: 12, freq: 2, offset: 2 },
        { ch: 's', drive: 'attack', attack: 'heal', amp: 0.24, amp2: 0.24 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: -30, amp2: -30 },
        { ch: 's', drive: 'attack', attack: 'heal', amp: 0.05, freq: 3 },
        { ch: 's', drive: 'stagger', amp: 0.1, freq: 9 },
        { ch: 's', drive: 'death', amp: -0.45, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'arm_L',
      parent: 'chest',
      pivot: [0.2, 1.56, 0.0],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rz', drive: 'rest', amp: 12 },
        { ch: 'rx', drive: 'rest', amp: -12 },
        { ch: 'rx', drive: 'idle', amp: 4, freq: 0.3 },
        { ch: 'rz', drive: 'idle', amp: 3, freq: 0.2, offset: 1 },
        { ch: 'rx', drive: 'loco', amp: 26, window: [0.35, 1] },
        { ch: 'rx', drive: 'gait', amp: 4, amp2: 7 },
        // Channel: arms spread and raised towards the tethered ally.
        { ch: 'rz', drive: 'attack', attack: 'heal', amp: 48, amp2: 48 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: -38, amp2: -38 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: 4, freq: 1.5 },
        { ch: 'rx', drive: 'attack', attack: 'lash', amp: -95, amp2: 45, mirror: false },
        { ch: 'ry', drive: 'attack', attack: 'lash', amp: -35, amp2: 30, mirror: false },
        { ch: 'rz', drive: 'attack', attack: 'lash', amp: 10, amp2: 40, mirror: false },
        { ch: 'rz', drive: 'stagger', amp: 22 },
        { ch: 'rx', drive: 'stagger', amp: 12 },
        { ch: 'rz', drive: 'death', amp: -30, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'forearm_L',
      parent: 'arm_L',
      pivot: [0.28, 1.2, 0.08],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'rest', amp: -22 },
        { ch: 'rx', drive: 'idle', amp: 6, freq: 0.35, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'heal', amp: -36, amp2: -36 },
        { ch: 'rx', drive: 'attack', attack: 'lash', amp: -40, amp2: 35, mirror: false },
        { ch: 'rx', drive: 'stagger', amp: 18 },
        { ch: 'rx', drive: 'death', amp: 35, window: [0.4, 1] },
      ],
    },
    // Tendrils under the sac: two-segment whips that trail back in flight.
    {
      name: 'tendrilF_L',
      parent: 'body',
      pivot: [0.08, 0.86, 0.05],
      mirror: true,
      mirrorPhase: 1.3,
      motions: [
        { ch: 'rx', drive: 'idle', amp: 9, freq: 0.4 },
        { ch: 'rz', drive: 'idle', amp: 6, freq: 0.3, offset: 1 },
        { ch: 'rx', drive: 'gait', amp: 8, amp2: 12 },
        { ch: 'rx', drive: 'loco', amp: 30, window: [0.3, 1] },
        { ch: 'rz', drive: 'attack', attack: 'heal', amp: 10, amp2: 10 },
        { ch: 'rx', drive: 'stagger', amp: 16, freq: 6 },
        { ch: 'rx', drive: 'death', amp: -60, window: [0.3, 1] },
        { ch: 'rz', drive: 'death', amp: 30, window: [0.4, 1] },
      ],
    },
    {
      name: 'tendrilF2_L',
      parent: 'tendrilF_L',
      pivot: [0.1, 0.56, 0.07],
      mirror: true,
      mirrorPhase: 1.3,
      motions: [
        { ch: 'rx', drive: 'idle', amp: 14, freq: 0.4, offset: -1 },
        { ch: 'rz', drive: 'idle', amp: 8, freq: 0.3 },
        { ch: 'rx', drive: 'gait', amp: 10, amp2: 16, offset: -1 },
        { ch: 'rx', drive: 'loco', amp: 20, window: [0.3, 1] },
        { ch: 'rx', drive: 'stagger', amp: 20, freq: 6, offset: 1 },
        { ch: 'rx', drive: 'death', amp: -50, window: [0.4, 1] },
      ],
    },
    {
      name: 'tendrilB_L',
      parent: 'body',
      pivot: [0.08, 0.86, -0.1],
      mirror: true,
      mirrorPhase: 2.1,
      motions: [
        { ch: 'rx', drive: 'idle', amp: 9, freq: 0.35, offset: 2 },
        { ch: 'rz', drive: 'idle', amp: 7, freq: 0.3, offset: 3 },
        { ch: 'rx', drive: 'gait', amp: 8, amp2: 12, offset: 1 },
        { ch: 'rx', drive: 'loco', amp: 26, window: [0.3, 1] },
        { ch: 'rz', drive: 'attack', attack: 'heal', amp: 14, amp2: 14 },
        { ch: 'rx', drive: 'stagger', amp: -16, freq: 6 },
        { ch: 'rx', drive: 'death', amp: 40, window: [0.3, 1] },
        { ch: 'rz', drive: 'death', amp: 35, window: [0.4, 1] },
      ],
    },
    {
      name: 'tendrilB2_L',
      parent: 'tendrilB_L',
      pivot: [0.11, 0.54, -0.14],
      mirror: true,
      mirrorPhase: 2.1,
      motions: [
        { ch: 'rx', drive: 'idle', amp: 14, freq: 0.35, offset: 1 },
        { ch: 'rz', drive: 'idle', amp: 9, freq: 0.3, offset: 2 },
        { ch: 'rx', drive: 'gait', amp: 10, amp2: 16 },
        { ch: 'rx', drive: 'loco', amp: 18, window: [0.3, 1] },
        { ch: 'rx', drive: 'stagger', amp: -20, freq: 6, offset: 1 },
        { ch: 'rx', drive: 'death', amp: 40, window: [0.4, 1] },
      ],
    },
    {
      name: 'tendrilC',
      parent: 'body',
      pivot: [0, 0.8, -0.04],
      motions: [
        { ch: 'rx', drive: 'idle', amp: 10, freq: 0.3, offset: 4 },
        { ch: 'rz', drive: 'idle', amp: 9, freq: 0.45 },
        { ch: 'rx', drive: 'loco', amp: 34, window: [0.3, 1] },
        { ch: 'rx', drive: 'gait', amp: 10, amp2: 14, offset: HALF_PI },
        { ch: 'rx', drive: 'stagger', amp: 22, freq: 5 },
        { ch: 'rx', drive: 'death', amp: -70, window: [0.3, 1] },
      ],
    },
  ],
  parts: [
    // Sac body under the torso (tendrils hang from it).
    {
      shape: 'lathe',
      bone: 'body',
      zone: 'flesh',
      a: [0, 1.12, -0.02],
      b: [0, 0.7, -0.04],
      profile: [
        [0, 0.1],
        [0.2, 0.17],
        [0.55, 0.19],
        [0.85, 0.13],
        [1, 0],
      ],
      lumpy: 0.016,
    },
    // Mantle skirt around the sac.
    {
      shape: 'ellipsoid',
      bone: 'body',
      zone: 'membrane',
      center: [0.1, 0.96, -0.1],
      radii: [0.12, 0.02, 0.26],
      rot: [70, 25, 0],
      bend: -0.05,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'body',
      zone: 'chitin',
      center: [0, 1.06, 0.1],
      radii: [0.15, 0.03, 0.12],
      rot: [-60, 0, 0],
      bend: -0.06,
    },
    // Torso.
    {
      shape: 'lathe',
      bone: 'chest',
      zone: 'flesh',
      a: [0, 1.06, -0.03],
      b: [0, 1.68, 0.05],
      profile: [
        [0, 0.1],
        [0.2, 0.14],
        [0.55, 0.17],
        [0.82, 0.19],
        [1, 0.1],
      ],
      ellipse: [1, 0.72],
      lumpy: 0.012,
    },
    // Exposed ribs.
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.03, 1.52, 0.14],
        [0.14, 1.5, 0.11],
        [0.18, 1.45, 0.0],
      ],
      radius: 0.014,
      radiusB: 0.01,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.03, 1.42, 0.14],
        [0.14, 1.4, 0.1],
        [0.17, 1.35, -0.01],
      ],
      radius: 0.013,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.03, 1.32, 0.13],
        [0.13, 1.3, 0.09],
        [0.15, 1.26, -0.01],
      ],
      radius: 0.012,
      radiusB: 0.008,
      mirror: true,
    },
    // Cowl: shoulder plates, a high back plate, a collar framing the mask.
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'chitin',
      center: [0.16, 1.63, -0.04],
      radii: [0.15, 0.035, 0.17],
      rot: [0, 0, -32],
      bend: -0.07,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'chitin',
      center: [0, 1.56, -0.17],
      radii: [0.2, 0.04, 0.2],
      rot: [-72, 0, 0],
      bend: -0.08,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'chitin',
      center: [0.1, 1.79, 0.02],
      radii: [0.035, 0.17, 0.14],
      rot: [0, 18, -8],
      bend: 0.04,
      mirror: true,
    },
    // Mantle down the back.
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'membrane',
      center: [0.13, 1.28, -0.2],
      radii: [0.13, 0.018, 0.4],
      rot: [84, 12, 0],
      bend: -0.05,
      mirror: true,
    },
    // Glowing pustules along the spine.
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'lantern',
      center: [0.07, 1.46, -0.17],
      radii: [0.035, 0.03, 0.03],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'lantern',
      center: [0.06, 1.32, -0.15],
      radii: [0.028, 0.025, 0.025],
      mirror: true,
    },
    // Stalk arching over the head, the lantern bulb hanging from its tip in a bone cage.
    {
      shape: 'tube',
      bone: 'stalk',
      zone: 'flesh',
      points: [
        [0, 1.6, -0.19],
        [0, 1.95, -0.27],
        [0, 2.28, -0.16],
        [0, 2.44, 0.06],
        [0, 2.4, 0.24],
      ],
      radius: 0.04,
      radiusB: 0.02,
    },
    {
      shape: 'spike',
      bone: 'stalk',
      zone: 'bone',
      a: [0, 1.95, -0.29],
      b: [0, 2.03, -0.42],
      radius: 0.02,
      curve: [0, 0.03, 0],
    },
    {
      shape: 'spike',
      bone: 'stalk',
      zone: 'bone',
      a: [0, 2.26, -0.19],
      b: [0, 2.39, -0.3],
      radius: 0.018,
      curve: [0, 0.03, 0],
    },
    {
      shape: 'ellipsoid',
      bone: 'lantern',
      zone: 'lantern',
      center: [0, 2.22, 0.28],
      radii: [0.13, 0.15, 0.13],
      lumpy: 0.008,
    },
    {
      shape: 'tube',
      bone: 'lantern',
      zone: 'bone',
      points: [
        [0.02, 2.39, 0.25],
        [0.13, 2.3, 0.29],
        [0.14, 2.16, 0.3],
        [0.02, 2.05, 0.28],
      ],
      radius: 0.012,
      radiusB: 0.008,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'lantern',
      zone: 'bone',
      points: [
        [0, 2.39, 0.27],
        [0, 2.3, 0.42],
        [0, 2.14, 0.42],
        [0, 2.05, 0.3],
      ],
      radius: 0.012,
      radiusB: 0.008,
    },
    {
      shape: 'spike',
      bone: 'lantern',
      zone: 'bone',
      a: [0, 2.07, 0.28],
      b: [0, 1.94, 0.3],
      radius: 0.014,
    },
    // Head: neck, bone mask with three eyes, chin feelers, a crest of spines.
    {
      shape: 'capsule',
      bone: 'head',
      zone: 'flesh',
      a: [0, 1.6, 0.04],
      b: [0, 1.76, 0.12],
      radius: 0.05,
      radiusB: 0.045,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.83, 0.12],
      radii: [0.1, 0.12, 0.11],
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'bone',
      center: [0, 1.81, 0.2],
      radii: [0.085, 0.12, 0.04],
      rot: [-8, 0, 0],
      bend: 0.025,
    },
    { shape: 'ellipsoid', bone: 'head', zone: 'eyes', center: [0, 1.88, 0.238], radii: [0.016, 0.022, 0.012] },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.036, 1.83, 0.232],
      radii: [0.016, 0.011, 0.012],
      rot: [0, 0, -18],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.03, 1.72, 0.2],
      b: [0.05, 1.58, 0.21],
      radius: 0.012,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0, 1.93, 0.08],
      b: [0, 2.04, -0.06],
      radius: 0.022,
      curve: [0, 0.02, 0],
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.05, 1.91, 0.06],
      b: [0.1, 1.98, -0.07],
      radius: 0.016,
      curve: [0, 0.02, 0],
      mirror: true,
    },
    // Arms: thin, with a shoulder spike, glowing wrist beads and long needle fingers.
    {
      shape: 'capsule',
      bone: 'arm_L',
      zone: 'flesh',
      a: [0.2, 1.56, 0.0],
      b: [0.28, 1.2, 0.08],
      radius: 0.038,
      radiusB: 0.028,
      lumpy: 0.005,
    },
    {
      shape: 'spike',
      bone: 'arm_L',
      zone: 'bone',
      a: [0.22, 1.62, -0.02],
      b: [0.3, 1.76, -0.08],
      radius: 0.02,
      curve: [0.01, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'forearm_L',
      zone: 'chitin',
      a: [0.28, 1.2, 0.08],
      b: [0.3, 0.9, 0.22],
      radius: 0.03,
      radiusB: 0.022,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'lantern',
      center: [0.3, 0.93, 0.2],
      radii: [0.028, 0.028, 0.028],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.31, 0.9, 0.22],
      b: [0.35, 0.7, 0.31],
      radius: 0.011,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.3, 0.9, 0.22],
      b: [0.29, 0.69, 0.33],
      radius: 0.011,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.29, 0.9, 0.21],
      b: [0.24, 0.73, 0.28],
      radius: 0.01,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    // Tendrils.
    {
      shape: 'tube',
      bone: 'tendrilF_L',
      zone: 'flesh',
      points: [
        [0.08, 0.88, 0.05],
        [0.1, 0.72, 0.08],
        [0.1, 0.56, 0.07],
      ],
      radius: 0.034,
      radiusB: 0.024,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'tendrilF2_L',
      zone: 'flesh',
      points: [
        [0.1, 0.57, 0.07],
        [0.09, 0.4, 0.05],
        [0.08, 0.23, 0.09],
      ],
      radius: 0.024,
      radiusB: 0.007,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'tendrilB_L',
      zone: 'membrane',
      points: [
        [0.08, 0.88, -0.1],
        [0.11, 0.7, -0.13],
        [0.11, 0.54, -0.14],
      ],
      radius: 0.03,
      radiusB: 0.022,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'tendrilB2_L',
      zone: 'membrane',
      points: [
        [0.11, 0.55, -0.14],
        [0.1, 0.38, -0.17],
        [0.07, 0.24, -0.14],
      ],
      radius: 0.022,
      radiusB: 0.006,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'tendrilC',
      zone: 'flesh',
      points: [
        [0, 0.82, -0.04],
        [0.02, 0.6, -0.06],
        [-0.01, 0.38, -0.04],
        [0.01, 0.16, -0.08],
      ],
      radius: 0.03,
      radiusB: 0.006,
    },
  ],
  attacks: [
    // Held for the whole channel (windup = strike: no pose / glow change while tethered).
    { id: 'heal', windup: 0.4, strike: 0.4, glow: 1.6 },
    { id: 'lash', windup: 0.38, strike: 0.56, glow: 0.5 },
  ],
  hitboxes: [
    { bone: 'lantern', shape: 'sphere', zone: 'weakpoint', a: [0, 2.22, 0.28], radius: 0.17 },
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 1.83, 0.14], radius: 0.13 },
    { bone: 'chest', shape: 'capsule', zone: 'body', a: [0, 1.1, -0.02], b: [0, 1.62, 0.03], radius: 0.19 },
    { bone: 'body', shape: 'capsule', zone: 'body', a: [0, 1.02, -0.03], b: [0, 0.78, -0.04], radius: 0.17 },
    {
      bone: 'arm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.2, 1.56, 0.0],
      b: [0.28, 1.2, 0.08],
      radius: 0.06,
      mirror: true,
    },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.28, 1.2, 0.08],
      b: [0.31, 0.78, 0.26],
      radius: 0.05,
      mirror: true,
    },
    {
      bone: 'tendrilF_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.09, 0.86, 0.06],
      b: [0.1, 0.52, 0.07],
      radius: 0.05,
      mirror: true,
    },
    {
      bone: 'tendrilB_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.09, 0.86, -0.1],
      b: [0.11, 0.52, -0.14],
      radius: 0.045,
      mirror: true,
    },
  ],
  sockets: {
    lantern: [{ bone: 'lantern', point: [0, 2.22, 0.34] }],
    head: [{ bone: 'head', point: [0, 1.83, 0.16] }],
    chest: [{ bone: 'chest', point: [0, 1.45, 0.1] }],
    core: [{ bone: 'chest', point: [0, 1.3, -0.02] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 55, pitchMaxDeg: 35 },
  // The stalk and lantern reach past the rest bounds when it rears up to heal; the corpse sprawls.
  cullMargin: 1,
  dissolve: { edgeColor: [0.35, 1, 0.4], edgeIntensity: 11, edgeWidth: 0.08, noiseScale: 7 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 0.8 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 0.9,
    death: 'enemy.death.acid',
    deathScale: 0.9,
    deathSocket: 'lantern',
  },
};
