/**
 * Springer – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and TYPES
 * from '../enemyVisuals' (runtime cycle otherwise).
 *
 * Lanky, emaciated digitigrade hunter (~1.5 m hunched, 2 m stretched): ash-pale skin over protruding
 * ribs with cold cyan veins, black chitin plates and a spined back, a long eyeless-looking skull with
 * a row of glowing cyan slits per side and swept-back horns, very long arms ending in sickle claws, a
 * whip tail. Sprints with its arms swept back; pounce = deep crouch (telegraph: eye glint) → stretched
 * flight with claws and jaws forward; slash = one sickle arm raised high and raked across.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const CYAN = [0.3, 0.82, 1] as const;

export const LEAPER_VISUAL: EnemyVisualDef | null = {
  // Leaper-heavy waves (special "all leapers" waves) + the dying.
  capacity: 48,
  zones: {
    skin: {
      color: [0.16, 0.155, 0.15],
      color2: [0.26, 0.24, 0.22],
      tip: [0.06, 0.055, 0.06],
      tipAmount: 0.5,
      roughness: 0.42,
      metalness: 0,
      clearcoat: 0.6,
      emissive: CYAN,
      emissiveIntensity: 2.8,
      glow: 0,
      pulse: 0,
      veins: 0.6,
      bump: 0.8,
      cells: 0.18,
      scale: 3,
    },
    chitin: {
      color: [0.018, 0.022, 0.03],
      color2: [0.045, 0.05, 0.065],
      tip: [0.16, 0.16, 0.17],
      tipAmount: 0.3,
      roughness: 0.26,
      metalness: 0.12,
      clearcoat: 1,
      emissive: CYAN,
      emissiveIntensity: 1.6,
      glow: 0,
      pulse: 0,
      veins: 0.15,
      bump: 1,
      cells: 0.7,
      scale: 3.4,
    },
    bone: BONE,
    eyes: {
      color: [0.01, 0.03, 0.05],
      color2: [0.01, 0.03, 0.05],
      tip: [0.01, 0.03, 0.05],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [0.45, 0.9, 1],
      emissiveIntensity: 8,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
    maw: {
      color: [0.02, 0.05, 0.07],
      color2: [0.04, 0.08, 0.1],
      tip: [0.02, 0.05, 0.07],
      tipAmount: 0,
      roughness: 0.2,
      metalness: 0,
      clearcoat: 1,
      emissive: CYAN,
      emissiveIntensity: 5,
      glow: 0.65,
      pulse: 0.5,
      veins: 0,
      bump: 0.3,
      cells: 0.2,
      scale: 6,
    },
  },
  bones: [
    {
      name: 'pelvis',
      parent: null,
      pivot: [0, 1, -0.12],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -2 },
        { ch: 'rx', drive: 'emerge', amp: -25, window: [0.1, 1] },
        { ch: 'ty', drive: 'gait', amp: 0.04, amp2: 0.09, freq: 2, offset: HALF_PI },
        { ch: 'rz', drive: 'gait', amp: 4, amp2: 5 },
        { ch: 'ry', drive: 'gait', amp: 5, amp2: 7, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 10, window: [0.5, 1] },
        { ch: 'ty', drive: 'loco', amp: -0.06, window: [0.5, 1] },
        { ch: 'ty', drive: 'idle', amp: 0.008, freq: 0.6 },
        { ch: 'rx', drive: 'idle', amp: 1.5, freq: 0.35 },
        { ch: 'ty', drive: 'attack', attack: 'pounce', amp: -0.12, amp2: -0.36 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: 6, amp2: 16 },
        { ch: 'ry', drive: 'attack', attack: 'slash', amp: -14, amp2: 12 },
        { ch: 'ty', drive: 'attack', attack: 'slash', amp: -0.1, amp2: -0.04 },
        { ch: 'rx', drive: 'stagger', amp: -10 },
        { ch: 'tz', drive: 'stagger', amp: -0.08 },
        { ch: 'rz', drive: 'stagger', amp: 5, freq: 7 },
        { ch: 'ty', drive: 'death', amp: -0.55, window: [0.05, 0.5] },
        { ch: 'rx', drive: 'death', amp: 55, window: [0.3, 0.95] },
        { ch: 'ty', drive: 'death', amp: -0.12, window: [0.5, 0.95] },
        { ch: 'rz', drive: 'death', amp: 15, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'spine',
      parent: 'pelvis',
      pivot: [0, 1.06, -0.08],
      motions: [
        { ch: 'rx', drive: 'gait', amp: 3, amp2: 6, freq: 2, offset: 1 },
        { ch: 'ry', drive: 'gait', amp: -5, amp2: -7, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 8, window: [0.5, 1] },
        { ch: 'rx', drive: 'idle', amp: 2, freq: 0.4 },
        { ch: 's', drive: 'idle', amp: 0.015, freq: 0.4 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -16, amp2: 14 },
        { ch: 'ry', drive: 'attack', attack: 'slash', amp: -28, amp2: 30 },
        { ch: 'rz', drive: 'attack', attack: 'slash', amp: 6, amp2: -6 },
        { ch: 'rx', drive: 'attack', attack: 'slash', amp: 10, amp2: -6 },
        { ch: 'rx', drive: 'stagger', amp: -16 },
        { ch: 'rz', drive: 'stagger', amp: 4, freq: 6 },
        { ch: 'rx', drive: 'death', amp: 20, window: [0.3, 1] },
      ],
    },
    {
      name: 'neck',
      parent: 'spine',
      pivot: [0, 1.36, 0.36],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.4 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.4 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.3, offset: 2 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -12, amp2: -24 },
        { ch: 'rx', drive: 'stagger', amp: -15 },
        { ch: 'rx', drive: 'death', amp: 25, window: [0.4, 1] },
      ],
    },
    {
      name: 'head',
      parent: 'neck',
      pivot: [0, 1.4, 0.5],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.6 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.6 },
        { ch: 'ry', drive: 'idle', amp: 5, freq: 0.23 },
        { ch: 'rz', drive: 'idle', amp: 4, freq: 0.17, offset: 1 },
        // A fast predatory twitch on top of the slow looks.
        { ch: 'ry', drive: 'idle', amp: 2.5, freq: 2.3 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -8, amp2: -10 },
        { ch: 'rx', drive: 'stagger', amp: -22 },
        { ch: 'ry', drive: 'stagger', amp: 10, freq: 5 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.3, 0.8] },
        { ch: 'ry', drive: 'death', amp: 25, window: [0.5, 1] },
      ],
    },
    {
      name: 'jaw',
      parent: 'head',
      pivot: [0, 1.37, 0.6],
      motions: [
        { ch: 'rx', drive: 'rest', amp: 5 },
        { ch: 'rx', drive: 'idle', amp: 4, freq: 0.7 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: 38, amp2: 18 },
        { ch: 'rx', drive: 'attack', attack: 'slash', amp: 26, amp2: 10 },
        { ch: 'rx', drive: 'stagger', amp: 20 },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.2, 0.7] },
      ],
    },
    {
      name: 'arm_L',
      parent: 'spine',
      pivot: [0.19, 1.34, 0.26],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: -22, amp2: -30 },
        { ch: 'rz', drive: 'rest', amp: 8 },
        // Sprinting: arms swept back, claws trailing.
        { ch: 'rx', drive: 'loco', amp: 38, window: [0.5, 1] },
        { ch: 'rx', drive: 'idle', amp: 4, freq: 0.3 },
        { ch: 'rz', drive: 'idle', amp: 3, freq: 0.21 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -100, amp2: 40 },
        { ch: 'rz', drive: 'attack', attack: 'pounce', amp: 8, amp2: 26 },
        { ch: 'rx', drive: 'attack', attack: 'slash', amp: -35, amp2: -130, mirror: false },
        { ch: 'ry', drive: 'attack', attack: 'slash', amp: -45, amp2: 35, mirror: false },
        { ch: 'rz', drive: 'attack', attack: 'slash', amp: -5, amp2: 20, mirror: false },
        { ch: 'rz', drive: 'stagger', amp: 18 },
        { ch: 'rx', drive: 'stagger', amp: -20 },
        { ch: 'rz', drive: 'death', amp: 30, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: -40, window: [0.4, 1] },
      ],
    },
    {
      name: 'forearm_L',
      parent: 'arm_L',
      pivot: [0.28, 0.98, 0.36],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: -14, amp2: -20, wave: 'pos', offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: -24, window: [0.5, 1] },
        { ch: 'rx', drive: 'idle', amp: 5, freq: 0.35, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -8, amp2: -35 },
        { ch: 'rx', drive: 'attack', attack: 'slash', amp: -8, amp2: -60, mirror: false },
        { ch: 'rx', drive: 'death', amp: -35, window: [0.4, 1] },
      ],
    },
    {
      name: 'thigh_L',
      parent: 'pelvis',
      pivot: [0.13, 1, -0.14],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 30, amp2: 44 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: 30, amp2: -30 },
        { ch: 'rz', drive: 'attack', attack: 'pounce', amp: 4, amp2: 8 },
        { ch: 'rx', drive: 'stagger', amp: -8 },
        { ch: 'rx', drive: 'death', amp: -70, window: [0.05, 0.5] },
      ],
    },
    {
      name: 'shin_L',
      parent: 'thigh_L',
      pivot: [0.19, 0.6, 0.18],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 28, amp2: 40, wave: 'pos', offset: -HALF_PI },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: 8, amp2: 42 },
        { ch: 'rx', drive: 'death', amp: 95, window: [0.05, 0.5] },
      ],
    },
    {
      name: 'foot_L',
      parent: 'shin_L',
      pivot: [0.19, 0.3, -0.22],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'gait', amp: 18, amp2: 26, wave: 'pos', offset: -HALF_PI },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: 30, amp2: -16 },
        { ch: 'rx', drive: 'death', amp: -30, window: [0.1, 0.6] },
      ],
    },
    {
      name: 'tail',
      parent: 'pelvis',
      pivot: [0, 1.02, -0.3],
      motions: [
        { ch: 'ry', drive: 'gait', amp: 8, amp2: 12, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 12, window: [0.5, 1] },
        { ch: 'ry', drive: 'idle', amp: 6, freq: 0.25 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.3, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'pounce', amp: -10, amp2: 22 },
        { ch: 'ry', drive: 'stagger', amp: 15, freq: 5 },
        { ch: 'rx', drive: 'death', amp: -20, window: [0.3, 1] },
      ],
    },
  ],
  parts: [
    // Pelvis + emaciated, forward-pitched torso.
    {
      shape: 'ellipsoid',
      bone: 'pelvis',
      zone: 'skin',
      center: [0, 1, -0.14],
      radii: [0.14, 0.11, 0.13],
      lumpy: 0.008,
    },
    {
      shape: 'lathe',
      bone: 'spine',
      zone: 'skin',
      a: [0, 1.02, -0.2],
      b: [0, 1.42, 0.42],
      profile: [
        [0, 0],
        [0.08, 0.1],
        [0.25, 0.115],
        [0.55, 0.18],
        [0.8, 0.17],
        [0.95, 0.1],
        [1, 0],
      ],
      ellipse: [1, 0.78],
      lumpy: 0.01,
    },
    // Protruding ribs.
    {
      shape: 'tube',
      bone: 'spine',
      zone: 'bone',
      points: [
        [0.03, 1.22, -0.07],
        [0.13, 1.19, -0.04],
        [0.155, 1.14, -0.01],
        [0.12, 1.08, 0.03],
        [0.04, 1.06, 0.05],
      ],
      radius: 0.012,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'spine',
      zone: 'bone',
      points: [
        [0.03, 1.3, 0.02],
        [0.15, 1.27, 0.04],
        [0.19, 1.2, 0.08],
        [0.15, 1.12, 0.13],
        [0.05, 1.1, 0.16],
      ],
      radius: 0.014,
      radiusB: 0.01,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'spine',
      zone: 'bone',
      points: [
        [0.03, 1.37, 0.12],
        [0.15, 1.34, 0.14],
        [0.19, 1.27, 0.19],
        [0.15, 1.19, 0.24],
        [0.05, 1.17, 0.27],
      ],
      radius: 0.014,
      radiusB: 0.01,
      mirror: true,
    },
    // Dorsal chitin plates and the spined ridge.
    {
      shape: 'ellipsoid',
      bone: 'spine',
      zone: 'chitin',
      center: [0, 1.24, -0.08],
      radii: [0.13, 0.03, 0.1],
      rot: [-33, 0, 0],
      bend: -0.05,
    },
    {
      shape: 'ellipsoid',
      bone: 'spine',
      zone: 'chitin',
      center: [0, 1.345, 0.03],
      radii: [0.16, 0.035, 0.11],
      rot: [-33, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'ellipsoid',
      bone: 'spine',
      zone: 'chitin',
      center: [0, 1.418, 0.154],
      radii: [0.15, 0.035, 0.1],
      rot: [-33, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'ellipsoid',
      bone: 'spine',
      zone: 'chitin',
      center: [0, 1.46, 0.28],
      radii: [0.11, 0.03, 0.08],
      rot: [-33, 0, 0],
      bend: -0.04,
    },
    {
      shape: 'spike',
      bone: 'spine',
      zone: 'bone',
      a: [0, 1.26, -0.09],
      b: [0, 1.36, -0.22],
      radius: 0.022,
      curve: [0, 0.02, 0],
    },
    {
      shape: 'spike',
      bone: 'spine',
      zone: 'bone',
      a: [0, 1.37, 0.02],
      b: [0, 1.52, -0.12],
      radius: 0.028,
      curve: [0, 0.03, 0],
    },
    {
      shape: 'spike',
      bone: 'spine',
      zone: 'bone',
      a: [0, 1.44, 0.14],
      b: [0, 1.62, 0.02],
      radius: 0.03,
      curve: [0, 0.03, 0],
    },
    {
      shape: 'spike',
      bone: 'spine',
      zone: 'bone',
      a: [0.07, 1.43, 0.2],
      b: [0.14, 1.58, 0.08],
      radius: 0.02,
      curve: [0.01, 0.02, 0],
      mirror: true,
    },
    // Shoulder plates.
    {
      shape: 'ellipsoid',
      bone: 'arm_L',
      zone: 'chitin',
      center: [0.21, 1.38, 0.26],
      radii: [0.08, 0.03, 0.1],
      rot: [0, 0, -32],
      bend: -0.04,
      mirror: true,
    },
    // Neck, long skull with swept-back horns, eye slits, glowing maw.
    {
      shape: 'capsule',
      bone: 'neck',
      zone: 'skin',
      a: [0, 1.36, 0.36],
      b: [0, 1.41, 0.52],
      radius: 0.06,
      radiusB: 0.05,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.44, 0.64],
      radii: [0.085, 0.075, 0.2],
      rot: [8, 0, 0],
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.5, 0.6],
      radii: [0.08, 0.03, 0.18],
      rot: [4, 0, 0],
      bend: -0.03,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.05, 1.5, 0.54],
      b: [0.11, 1.6, 0.3],
      radius: 0.024,
      curve: [0.02, 0.04, 0],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.06, 1.47, 0.6],
      b: [0.14, 1.5, 0.46],
      radius: 0.016,
      curve: [0.01, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.066, 1.47, 0.73],
      radii: [0.016, 0.012, 0.024],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.076, 1.46, 0.67],
      radii: [0.013, 0.01, 0.02],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.08, 1.45, 0.61],
      radii: [0.01, 0.008, 0.016],
      mirror: true,
    },
    { shape: 'ellipsoid', bone: 'head', zone: 'maw', center: [0, 1.4, 0.72], radii: [0.05, 0.03, 0.1] },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.035, 1.41, 0.8],
      b: [0.03, 1.36, 0.82],
      radius: 0.009,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.045, 1.41, 0.74],
      b: [0.04, 1.365, 0.75],
      radius: 0.008,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'jaw',
      zone: 'chitin',
      center: [0, 1.37, 0.7],
      radii: [0.065, 0.026, 0.15],
      rot: [10, 0, 0],
    },
    {
      shape: 'spike',
      bone: 'jaw',
      zone: 'bone',
      a: [0.035, 1.37, 0.8],
      b: [0.032, 1.41, 0.81],
      radius: 0.009,
      mirror: true,
    },
    // Arms: long, thin; sickle claws.
    {
      shape: 'capsule',
      bone: 'arm_L',
      zone: 'skin',
      a: [0.19, 1.34, 0.26],
      b: [0.28, 0.98, 0.36],
      radius: 0.05,
      radiusB: 0.034,
      mirror: true,
      lumpy: 0.005,
    },
    {
      shape: 'spike',
      bone: 'arm_L',
      zone: 'bone',
      a: [0.28, 0.99, 0.35],
      b: [0.33, 1.1, 0.18],
      radius: 0.018,
      curve: [0, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'forearm_L',
      zone: 'chitin',
      a: [0.28, 0.98, 0.36],
      b: [0.29, 0.62, 0.5],
      radius: 0.034,
      radiusB: 0.027,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'skin',
      center: [0.29, 0.6, 0.51],
      radii: [0.035, 0.03, 0.04],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.29, 0.6, 0.52],
      b: [0.31, 0.22, 0.8],
      radius: 0.022,
      curve: [0, -0.04, 0.09],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.27, 0.6, 0.51],
      b: [0.23, 0.28, 0.72],
      radius: 0.018,
      curve: [0, -0.03, 0.07],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.31, 0.6, 0.5],
      b: [0.37, 0.35, 0.66],
      radius: 0.015,
      curve: [0, -0.02, 0.05],
      mirror: true,
    },
    // Digitigrade legs: thigh forward to a high knee, shin back to the hock, long foot.
    {
      shape: 'capsule',
      bone: 'thigh_L',
      zone: 'skin',
      a: [0.13, 1, -0.14],
      b: [0.19, 0.6, 0.18],
      radius: 0.075,
      radiusB: 0.05,
      mirror: true,
      lumpy: 0.006,
    },
    {
      shape: 'ellipsoid',
      bone: 'shin_L',
      zone: 'chitin',
      center: [0.19, 0.61, 0.2],
      radii: [0.045, 0.04, 0.05],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shin_L',
      zone: 'bone',
      a: [0.19, 0.62, 0.22],
      b: [0.2, 0.74, 0.34],
      radius: 0.018,
      curve: [0, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'shin_L',
      zone: 'chitin',
      a: [0.19, 0.6, 0.18],
      b: [0.19, 0.3, -0.22],
      radius: 0.042,
      radiusB: 0.032,
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'foot_L',
      zone: 'chitin',
      a: [0.19, 0.3, -0.22],
      b: [0.2, 0.03, 0.02],
      radius: 0.03,
      radiusB: 0.024,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'foot_L',
      zone: 'bone',
      a: [0.2, 0.03, 0.02],
      b: [0.23, 0.005, 0.17],
      radius: 0.022,
      curve: [0, 0.01, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'foot_L',
      zone: 'bone',
      a: [0.19, 0.03, 0.02],
      b: [0.13, 0.005, 0.14],
      radius: 0.018,
      curve: [0, 0.01, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'foot_L',
      zone: 'bone',
      a: [0.19, 0.06, -0.02],
      b: [0.19, 0.005, -0.11],
      radius: 0.015,
      mirror: true,
    },
    // Whip tail.
    {
      shape: 'tube',
      bone: 'tail',
      zone: 'skin',
      points: [
        [0, 1.02, -0.26],
        [0, 0.98, -0.55],
        [0, 0.88, -0.82],
        [0, 0.72, -1.05],
      ],
      radius: 0.05,
      radiusB: 0.012,
    },
    {
      shape: 'spike',
      bone: 'tail',
      zone: 'bone',
      a: [0, 1.02, -0.44],
      b: [0, 1.12, -0.58],
      radius: 0.018,
      curve: [0, 0.01, 0],
    },
    {
      shape: 'spike',
      bone: 'tail',
      zone: 'bone',
      a: [0, 0.94, -0.7],
      b: [0, 1.02, -0.84],
      radius: 0.014,
    },
  ],
  attacks: [
    { id: 'pounce', windup: 0.42, strike: 0.84, glow: 1.8 },
    { id: 'slash', windup: 0.32, strike: 0.48, glow: 1 },
  ],
  hitboxes: [
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 1.44, 0.66], radius: 0.13 },
    { bone: 'spine', shape: 'capsule', zone: 'body', a: [0, 1.08, -0.12], b: [0, 1.38, 0.36], radius: 0.19 },
    {
      bone: 'arm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.19, 1.34, 0.26],
      b: [0.28, 0.98, 0.36],
      radius: 0.065,
      mirror: true,
    },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.28, 0.98, 0.36],
      b: [0.3, 0.4, 0.62],
      radius: 0.07,
      mirror: true,
    },
    {
      bone: 'thigh_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.13, 0.98, -0.12],
      b: [0.19, 0.6, 0.18],
      radius: 0.09,
      mirror: true,
    },
    {
      bone: 'shin_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.19, 0.6, 0.18],
      b: [0.19, 0.3, -0.22],
      radius: 0.06,
      mirror: true,
    },
    {
      bone: 'foot_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.19, 0.3, -0.22],
      b: [0.2, 0.05, 0.04],
      radius: 0.05,
      mirror: true,
    },
  ],
  sockets: {
    eyes: [{ bone: 'head', point: [0, 1.47, 0.76] }],
    head: [{ bone: 'head', point: [0, 1.44, 0.64] }],
    jaws: [{ bone: 'jaw', point: [0, 1.37, 0.82] }],
    chest: [{ bone: 'spine', point: [0, 1.3, 0.22] }],
    core: [{ bone: 'spine', point: [0, 1.2, 0.06] }],
    claws: [
      { bone: 'forearm_L', point: [0.3, 0.3, 0.74] },
      { bone: 'forearm_R', point: [-0.3, 0.3, 0.74] },
    ],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 55, pitchMaxDeg: 40 },
  // Pounce: arms and claws reach far ahead of the rest pose, the tail streams behind.
  cullMargin: 1.2,
  dissolve: { edgeColor: [0.35, 0.85, 1], edgeIntensity: 11, edgeWidth: 0.08, noiseScale: 8 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 0.85 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 0.85,
    death: 'enemy.death',
    deathScale: 0.85,
    deathSocket: 'core',
  },
};
