/**
 * Milbe – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and TYPES
 * from '../enemyVisuals' (runtime cycle otherwise).
 *
 * Tick-sized parasite (~0.4 m): glossy blue-black carapace, a swollen teal-glowing abdomen (a swarm
 * reads as a carpet of moving lights in the dark), two eye dots, chittering mandibles, eight
 * spindly legs in a tripod gait. Cheap on purpose: 13 bones, few small parts (low tessellation);
 * one draw call for the whole swarm.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const TEAL = [0.1, 1, 0.75] as const;

export const MITE_VISUAL: EnemyVisualDef | null = {
  // Mite swarm waves may fill every living slot (ENEMY_AI.capacity) + the dying.
  capacity: 80,
  zones: {
    chitin: {
      color: [0.015, 0.02, 0.025],
      color2: [0.04, 0.05, 0.06],
      tip: [0.12, 0.13, 0.14],
      tipAmount: 0.3,
      roughness: 0.2,
      metalness: 0.1,
      clearcoat: 1,
      emissive: TEAL,
      emissiveIntensity: 1,
      glow: 0,
      pulse: 0,
      veins: 0.1,
      bump: 0.8,
      cells: 0.6,
      scale: 9,
    },
    glow: {
      color: [0.03, 0.2, 0.16],
      color2: [0.05, 0.3, 0.24],
      tip: [0.03, 0.2, 0.16],
      tipAmount: 0,
      roughness: 0.12,
      metalness: 0,
      clearcoat: 1,
      emissive: TEAL,
      emissiveIntensity: 3.5,
      glow: 0.9,
      pulse: 0.5,
      veins: 0.6,
      bump: 0.4,
      cells: 0.6,
      scale: 9,
    },
    bone: BONE,
    eyes: {
      color: [0.01, 0.05, 0.04],
      color2: [0.01, 0.05, 0.04],
      tip: [0.01, 0.05, 0.04],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [0.3, 1, 0.85],
      emissiveIntensity: 7,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
  },
  bones: [
    {
      name: 'body',
      parent: null,
      pivot: [0, 0.15, 0],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -0.5 },
        { ch: 'rx', drive: 'emerge', amp: -30, window: [0.1, 1] },
        { ch: 'ty', drive: 'gait', amp: 0.008, amp2: 0.014, freq: 2 },
        { ch: 'rz', drive: 'gait', amp: 3, amp2: 5 },
        { ch: 'ty', drive: 'idle', amp: 0.004, freq: 1.1 },
        { ch: 'ry', drive: 'idle', amp: 6, freq: 0.37 },
        { ch: 'rx', drive: 'attack', attack: 'bite', amp: 14, amp2: -18 },
        { ch: 'tz', drive: 'attack', attack: 'bite', amp: 0.07, amp2: -0.03 },
        { ch: 'rx', drive: 'stagger', amp: -20 },
        { ch: 'rz', drive: 'stagger', amp: 10, freq: 9 },
        // Flips onto its back.
        { ch: 'rz', drive: 'death', amp: 170, window: [0.1, 0.6] },
        { ch: 'ty', drive: 'death', amp: -0.04, window: [0.3, 0.8] },
      ],
    },
    {
      name: 'abdomen',
      parent: 'body',
      pivot: [0, 0.16, -0.06],
      motions: [
        { ch: 's', drive: 'idle', amp: 0.06, freq: 1.3 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.8 },
        { ch: 'ry', drive: 'gait', amp: 6, amp2: 10, offset: HALF_PI },
        { ch: 'rx', drive: 'attack', attack: 'bite', amp: -10, amp2: 6 },
        { ch: 's', drive: 'death', amp: -0.3, window: [0.3, 1] },
      ],
    },
    {
      name: 'head',
      parent: 'body',
      pivot: [0, 0.14, 0.09],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.8 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.5 },
        { ch: 'ry', drive: 'idle', amp: 8, freq: 0.9 },
        { ch: 'rx', drive: 'attack', attack: 'bite', amp: 20, amp2: -25 },
      ],
    },
    {
      name: 'jaw_L',
      parent: 'head',
      pivot: [0.025, 0.12, 0.15],
      mirror: true,
      motions: [
        { ch: 'ry', drive: 'idle', amp: 10, freq: 3 },
        { ch: 'ry', drive: 'attack', attack: 'bite', amp: -10, amp2: 40 },
        { ch: 'ry', drive: 'death', amp: 30, window: [0.2, 0.6] },
      ],
    },
    // Legs A–D (front to back): A and C step together, B and D in antiphase; the right twins are
    // shifted by π – a tripod gait.
    {
      name: 'legA_L',
      parent: 'body',
      pivot: [0.07, 0.15, 0.07],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 22, amp2: 30 },
        { ch: 'rz', drive: 'gait', amp: 14, amp2: 20, wave: 'pos', offset: -HALF_PI },
        { ch: 'ry', drive: 'attack', attack: 'bite', amp: -15, amp2: 8 },
        { ch: 'rz', drive: 'attack', attack: 'bite', amp: 12, amp2: 20 },
        { ch: 'rz', drive: 'stagger', amp: -8 },
        { ch: 'rz', drive: 'death', amp: 40, window: [0.2, 0.7] },
        { ch: 'rz', drive: 'death', amp: 10, freq: 11, window: [0.6, 1] },
      ],
    },
    {
      name: 'legB_L',
      parent: 'body',
      pivot: [0.08, 0.15, 0.02],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 22, amp2: 30, offset: PI },
        { ch: 'rz', drive: 'gait', amp: 14, amp2: 20, wave: 'pos', offset: HALF_PI },
        { ch: 'rz', drive: 'stagger', amp: -8 },
        { ch: 'rz', drive: 'death', amp: 40, window: [0.2, 0.7] },
        { ch: 'rz', drive: 'death', amp: 10, freq: 9, offset: 1, window: [0.6, 1] },
      ],
    },
    {
      name: 'legC_L',
      parent: 'body',
      pivot: [0.08, 0.15, -0.03],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 22, amp2: 30 },
        { ch: 'rz', drive: 'gait', amp: 14, amp2: 20, wave: 'pos', offset: -HALF_PI },
        { ch: 'rz', drive: 'stagger', amp: -8 },
        { ch: 'rz', drive: 'death', amp: 40, window: [0.2, 0.7] },
        { ch: 'rz', drive: 'death', amp: 10, freq: 12, offset: 2, window: [0.6, 1] },
      ],
    },
    {
      name: 'legD_L',
      parent: 'body',
      pivot: [0.07, 0.15, -0.08],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 22, amp2: 30, offset: PI },
        { ch: 'rz', drive: 'gait', amp: 14, amp2: 20, wave: 'pos', offset: HALF_PI },
        { ch: 'rz', drive: 'stagger', amp: -8 },
        { ch: 'rz', drive: 'death', amp: 40, window: [0.2, 0.7] },
        { ch: 'rz', drive: 'death', amp: 10, freq: 10, offset: 3, window: [0.6, 1] },
      ],
    },
  ],
  parts: [
    { shape: 'ellipsoid', bone: 'body', zone: 'chitin', center: [0, 0.16, 0.02], radii: [0.09, 0.06, 0.1] },
    {
      shape: 'ellipsoid',
      bone: 'abdomen',
      zone: 'glow',
      center: [0, 0.17, -0.12],
      radii: [0.11, 0.085, 0.13],
      lumpy: 0.006,
    },
    {
      shape: 'ellipsoid',
      bone: 'abdomen',
      zone: 'chitin',
      center: [0, 0.235, -0.06],
      radii: [0.08, 0.018, 0.07],
      rot: [-12, 0, 0],
      bend: -0.025,
    },
    { shape: 'ellipsoid', bone: 'head', zone: 'chitin', center: [0, 0.14, 0.12], radii: [0.05, 0.04, 0.05] },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.025, 0.165, 0.155],
      radii: [0.012, 0.012, 0.012],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'jaw_L',
      zone: 'bone',
      a: [0.025, 0.12, 0.15],
      b: [0.008, 0.11, 0.22],
      radius: 0.012,
      curve: [0.015, 0, 0],
      mirror: true,
    },
    // Legs: femur up to a high knee, tibia down to the floor.
    {
      shape: 'capsule',
      bone: 'legA_L',
      zone: 'chitin',
      a: [0.07, 0.15, 0.07],
      b: [0.16, 0.21, 0.13],
      radius: 0.012,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'legA_L',
      zone: 'chitin',
      a: [0.16, 0.21, 0.13],
      b: [0.22, 0, 0.19],
      radius: 0.01,
      curve: [0.02, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'legB_L',
      zone: 'chitin',
      a: [0.08, 0.15, 0.02],
      b: [0.18, 0.21, 0.04],
      radius: 0.012,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'legB_L',
      zone: 'chitin',
      a: [0.18, 0.21, 0.04],
      b: [0.25, 0, 0.05],
      radius: 0.01,
      curve: [0.02, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'legC_L',
      zone: 'chitin',
      a: [0.08, 0.15, -0.03],
      b: [0.18, 0.21, -0.06],
      radius: 0.012,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'legC_L',
      zone: 'chitin',
      a: [0.18, 0.21, -0.06],
      b: [0.24, 0, -0.09],
      radius: 0.01,
      curve: [0.02, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'legD_L',
      zone: 'chitin',
      a: [0.07, 0.15, -0.08],
      b: [0.15, 0.21, -0.15],
      radius: 0.012,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'legD_L',
      zone: 'chitin',
      a: [0.15, 0.21, -0.15],
      b: [0.2, 0, -0.22],
      radius: 0.01,
      curve: [0.02, 0.02, 0],
      mirror: true,
    },
  ],
  attacks: [{ id: 'bite', windup: 0.36, strike: 0.5, glow: 1.5 }],
  hitboxes: [
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 0.14, 0.13], radius: 0.07 },
    { bone: 'body', shape: 'capsule', zone: 'body', a: [0, 0.16, 0.12], b: [0, 0.17, -0.16], radius: 0.15 },
  ],
  sockets: {
    head: [{ bone: 'head', point: [0, 0.15, 0.13] }],
    jaws: [{ bone: 'head', point: [0, 0.12, 0.2] }],
    chest: [{ bone: 'body', point: [0, 0.17, 0.02] }],
    core: [{ bone: 'body', point: [0, 0.17, -0.06] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 60, pitchMaxDeg: 30 },
  cullMargin: 0.4,
  dissolve: { edgeColor: [0.2, 1, 0.8], edgeIntensity: 10, edgeWidth: 0.06, noiseScale: 16 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 0.4 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 0.35,
    death: 'enemy.death',
    deathScale: 0.3,
    deathSocket: 'core',
  },
};
