/**
 * Späher – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and TYPES
 * from '../enemyVisuals' (runtime cycle otherwise).
 *
 * A spindly stilt-walker: a compact chitin thorax slung between four long arched legs (knees high
 * above the body like a harvestman), a sail of tall dorsal spines, a segmented abdomen with a tail
 * spike, and a long lance-like head on a thin neck that ends in one big red lens – the scope the
 * laser leaves from (socket 'scope') and its weakpoint. Snipe: it crouches, the lance extends and
 * the lens blazes during the aim; the shot kicks the lance up. Stab: rears up and spears down with
 * a foreleg. Death: the legs splay and the body drops.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const RED: readonly [number, number, number] = [1, 0.13, 0.07];

export const SNIPER_VISUAL: EnemyVisualDef | null = {
  capacity: 12,
  zones: {
    chitin: {
      color: [0.04, 0.04, 0.045],
      color2: [0.09, 0.085, 0.09],
      tip: [0.24, 0.19, 0.15],
      tipAmount: 0.3,
      roughness: 0.3,
      metalness: 0.3,
      clearcoat: 0.9,
      emissive: RED,
      emissiveIntensity: 1.6,
      glow: 0,
      pulse: 0,
      veins: 0.12,
      bump: 1,
      cells: 0.7,
      scale: 3,
    },
    flesh: {
      color: [0.1, 0.03, 0.03],
      color2: [0.2, 0.06, 0.05],
      tip: [0.05, 0.015, 0.015],
      tipAmount: 0.4,
      roughness: 0.4,
      metalness: 0,
      clearcoat: 0.8,
      emissive: RED,
      emissiveIntensity: 3,
      glow: 0,
      pulse: 0,
      veins: 0.65,
      bump: 0.7,
      cells: 0.2,
      scale: 2.6,
    },
    bone: BONE,
    lens: {
      color: [0.3, 0.02, 0.02],
      color2: [0.45, 0.04, 0.03],
      tip: [0.3, 0.02, 0.02],
      tipAmount: 0,
      roughness: 0.05,
      metalness: 0,
      clearcoat: 1,
      emissive: RED,
      emissiveIntensity: 8,
      glow: 1,
      pulse: 0.3,
      veins: 0.2,
      bump: 0.2,
      cells: 0.4,
      scale: 8,
    },
    eyes: {
      color: [0.05, 0.01, 0.01],
      color2: [0.05, 0.01, 0.01],
      tip: [0.05, 0.01, 0.01],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [1, 0.22, 0.1],
      emissiveIntensity: 7,
      glow: 1,
      pulse: 0.2,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
  },
  bones: [
    {
      name: 'thorax',
      parent: null,
      pivot: [0, 1.45, 0],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -2.6 },
        { ch: 'rx', drive: 'emerge', amp: -25, window: [0.1, 1] },
        { ch: 'ty', drive: 'gait', amp: 0.03, amp2: 0.05, freq: 2 },
        { ch: 'rz', drive: 'gait', amp: 3, amp2: 4 },
        { ch: 'ry', drive: 'gait', amp: 3, amp2: 4, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 6, window: [0.5, 1] },
        { ch: 'ty', drive: 'idle', amp: 0.012, freq: 0.4 },
        { ch: 'rx', drive: 'idle', amp: 1.5, freq: 0.3, offset: 1 },
        // Snipe: crouch into the aim, the shot jolts it back.
        { ch: 'ty', drive: 'attack', attack: 'snipe', amp: -0.16, amp2: -0.22 },
        { ch: 'rx', drive: 'attack', attack: 'snipe', amp: -7, amp2: 3 },
        { ch: 'tz', drive: 'attack', attack: 'snipe', amp: -0.12, amp2: 0 },
        { ch: 'rx', drive: 'attack', attack: 'stab', amp: 16, amp2: -22 },
        { ch: 'ty', drive: 'attack', attack: 'stab', amp: -0.06, amp2: 0.14 },
        { ch: 'rx', drive: 'stagger', amp: -10 },
        { ch: 'tz', drive: 'stagger', amp: -0.08 },
        { ch: 'rz', drive: 'stagger', amp: 5, freq: 7 },
        { ch: 'ty', drive: 'death', amp: -1.12, window: [0.1, 0.7] },
        { ch: 'rz', drive: 'death', amp: 16, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: 8, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'abdomen',
      parent: 'thorax',
      pivot: [0, 1.47, -0.22],
      motions: [
        { ch: 's', drive: 'idle', amp: 0.03, freq: 0.6 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.3, offset: 2 },
        { ch: 'ry', drive: 'gait', amp: 4, amp2: 6, offset: HALF_PI + PI },
        { ch: 'rx', drive: 'attack', attack: 'snipe', amp: -10, amp2: -10 },
        { ch: 'rx', drive: 'stagger', amp: 10 },
        { ch: 'rx', drive: 'death', amp: -18, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'neck',
      parent: 'thorax',
      pivot: [0, 1.58, 0.2],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.45 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.45 },
        { ch: 'ry', drive: 'idle', amp: 3, freq: 0.21 },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 3, freq: 2, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'snipe', amp: -14, amp2: 0 },
        { ch: 'rx', drive: 'attack', attack: 'stab', amp: 12, amp2: -20 },
        { ch: 'rx', drive: 'stagger', amp: -18 },
        { ch: 'rx', drive: 'death', amp: 32, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'head',
      parent: 'neck',
      pivot: [0, 1.74, 0.62],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.5 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.55 },
        // Scanning twitches.
        { ch: 'rz', drive: 'idle', amp: 3, freq: 0.17 },
        { ch: 'ry', drive: 'idle', amp: 2.5, freq: 0.33, offset: 1 },
        { ch: 'tz', drive: 'attack', attack: 'snipe', amp: -0.05, amp2: 0.07 },
        { ch: 'rx', drive: 'attack', attack: 'snipe', amp: -9, amp2: 0 },
        { ch: 'ry', drive: 'stagger', amp: 12, freq: 6 },
        { ch: 'rx', drive: 'stagger', amp: -14 },
        { ch: 'rx', drive: 'death', amp: 25, window: [0.3, 0.9] },
        { ch: 'ry', drive: 'death', amp: 28, window: [0.5, 1] },
      ],
    },
    {
      name: 'mandible_L',
      parent: 'head',
      pivot: [0.05, 1.7, 0.7],
      mirror: true,
      motions: [
        { ch: 'ry', drive: 'idle', amp: 6, freq: 1.3 },
        { ch: 'ry', drive: 'attack', attack: 'snipe', amp: 12, amp2: -8 },
        { ch: 'ry', drive: 'attack', attack: 'stab', amp: -8, amp2: 25 },
        { ch: 'ry', drive: 'stagger', amp: 18 },
        { ch: 'ry', drive: 'death', amp: 25, window: [0.2, 0.6] },
      ],
    },
    {
      name: 'legF_L',
      parent: 'thorax',
      pivot: [0.16, 1.46, 0.14],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 12, amp2: 18 },
        { ch: 'rz', drive: 'gait', amp: 9, amp2: 13, wave: 'pos', offset: -HALF_PI },
        { ch: 'rz', drive: 'idle', amp: 1, freq: 0.3 },
        { ch: 'rz', drive: 'attack', attack: 'snipe', amp: 9, amp2: 11 },
        { ch: 'rz', drive: 'attack', attack: 'stab', amp: -6, amp2: 38, mirror: false },
        { ch: 'ry', drive: 'attack', attack: 'stab', amp: -44, amp2: -24, mirror: false },
        { ch: 'rz', drive: 'stagger', amp: -6 },
        { ch: 'rz', drive: 'death', amp: -42, window: [0.1, 0.7] },
      ],
    },
    {
      name: 'shinF_L',
      parent: 'legF_L',
      pivot: [0.55, 1.95, 0.42],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rz', drive: 'gait', amp: -10, amp2: -14, wave: 'pos', offset: -HALF_PI },
        { ch: 'rz', drive: 'attack', attack: 'snipe', amp: -12, amp2: -14 },
        { ch: 'rz', drive: 'attack', attack: 'stab', amp: 14, amp2: -30, mirror: false },
        { ch: 'rz', drive: 'death', amp: 52, window: [0.15, 0.75] },
        { ch: 'rz', drive: 'death', amp: 5, freq: 9, window: [0.7, 1] },
      ],
    },
    {
      name: 'legB_L',
      parent: 'thorax',
      pivot: [0.15, 1.44, -0.12],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'ry', drive: 'gait', amp: 12, amp2: 18, offset: PI },
        { ch: 'rz', drive: 'gait', amp: 9, amp2: 13, wave: 'pos', offset: HALF_PI },
        { ch: 'rz', drive: 'idle', amp: 1, freq: 0.3, offset: 2 },
        { ch: 'rz', drive: 'attack', attack: 'snipe', amp: 9, amp2: 11 },
        { ch: 'rz', drive: 'attack', attack: 'stab', amp: -8, amp2: -10 },
        { ch: 'rz', drive: 'stagger', amp: -6 },
        { ch: 'rz', drive: 'death', amp: -40, window: [0.1, 0.7] },
      ],
    },
    {
      name: 'shinB_L',
      parent: 'legB_L',
      pivot: [0.52, 1.9, -0.4],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rz', drive: 'gait', amp: -10, amp2: -14, wave: 'pos', offset: HALF_PI },
        { ch: 'rz', drive: 'attack', attack: 'snipe', amp: -12, amp2: -14 },
        { ch: 'rz', drive: 'attack', attack: 'stab', amp: 8, amp2: 10 },
        { ch: 'rz', drive: 'death', amp: 50, window: [0.15, 0.75] },
        { ch: 'rz', drive: 'death', amp: 5, freq: 8, offset: 1.3, window: [0.7, 1] },
      ],
    },
  ],
  parts: [
    // Thorax: flesh core under chitin plates, glowing vents, a sail of dorsal spines.
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'flesh',
      center: [0, 1.47, 0.02],
      radii: [0.19, 0.16, 0.28],
      lumpy: 0.012,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'chitin',
      center: [0, 1.6, 0.06],
      radii: [0.22, 0.045, 0.3],
      bend: -0.07,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'chitin',
      center: [0.16, 1.49, 0.03],
      radii: [0.035, 0.11, 0.25],
      rot: [0, 0, -14],
      bend: 0.03,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'chitin',
      center: [0, 1.38, 0.05],
      radii: [0.15, 0.035, 0.22],
      bend: 0.05,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'lens',
      center: [0.19, 1.44, 0.1],
      radii: [0.018, 0.03, 0.05],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'lens',
      center: [0.19, 1.44, -0.04],
      radii: [0.016, 0.026, 0.04],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'thorax',
      zone: 'bone',
      a: [0, 1.62, 0.14],
      b: [0, 2.04, -0.06],
      radius: 0.028,
      curve: [0, 0.04, 0.02],
    },
    {
      shape: 'spike',
      bone: 'thorax',
      zone: 'bone',
      a: [0, 1.63, -0.02],
      b: [0, 2.18, -0.26],
      radius: 0.032,
      curve: [0, 0.05, 0.02],
    },
    {
      shape: 'spike',
      bone: 'thorax',
      zone: 'bone',
      a: [0, 1.61, -0.16],
      b: [0, 1.96, -0.42],
      radius: 0.026,
      curve: [0, 0.04, 0.02],
    },
    {
      shape: 'spike',
      bone: 'thorax',
      zone: 'bone',
      a: [0.07, 1.61, 0.04],
      b: [0.13, 1.92, -0.12],
      radius: 0.018,
      curve: [0, 0.03, 0.01],
      mirror: true,
    },
    // Hip joints.
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'flesh',
      center: [0.17, 1.46, 0.13],
      radii: [0.06, 0.06, 0.06],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'thorax',
      zone: 'flesh',
      center: [0.16, 1.44, -0.12],
      radii: [0.06, 0.06, 0.06],
      mirror: true,
    },
    // Abdomen + tail spike.
    {
      shape: 'ellipsoid',
      bone: 'abdomen',
      zone: 'flesh',
      center: [0, 1.44, -0.52],
      radii: [0.17, 0.15, 0.32],
      lumpy: 0.014,
    },
    {
      shape: 'ellipsoid',
      bone: 'abdomen',
      zone: 'chitin',
      center: [0, 1.56, -0.4],
      radii: [0.17, 0.04, 0.14],
      rot: [8, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'ellipsoid',
      bone: 'abdomen',
      zone: 'chitin',
      center: [0, 1.54, -0.62],
      radii: [0.15, 0.04, 0.14],
      rot: [18, 0, 0],
      bend: -0.06,
    },
    {
      shape: 'spike',
      bone: 'abdomen',
      zone: 'bone',
      a: [0, 1.4, -0.8],
      b: [0, 1.16, -1.08],
      radius: 0.035,
      curve: [0, -0.02, -0.04],
    },
    // Neck: thin flesh under a chitin sheath.
    {
      shape: 'capsule',
      bone: 'neck',
      zone: 'flesh',
      a: [0, 1.56, 0.18],
      b: [0, 1.74, 0.64],
      radius: 0.07,
      radiusB: 0.05,
      lumpy: 0.006,
    },
    {
      shape: 'ellipsoid',
      bone: 'neck',
      zone: 'chitin',
      center: [0, 1.7, 0.42],
      radii: [0.07, 0.03, 0.22],
      rot: [-22, 0, 0],
      bend: -0.04,
    },
    // Head: housing, lance barrel with a ridge, the lens in a chitin rim, side eyes, mandibles.
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.76, 0.72],
      radii: [0.09, 0.08, 0.16],
    },
    {
      shape: 'capsule',
      bone: 'head',
      zone: 'chitin',
      a: [0, 1.76, 0.8],
      b: [0, 1.77, 1.1],
      radius: 0.048,
      radiusB: 0.036,
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0, 1.82, 0.66],
      b: [0, 1.84, 1.02],
      radius: 0.02,
      curve: [0, 0.015, 0],
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'chitin',
      center: [0, 1.77, 1.11],
      radii: [0.075, 0.075, 0.03],
    },
    { shape: 'ellipsoid', bone: 'head', zone: 'lens', center: [0, 1.77, 1.14], radii: [0.06, 0.06, 0.03] },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.075, 1.79, 0.76],
      radii: [0.014, 0.014, 0.014],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.07, 1.76, 0.82],
      radii: [0.01, 0.01, 0.01],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'mandible_L',
      zone: 'bone',
      a: [0.05, 1.7, 0.7],
      b: [0.07, 1.6, 0.88],
      radius: 0.016,
      curve: [-0.01, 0, 0.02],
      mirror: true,
    },
    // Legs: chitin stilts with flesh knees, knee spikes and needle feet.
    {
      shape: 'capsule',
      bone: 'legF_L',
      zone: 'chitin',
      a: [0.17, 1.46, 0.14],
      b: [0.55, 1.95, 0.42],
      radius: 0.05,
      radiusB: 0.035,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'shinF_L',
      zone: 'flesh',
      center: [0.55, 1.95, 0.42],
      radii: [0.045, 0.045, 0.045],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shinF_L',
      zone: 'bone',
      a: [0.56, 1.97, 0.42],
      b: [0.6, 2.16, 0.34],
      radius: 0.02,
      curve: [0, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'shinF_L',
      zone: 'chitin',
      a: [0.55, 1.95, 0.42],
      b: [0.74, 0.34, 0.66],
      radius: 0.032,
      radiusB: 0.022,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shinF_L',
      zone: 'bone',
      a: [0.74, 0.36, 0.66],
      b: [0.78, 0.0, 0.72],
      radius: 0.022,
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'legB_L',
      zone: 'chitin',
      a: [0.16, 1.44, -0.12],
      b: [0.52, 1.9, -0.4],
      radius: 0.048,
      radiusB: 0.034,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'shinB_L',
      zone: 'flesh',
      center: [0.52, 1.9, -0.4],
      radii: [0.043, 0.043, 0.043],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shinB_L',
      zone: 'bone',
      a: [0.53, 1.92, -0.4],
      b: [0.57, 2.1, -0.46],
      radius: 0.019,
      curve: [0, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'capsule',
      bone: 'shinB_L',
      zone: 'chitin',
      a: [0.52, 1.9, -0.4],
      b: [0.7, 0.34, -0.72],
      radius: 0.031,
      radiusB: 0.021,
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'shinB_L',
      zone: 'bone',
      a: [0.7, 0.36, -0.72],
      b: [0.73, 0.0, -0.78],
      radius: 0.021,
      mirror: true,
    },
  ],
  attacks: [
    // The lens brightens over the whole aim (glow rides the wind-up envelope).
    { id: 'snipe', windup: 0.6, strike: 0.68, glow: 3 },
    { id: 'stab', windup: 0.38, strike: 0.56, glow: 0.8 },
  ],
  hitboxes: [
    { bone: 'head', shape: 'sphere', zone: 'weakpoint', a: [0, 1.77, 1.13], radius: 0.1 },
    { bone: 'head', shape: 'capsule', zone: 'head', a: [0, 1.76, 0.66], b: [0, 1.77, 1.04], radius: 0.09 },
    { bone: 'neck', shape: 'capsule', zone: 'body', a: [0, 1.57, 0.2], b: [0, 1.73, 0.6], radius: 0.08 },
    { bone: 'thorax', shape: 'capsule', zone: 'body', a: [0, 1.47, -0.2], b: [0, 1.48, 0.26], radius: 0.22 },
    {
      bone: 'abdomen',
      shape: 'capsule',
      zone: 'body',
      a: [0, 1.44, -0.3],
      b: [0, 1.42, -0.78],
      radius: 0.17,
    },
    {
      bone: 'legF_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.17, 1.46, 0.14],
      b: [0.55, 1.95, 0.42],
      radius: 0.06,
      mirror: true,
    },
    {
      bone: 'shinF_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.55, 1.95, 0.42],
      b: [0.77, 0.05, 0.71],
      radius: 0.05,
      mirror: true,
    },
    {
      bone: 'legB_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.16, 1.44, -0.12],
      b: [0.52, 1.9, -0.4],
      radius: 0.06,
      mirror: true,
    },
    {
      bone: 'shinB_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.52, 1.9, -0.4],
      b: [0.72, 0.05, -0.77],
      radius: 0.05,
      mirror: true,
    },
  ],
  sockets: {
    scope: [{ bone: 'head', point: [0, 1.77, 1.19] }],
    head: [{ bone: 'head', point: [0, 1.77, 0.8] }],
    chest: [{ bone: 'thorax', point: [0, 1.5, 0.12] }],
    core: [{ bone: 'thorax', point: [0, 1.47, 0] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 60, pitchMaxDeg: 40 },
  cullMargin: 1,
  dissolve: { edgeColor: [1, 0.18, 0.08], edgeIntensity: 12, edgeWidth: 0.08, noiseScale: 7 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 1.1 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 1.1,
    death: 'enemy.death.armor',
    deathScale: 1,
    deathSocket: 'core',
  },
};
