/**
 * Beschwörer – enemy visual def (M6). Import runtime values only from '../enemyVisualCommon' and
 * TYPES from '../enemyVisuals' (runtime cycle otherwise).
 *
 * A tall, hunched rift-caller in a tattered robe: a pointed hood over a shadowed face with two
 * violet eyes and a bone jaw, a crown of bone spines, two long horns rising from its back, flared
 * sleeves with long-fingered skeletal hands, faintly glowing rune veins in the cloth. The parted
 * robe shows a pulsing rift heart in the ribcage (weakpoint). Summon: the arms rise, the head tips
 * back and the crown spreads while the heart blazes (the channel), then the hands thrust down as
 * the rift erupts. Death: it sinks into its collapsing robe.
 */
import type { EnemyVisualDef } from '../enemyVisuals';
import { BONE, HALF_PI, PI, RIFT_VIOLET } from '../enemyVisualCommon';

const VIOLET: readonly [number, number, number] = [0.6, 0.25, 1];

/** Tattered robe strips around the hem: [x, z, yaw DEGREES]. */
const HEM: readonly (readonly [number, number, number])[] = [
  [0.2, 0.28, 36],
  [0.33, 0.02, 88],
  [0.24, -0.25, 136],
];

export const SUMMONER_VISUAL: EnemyVisualDef | null = {
  capacity: 10,
  zones: {
    robe: {
      color: [0.03, 0.022, 0.035],
      color2: [0.065, 0.048, 0.075],
      tip: [0.012, 0.009, 0.015],
      tipAmount: 0.55,
      roughness: 0.78,
      metalness: 0,
      clearcoat: 0.08,
      emissive: VIOLET,
      emissiveIntensity: 3.6,
      glow: 0,
      pulse: 0,
      veins: 0.45,
      bump: 0.55,
      cells: 0.12,
      scale: 2,
    },
    flesh: {
      color: [0.13, 0.11, 0.14],
      color2: [0.22, 0.19, 0.22],
      tip: [0.05, 0.04, 0.055],
      tipAmount: 0.5,
      roughness: 0.5,
      metalness: 0,
      clearcoat: 0.4,
      emissive: VIOLET,
      emissiveIntensity: 3,
      glow: 0,
      pulse: 0,
      veins: 0.55,
      bump: 0.6,
      cells: 0.25,
      scale: 3,
    },
    bone: BONE,
    heart: {
      color: [0.2, 0.06, 0.3],
      color2: [0.34, 0.12, 0.45],
      tip: [0.2, 0.06, 0.3],
      tipAmount: 0,
      roughness: 0.1,
      metalness: 0,
      clearcoat: 1,
      emissive: [0.66, 0.3, 1],
      emissiveIntensity: 7,
      glow: 1,
      pulse: 0.5,
      veins: 0.4,
      bump: 0.4,
      cells: 0.6,
      scale: 4,
    },
    eyes: {
      color: [0.04, 0.01, 0.06],
      color2: [0.04, 0.01, 0.06],
      tip: [0.04, 0.01, 0.06],
      tipAmount: 0,
      roughness: 0.08,
      metalness: 0,
      clearcoat: 1,
      emissive: [0.78, 0.45, 1],
      emissiveIntensity: 9,
      glow: 1,
      pulse: 0.25,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 12,
    },
    shadow: {
      color: [0.004, 0.003, 0.006],
      color2: [0.008, 0.005, 0.01],
      tip: [0.004, 0.003, 0.006],
      tipAmount: 0,
      roughness: 1,
      metalness: 0,
      clearcoat: 0,
      emissive: VIOLET,
      emissiveIntensity: 0.3,
      glow: 0.3,
      pulse: 0.3,
      veins: 0,
      bump: 0,
      cells: 0,
      scale: 4,
    },
    sigil: {
      color: [0.1, 0.04, 0.16],
      color2: [0.16, 0.07, 0.24],
      tip: [0.1, 0.04, 0.16],
      tipAmount: 0,
      roughness: 0.2,
      metalness: 0.3,
      clearcoat: 1,
      emissive: VIOLET,
      emissiveIntensity: 5,
      glow: 0.9,
      pulse: 0.6,
      veins: 0,
      bump: 0.2,
      cells: 0.5,
      scale: 6,
    },
  },
  bones: [
    {
      name: 'body',
      parent: null,
      pivot: [0, 1.0, 0],
      motions: [
        { ch: 'ty', drive: 'emerge', amp: -2.9 },
        { ch: 'rx', drive: 'emerge', amp: -18, window: [0.1, 1] },
        { ch: 'ty', drive: 'gait', amp: 0.025, amp2: 0.04, freq: 2 },
        { ch: 'rz', drive: 'gait', amp: 2, amp2: 3 },
        { ch: 'ry', drive: 'gait', amp: 3, amp2: 4, offset: HALF_PI },
        { ch: 'rx', drive: 'loco', amp: 6, window: [0.5, 1] },
        { ch: 'ty', drive: 'idle', amp: 0.01, freq: 0.3 },
        // Channel: it rises and leans back, then crouches into the release.
        { ch: 'ty', drive: 'attack', attack: 'summon', amp: -0.08, amp2: 0.1 },
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: 12, amp2: -6 },
        { ch: 'ry', drive: 'attack', attack: 'claw', amp: -24, amp2: 20 },
        { ch: 'rx', drive: 'stagger', amp: -10 },
        { ch: 'tz', drive: 'stagger', amp: -0.1 },
        { ch: 'rz', drive: 'stagger', amp: 4, freq: 6 },
        { ch: 'ty', drive: 'death', amp: -0.78, window: [0.1, 0.65] },
        { ch: 'rx', drive: 'death', amp: 22, window: [0.4, 1] },
        { ch: 'rz', drive: 'death', amp: 8, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'robe',
      parent: 'body',
      pivot: [0, 1.05, -0.03],
      motions: [
        { ch: 'ry', drive: 'gait', amp: 3, amp2: 5, offset: HALF_PI + PI },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 3, freq: 2, offset: 1 },
        { ch: 'rz', drive: 'idle', amp: 1.5, freq: 0.25 },
        { ch: 'rx', drive: 'loco', amp: -6, window: [0.4, 1] },
        // The hem flutters in the rift wind while channelling.
        { ch: 'sx', drive: 'attack', attack: 'summon', amp: 0.04, amp2: 0.1 },
        { ch: 'sz', drive: 'attack', attack: 'summon', amp: 0.04, amp2: 0.1 },
        { ch: 'rz', drive: 'attack', attack: 'summon', amp: 3, freq: 5 },
        { ch: 'sy', drive: 'death', amp: -0.55, window: [0.15, 0.85] },
        { ch: 'sx', drive: 'death', amp: 0.18, window: [0.3, 1] },
        { ch: 'sz', drive: 'death', amp: 0.18, window: [0.3, 1] },
      ],
    },
    {
      name: 'chest',
      parent: 'body',
      pivot: [0, 1.22, -0.05],
      motions: [
        { ch: 'rx', drive: 'rest', amp: 12 },
        { ch: 's', drive: 'idle', amp: 0.015, freq: 0.35 },
        { ch: 'rx', drive: 'idle', amp: 1.5, freq: 0.2, offset: 1 },
        { ch: 'rx', drive: 'gait', amp: 2, amp2: 3, freq: 2, offset: 1.5 },
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: 14, amp2: -20 },
        { ch: 'ry', drive: 'attack', attack: 'claw', amp: -28, amp2: 26 },
        { ch: 'rx', drive: 'attack', attack: 'claw', amp: 12, amp2: -6 },
        { ch: 'rx', drive: 'stagger', amp: -12 },
        { ch: 'rx', drive: 'death', amp: 26, window: [0.3, 1] },
      ],
    },
    {
      name: 'head',
      parent: 'chest',
      pivot: [0, 1.7, 0.08],
      motions: [
        { ch: 'ry', drive: 'lookYaw', amp: 0.75 },
        { ch: 'rx', drive: 'lookPitch', amp: 0.6 },
        { ch: 'ry', drive: 'idle', amp: 4, freq: 0.18 },
        { ch: 'rz', drive: 'idle', amp: 3, freq: 0.12, offset: 2 },
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: 12, amp2: -24 },
        { ch: 'rx', drive: 'stagger', amp: -20 },
        { ch: 'ry', drive: 'stagger', amp: 8, freq: 5 },
        { ch: 'rx', drive: 'death', amp: 42, window: [0.2, 0.8] },
      ],
    },
    {
      name: 'crown',
      parent: 'head',
      pivot: [0, 2.0, 0.0],
      motions: [
        { ch: 'ry', drive: 'idle', amp: 6, freq: 0.1 },
        { ch: 's', drive: 'attack', attack: 'summon', amp: 0.05, amp2: 0.18 },
        { ch: 'ry', drive: 'attack', attack: 'summon', amp: 14, freq: 0.5 },
        { ch: 's', drive: 'stagger', amp: 0.06, freq: 8 },
        { ch: 's', drive: 'death', amp: -0.3, window: [0.3, 1] },
      ],
    },
    {
      name: 'arm_L',
      parent: 'chest',
      pivot: [0.22, 1.6, 0.0],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rz', drive: 'rest', amp: 8 },
        { ch: 'rx', drive: 'rest', amp: -8 },
        { ch: 'rx', drive: 'gait', amp: -5, amp2: -8 },
        { ch: 'rx', drive: 'idle', amp: 3, freq: 0.28 },
        // Channel: both hands raised to the rift; release: thrust down at it.
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: -30, amp2: -78 },
        { ch: 'rz', drive: 'attack', attack: 'summon', amp: 8, amp2: 24 },
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: 3, freq: 4 },
        { ch: 'rx', drive: 'attack', attack: 'claw', amp: 42, amp2: -92, mirror: false },
        { ch: 'ry', drive: 'attack', attack: 'claw', amp: 28, amp2: -30, mirror: false },
        { ch: 'rz', drive: 'stagger', amp: 18 },
        { ch: 'rz', drive: 'death', amp: -18, window: [0.3, 0.9] },
        { ch: 'rx', drive: 'death', amp: 30, window: [0.3, 0.9] },
      ],
    },
    {
      name: 'forearm_L',
      parent: 'arm_L',
      pivot: [0.3, 1.25, 0.1],
      mirror: true,
      mirrorPhase: PI,
      motions: [
        { ch: 'rx', drive: 'rest', amp: -30 },
        { ch: 'rx', drive: 'idle', amp: 5, freq: 0.32, offset: 1 },
        { ch: 'rx', drive: 'attack', attack: 'summon', amp: -8, amp2: -24 },
        { ch: 'rx', drive: 'attack', attack: 'claw', amp: 35, amp2: -30, mirror: false },
        { ch: 'rx', drive: 'stagger', amp: 15 },
        { ch: 'rx', drive: 'death', amp: 35, window: [0.4, 1] },
      ],
    },
  ],
  parts: [
    // Robe skirt down to the floor with tattered strips at the hem.
    {
      shape: 'lathe',
      bone: 'robe',
      zone: 'robe',
      a: [0, 1.18, -0.03],
      b: [0, 0.02, -0.06],
      profile: [
        [0, 0.12],
        [0.2, 0.2],
        [0.55, 0.28],
        [0.88, 0.36],
        [1, 0.37],
      ],
      ellipse: [1, 0.9],
      lumpy: 0.02,
    },
    ...HEM.map(
      ([x, z, yaw]) =>
        ({
          shape: 'ellipsoid',
          bone: 'robe',
          zone: 'robe',
          center: [x, 0.13, z - 0.05],
          radii: [0.08, 0.014, 0.15],
          rot: [78, yaw, 0],
          bend: -0.03,
          mirror: true,
        }) as const,
    ),
    {
      shape: 'ellipsoid',
      bone: 'robe',
      zone: 'robe',
      center: [0, 0.13, -0.42],
      radii: [0.09, 0.014, 0.16],
      rot: [78, 180, 0],
      bend: -0.03,
    },
    // Rune plates on the robe front.
    {
      shape: 'ellipsoid',
      bone: 'robe',
      zone: 'sigil',
      center: [0.1, 0.8, 0.2],
      radii: [0.03, 0.05, 0.012],
      rot: [-10, 20, 0],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'robe',
      zone: 'sigil',
      center: [0, 0.55, 0.26],
      radii: [0.035, 0.06, 0.012],
      rot: [-12, 0, 0],
    },
    // Torso under the robe: flesh, ribs over the rift heart.
    {
      shape: 'lathe',
      bone: 'chest',
      zone: 'flesh',
      a: [0, 1.1, -0.05],
      b: [0, 1.68, 0.04],
      profile: [
        [0, 0.12],
        [0.3, 0.16],
        [0.7, 0.19],
        [0.9, 0.17],
        [1, 0.08],
      ],
      ellipse: [1, 0.78],
      lumpy: 0.012,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'heart',
      center: [0, 1.42, 0.1],
      radii: [0.08, 0.1, 0.06],
      lumpy: 0.006,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.02, 1.52, 0.16],
        [0.12, 1.5, 0.12],
        [0.17, 1.46, 0.02],
      ],
      radius: 0.013,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.02, 1.42, 0.17],
        [0.12, 1.4, 0.13],
        [0.17, 1.36, 0.02],
      ],
      radius: 0.013,
      radiusB: 0.009,
      mirror: true,
    },
    {
      shape: 'tube',
      bone: 'chest',
      zone: 'bone',
      points: [
        [0.02, 1.32, 0.15],
        [0.11, 1.3, 0.11],
        [0.15, 1.26, 0.02],
      ],
      radius: 0.012,
      radiusB: 0.008,
      mirror: true,
    },
    // Mantle: the robe over back and shoulders, parted at the front.
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'robe',
      center: [0, 1.42, -0.1],
      radii: [0.27, 0.04, 0.34],
      rot: [-82, 0, 0],
      bend: -0.15,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'robe',
      center: [0.15, 1.36, 0.1],
      radii: [0.09, 0.028, 0.34],
      rot: [-86, -28, 0],
      bend: -0.05,
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'chest',
      zone: 'robe',
      center: [0.19, 1.64, 0.0],
      radii: [0.16, 0.04, 0.2],
      rot: [0, 0, -26],
      bend: -0.08,
      mirror: true,
    },
    // Horns rising from the back.
    {
      shape: 'spike',
      bone: 'chest',
      zone: 'bone',
      a: [0.1, 1.6, -0.14],
      b: [0.3, 2.34, -0.36],
      radius: 0.035,
      curve: [0.04, 0.04, 0.06],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'chest',
      zone: 'bone',
      a: [0.08, 1.48, -0.16],
      b: [0.22, 2.02, -0.42],
      radius: 0.026,
      curve: [0.03, 0.02, 0.05],
      mirror: true,
    },
    // Hood: pointed cowl over a shadowed face, violet eyes, bone jaw with tusks, a brim.
    {
      shape: 'lathe',
      bone: 'head',
      zone: 'robe',
      a: [0, 1.66, -0.02],
      b: [0, 2.14, -0.1],
      profile: [
        [0, 0.12],
        [0.25, 0.17],
        [0.55, 0.16],
        [0.85, 0.08],
        [1, 0],
      ],
      ellipse: [0.95, 1],
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'shadow',
      center: [0, 1.84, 0.12],
      radii: [0.1, 0.13, 0.06],
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'robe',
      center: [0, 1.97, 0.1],
      radii: [0.14, 0.03, 0.1],
      rot: [-24, 0, 0],
      bend: -0.05,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'eyes',
      center: [0.036, 1.86, 0.172],
      radii: [0.018, 0.012, 0.012],
      rot: [0, 0, -12],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'head',
      zone: 'bone',
      center: [0, 1.74, 0.15],
      radii: [0.06, 0.03, 0.05],
    },
    {
      shape: 'spike',
      bone: 'head',
      zone: 'bone',
      a: [0.035, 1.73, 0.18],
      b: [0.04, 1.62, 0.2],
      radius: 0.012,
      curve: [0, 0, 0.015],
      mirror: true,
    },
    // Crown of bone spines around the hood.
    {
      shape: 'spike',
      bone: 'crown',
      zone: 'bone',
      a: [0, 2.02, 0.06],
      b: [0, 2.36, 0.1],
      radius: 0.018,
      curve: [0, 0.02, 0.02],
    },
    {
      shape: 'spike',
      bone: 'crown',
      zone: 'bone',
      a: [0.07, 2.0, 0.04],
      b: [0.2, 2.3, 0.06],
      radius: 0.016,
      curve: [0.01, 0.02, 0.01],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'crown',
      zone: 'bone',
      a: [0.1, 1.97, -0.04],
      b: [0.28, 2.2, -0.08],
      radius: 0.015,
      curve: [0.02, 0.02, 0],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'crown',
      zone: 'sigil',
      center: [0, 2.03, 0.12],
      radii: [0.025, 0.035, 0.012],
      rot: [-20, 0, 0],
    },
    // Sleeves (flared at the cuff) and long skeletal hands.
    {
      shape: 'capsule',
      bone: 'arm_L',
      zone: 'robe',
      a: [0.22, 1.6, 0.0],
      b: [0.3, 1.25, 0.1],
      radius: 0.07,
      radiusB: 0.065,
      mirror: true,
    },
    {
      shape: 'lathe',
      bone: 'forearm_L',
      zone: 'robe',
      a: [0.3, 1.27, 0.09],
      b: [0.34, 0.95, 0.27],
      profile: [
        [0, 0.06],
        [0.5, 0.08],
        [0.9, 0.12],
        [1, 0.12],
      ],
      mirror: true,
    },
    {
      shape: 'ellipsoid',
      bone: 'forearm_L',
      zone: 'flesh',
      center: [0.35, 0.9, 0.31],
      radii: [0.035, 0.05, 0.03],
      rot: [30, 0, 0],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.37, 0.88, 0.32],
      b: [0.42, 0.7, 0.4],
      radius: 0.011,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.35, 0.87, 0.33],
      b: [0.36, 0.67, 0.43],
      radius: 0.011,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.33, 0.88, 0.32],
      b: [0.29, 0.69, 0.4],
      radius: 0.01,
      curve: [0, 0, 0.02],
      mirror: true,
    },
    {
      shape: 'spike',
      bone: 'forearm_L',
      zone: 'bone',
      a: [0.32, 0.9, 0.3],
      b: [0.26, 0.76, 0.34],
      radius: 0.009,
      curve: [0, 0, 0.015],
      mirror: true,
    },
  ],
  attacks: [
    // The heart and eyes blaze up over the channel (glow rides the wind-up envelope).
    { id: 'summon', windup: 0.72, strike: 0.82, glow: 2.6 },
    { id: 'claw', windup: 0.38, strike: 0.56, glow: 0.6 },
  ],
  hitboxes: [
    { bone: 'chest', shape: 'sphere', zone: 'weakpoint', a: [0, 1.42, 0.11], radius: 0.11 },
    { bone: 'head', shape: 'sphere', zone: 'head', a: [0, 1.85, 0.06], radius: 0.15 },
    { bone: 'chest', shape: 'capsule', zone: 'body', a: [0, 1.15, -0.04], b: [0, 1.62, 0.0], radius: 0.23 },
    { bone: 'robe', shape: 'capsule', zone: 'body', a: [0, 0.25, -0.05], b: [0, 1.0, -0.04], radius: 0.3 },
    {
      bone: 'arm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.22, 1.6, 0.0],
      b: [0.3, 1.25, 0.1],
      radius: 0.08,
      mirror: true,
    },
    {
      bone: 'forearm_L',
      shape: 'capsule',
      zone: 'limb',
      a: [0.3, 1.25, 0.1],
      b: [0.36, 0.78, 0.36],
      radius: 0.08,
      mirror: true,
    },
  ],
  sockets: {
    hands: [
      { bone: 'forearm_L', point: [0.35, 0.86, 0.34] },
      { bone: 'forearm_R', point: [-0.35, 0.86, 0.34] },
    ],
    head: [{ bone: 'head', point: [0, 1.85, 0.1] }],
    chest: [{ bone: 'chest', point: [0, 1.45, 0.14] }],
    core: [{ bone: 'chest', point: [0, 1.4, 0.0] }],
  },
  aimSocket: 'chest',
  look: { yawMaxDeg: 55, pitchMaxDeg: 35 },
  cullMargin: 1,
  dissolve: { edgeColor: [0.7, 0.35, 1], edgeIntensity: 12, edgeWidth: 0.08, noiseScale: 6 },
  rift: { color: RIFT_VIOLET, intensity: 14, tearRadius: 1 },
  effects: {
    spawn: 'rift.spawn',
    spawnScale: 1.1,
    death: 'enemy.death',
    deathScale: 1,
    deathSocket: 'core',
  },
};
